### ISSUE TITLE
captureMessage works but real crashes don't get sent

### ISSUE THREAD

**Issue by timothylui** [getsentry/react-native-sentry#10]
I've set this up as described (with bitcode turned on).

I can successfully send a message to sentry using captureMessage, but real JS crashes don't get sent neither does artificial native crashes Sentry.nativeCrash(). This is all using debug builds on IOS running in the simulator.

Any idea what I should look at? I've followed the guide properly afaik and turning on debug as below doesn't yield anything useful.

Sentry.config(SENTRY_DSN,{
    logLevel: SentryLog.Debug
}).install();

Thanks

**Comment by HazAT** [comment]
Please make sure you also added the code to you `AppDelegate.m`

https://docs.sentry.io/clients/react-native/#client-configuration

Also note that `nativeCrash` will only work if the app is not attached to the debugger in Xcode.

**Comment by brunolemos** [comment]
Is `captureMessage` a replacement to `Raven.captureException`? I could not find a method that accepts an Error object like `captureException`.

**Comment by timbuckley** [comment]
@brunolemos `captureException` is still exposed by Sentry. It just calls Raven for you. https://github.com/getsentry/react-native-sentry/blob/5b84fe9bfbbf9a4b127bce2a1d890a92c0346572/lib/Sentry.js#L112

```js
static captureException(ex, options) {
    Sentry._ravenClient.captureException(ex, options);
}
```

**Comment by brunolemos** [comment]
@timbuckley thanks (apparently it was added 1 week after my comment above https://github.com/getsentry/react-native-sentry/commit/4b70baf1f16f5c33d81ee5fb4397cc8541501432)

**Comment by HazAT** [comment]
Yeah, sorry for not updating the issue, we are currently adding so much that it's hard to keep track of everything 😅

**Comment by HazAT** [comment]
Checkout latest release, this should work now since we use raven-js internally
