### ISSUE TITLE
DEPLOYMENT_TARGET_HIGHER_THAN_10 improperly set?

### ISSUE THREAD

**Issue by btoueg** [getsentry/react-native-sentry#100]
I've updated my app to use `RN 0.45.0` and `react-native-sentry 0.12.10`. It works fine on iOS 10.3.2 but crashes at launch on iOS 9.3.1

Looking at the stack with pause on exception, I see that we are indeed chosing the RN 0.45.0 path:
![image](https://user-images.githubusercontent.com/498190/27080514-7da11f6a-503c-11e7-9270-ce4bc4debca5.png)

However, further down the stack, it looks like it's chosing the path for iOS 10 even though the device is on `iOS 9.3.1` where `os_unfair_lock` is not available (reading the comments):
![image](https://user-images.githubusercontent.com/498190/27080550-ac3d1de2-503c-11e7-8204-aa2c27126316.png)

**Comment by HazAT** [comment]
Looking into this, thanks for reporting.
