### ISSUE TITLE
Support for multiple Sentry projects and build types

### ISSUE THREAD

**Issue by davidstoker** [getsentry/react-native-sentry#104]
I'm new to using Sentry and currently trying to understand how multiple build types are expected to be handled with this RN package? Is there support or plans for supporting different build types being associated to different Sentry projects -- beta and production builds for example?

I understand that I can change the DSN in my JS but the gradle script for uploading source maps is currently set to use the single `sentry.properties` file for configuring the sentry-cli command and doesn't provide a way for setting different project names per build type.

**Comment by HazAT** [comment]
I am not sure if we will add support for that at some point in the future, possibly.
But you can work around that if you take out the `project` variable from `sentry.properties` and pass `SENTRY_PROJECT=your-project` somewhere as a `env` variable.
This should achieve the same result.
Hope this helps.
