### ISSUE TITLE
Perform issue

### ISSUE THREAD

**Issue by damoguyan8844** [getsentry/react-native-sentry#109]
It takes more than 5s for landing page, when takes only 2s without sentry installed.  Do you have any suggestion?

Env:
"react": "15.4.2",
"react-native": "0.42.3",
"react-native-sentry": "0.8.1",

**Comment by HazAT** [comment]
Try to set `deactivateStacktraceMerging: true`, depending on how much is sent over the javascript bridge, this can be very demanding. 
But before doing that, try to update to the latest `react-native-sentry` version, we added several performance improvements.
https://docs.sentry.io/clients/react-native/config/

**Comment by messense** [comment]
@HazAT I am using latest `react-native-sentry` and have the same issue.

set `deactivateStacktraceMerging: true` solves the prolem.

**Comment by hasLandon** [comment]
Thank you for the quick reply @HazAT. In my case, disabling stacktrace merging makes my application go from being unusable to pretty performant. It's a night and day difference 😳

**Comment by damoguyan8844** [comment]
@HazAT , Thanks, I will try.

**Comment by HazAT** [comment]
Does anyone here have their app open source?
I am curious to debug it and see what's the bottleneck.
Also feel free to write me directly to daniel@sentry.io

**Comment by hasLandon** [comment]
Sadly our app is not open source and is quite large, so it would be hard to use to find the root cause. I can ask if I would be allowed to email you directly with the source though.

**Comment by hasLandon** [comment]
I don't think I'm going to be able to send our app 😞 Sorry about that
