### ISSUE TITLE
Sentry.framework/Sentry Reason: image not found

### ISSUE THREAD

**Issue by brunolemos** [getsentry/react-native-sentry#11]
I have already set `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` to `YES` as the docs say (on both Target and Project), but I still have the error:

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: .../Sentry.framework/Sentry
  Reason: image not found
(lldb) 
```

I have also cleaned the project, relinked the lib using `react-native link` and added `use_frameworks!` to `Podfile`.

**Comment by HazAT** [comment]
Did you also add?
https://docs.sentry.io/clients/react-native/#xcode-build-steps

**Comment by brunolemos** [comment]
Hey, I uninstalled and installed again. It works now (the app opens).
I'm not sure what caused it, but all right!

**Comment by r06921078** [comment]
..
