### ISSUE TITLE
What do I need auth.token for?

### ISSUE THREAD

**Issue by simPod** [getsentry/react-native-sentry#112]
In `sentry.properties` there's a property `auth.token`. What do I need it for? Is it safe to bundle my auth token into the app?

Thanks!

**Comment by HazAT** [comment]
The `auth.token` is used for uploading sourcemaps and debug symbols to sentry in order so we can symbolicate the crash correctly.
There is no need to bundle `sentry.properties` in your app.

**Comment by simPod** [comment]
Oh kk thanks. BTW what all permissions are needed for the access token?

**Comment by HazAT** [comment]
Good question, I believe it's just `project:releases` but don’t pin me down to that 😅

**Comment by suksoom** [comment]
#123

**Comment by simPod** [comment]
@HazAT created an access token with release rights only and it worked 👍 

@suksoom ?

**Comment by tuneZola** [comment]
I cannot find a place to get the auth token in the sentry UI. Is it project based or in the org settings?

**Comment by HazAT** [comment]
@tuneZola https://sentry.io/api/

**Comment by tuneZola** [comment]
@HazAT Where would this be stored at? I cannot find a list of keys in the Sentry UI.

**Comment by HazAT** [comment]
![screenshot 2017-08-22 15 39 53](https://user-images.githubusercontent.com/363802/29590743-2b7af7f6-8750-11e7-92a4-ee13fc646508.png)

Click on the little icon on the bottom left, and then on API
