### ISSUE TITLE
Capturing Redux State

### ISSUE THREAD

**Issue by jarredwitt** [getsentry/react-native-sentry#113]
I've been trying to figure out a way to capture my redux state along with the last two actions to send along with Sentry exceptions, but I'm not having much luck. I've been thinking that a middleware would be the best approach and I've tried using `setExtraContext` to record the actions, but can't seem to get that too work. Is `setExtraContext` the best approach for this? I saw that there is an internal `addExtraContext` that accepts a key/value but haven't tried that yet.

**Comment by ndbroadbent** [comment]
+1, this would be amazing. @jarredwitt, please let me know if you figure anything out.

**Comment by HazAT** [comment]
I would go ahead and add breadcrumbs, the system is meant for that.

There is also a redux middleware handling that.
https://github.com/ngokevin/redux-raven-middleware
I've never tested it though.

**Comment by ndbroadbent** [comment]
@HazAT thanks for the tip about that Redux middleware, I'll try that out and see if I can get it to work with React Native.

**Comment by Jonovono** [comment]
@ndbroadbent did you have any luck?

**Comment by lukebrandonfarrell** [comment]
@jarredwitt @ndbroadbent @HazAT @Jonovono Did any of you guys figure out a solution to this?

**Comment by jarredwitt** [comment]
@lukebrandonfarrell one of the better examples I've seen and used is here: https://github.com/mattermost/mattermost-mobile/blob/master/app/utils/sentry/middleware.js.

**Comment by cihati** [comment]
See https://medium.com/localz-engineering/track-errors-using-sentry-with-react-native-ba5d145ca1e6
