### ISSUE TITLE
Redux / Extra Support

### ISSUE THREAD

**Issue by masiamj** [getsentry/react-native-sentry#12]
First off, great work to put this together. Thanks.

I have two questions, is the "extra" key supported as an option in "captureMessage"? I have tried several times to send additional data, with no luck.

Also is there anything in the roadmap about adding support for Redux? There are several integrations with vanilla raven-js that automatically report the current redux state upon an error (https://github.com/ngokevin/redux-raven-middleware, https://www.npmjs.com/package/raven-for-redux).

Thanks!

**Comment by HazAT** [comment]
Hey

You can use:
```
Sentry.setExtraContext({
  "a_thing": 3,
  "some_things": {"green": "red"},
  "foobar": ["a", "b", "c"],
  "react": true,
  "float": 2.43
});
```
This sets "global" extras .... that's what we have now ...

And in regards to Redux support, we will surely add it at some point in the future.
Our main focus right now is stabilizing and simplify the setup process.

**Comment by brunolemos** [comment]
`Raven.captureBreadcrumb` was great for that.
