### ISSUE TITLE
Crash Simulation

### ISSUE THREAD

**Issue by andypmw** [getsentry/react-native-sentry#120]
Hi there!

My company moving from Crashlytics to Sentry for our React Native App.

I have successfully add the Sentry for React Native. But how I can sure it installed correctly?

Do you have any code to call, to simulate a crash?

Crashlytics have this sample function to call to make a crash event:

[React Native Fabric](https://github.com/corymsmith/react-native-fabric)

```
// Forces a native crash for testing
Crashlytics.crash();
```

**Comment by HazAT** [comment]
There is also a function called `Sentry.nativeCrash()`
https://docs.sentry.io/clients/react-native/config/
That will trigger a crash in the native code.
If you want to try catching a JS exception, just throw a `new Error('something')`
