### ISSUE TITLE
no JS stacktrace in dev?

### ISSUE THREAD

**Issue by vafada** [getsentry/react-native-sentry#121]
When an error is logged in Sentry dashboard. We don't get to see the JS stacktrace. See example:
<img width="640" alt="screen shot 2017-06-26 at 8 51 24 pm" src="https://user-images.githubusercontent.com/285941/27566164-51b16f84-5ab1-11e7-8d0a-d34d01888708.png">

It looks like the source maps aren't getting uploaded.

The `Bundle React Native code and images` is updated and enabled:

<img width="669" alt="screen shot 2017-06-26 at 8 58 02 pm" src="https://user-images.githubusercontent.com/285941/27566288-54504d9a-5ab2-11e7-9ed1-d3b4e22498dc.png">

The `Upload Debug Symbols to Sentry` build phases is enabled:

<img width="703" alt="screen shot 2017-06-26 at 8 53 31 pm" src="https://user-images.githubusercontent.com/285941/27566196-88f9ca4a-5ab1-11e7-9bad-d040d7f041e2.png">

And I see the iOS debug symbol upload success everytime i build using xcode.

Based on this doc: https://github.com/getsentry/react-native-sentry/blob/master/docs/sourcemaps.rst

The source maps should be automatically generated (and uploaded?)

Am I missing something?

**Comment by vafada** [comment]
Is this the reason the sourcemaps isnt getting uploaded? 

<img width="382" alt="screen shot 2017-06-26 at 9 02 38 pm" src="https://user-images.githubusercontent.com/285941/27566366-dd9411a4-5ab2-11e7-8281-40f9c573ea87.png">

**Comment by HazAT** [comment]
@vafada That message is from `react-native`. 
We disabled the sourcemap upload by default for simulator builds. The generated script is always changing and we figured it does not make much sense always uploading it.
But you can enable it if you want, it's a bit hidden in the documentation but if you pass `–allow-fetch`.

`../node_modules/sentry-cli-binary/bin/sentry-cli react-native-xcode --allow-fetch ../node_modules/react-native/packager/react-native-xcode.sh`
