### ISSUE TITLE
Dashboard showing react stacktrace

### ISSUE THREAD

**Issue by vafada** [getsentry/react-native-sentry#124]
Why is the Sentry dashboard showing React's stacktrace?

![image](https://user-images.githubusercontent.com/285941/27613055-7626ce5c-5b67-11e7-9cc5-d1fcdae57e5e.png)

This is our method to force an error:

```
handleThrowError() {
   console.log('Throw Error');
   throw new Error('force throw error');
};
...
<Action action={this.handleThrowError} />
```

`Action` is our component which wraps React's `Touchable` UI.

How do we fix this to our our code's stacktrace instead of React Native Library Code?

**Comment by HazAT** [comment]
I've looked into this and the issue lies in Sentry itself.
I justed wanted to inform you that we are looking at it.

**Comment by HazAT** [comment]
Can you please upgrade to the latest version `0.14.2` and try again. 
This should be fixed, at least on our side.
There still seems to be an issue with sourcemap generation and react-native itself.
facebook/react-native#6946

**Comment by HazAT** [comment]
Hey, sorry for the long wait.
Please upgrade to `0.14.16` this should fix the issue.
