### ISSUE TITLE
iOS: Why is IPHONEOS_DEPLOYMENT_TARGET = 9.1 required in v0.14.0?

### ISSUE THREAD

**Issue by heracek** [getsentry/react-native-sentry#127]
React Native apps requires only deployment target 8.0 by default.
But `react-native-sentry` is build with iOS Deployment Target set to 9.1, se we are forced to change deployment target in our project.

Is it possible to create build of this package for 8.0?

**Comment by HazAT** [comment]
I've just checked it and the deployment target for RNSentry is `7.0`.
You can change it to `8.0` without any problems.

**Comment by mitsuhiko** [comment]
@HazAT we should make sure that the default in the release builds are set to 7.0.

**Comment by HazAT** [comment]
I will close this for now, `react-native` has a support for iOS >= 8.0
> Supported operating systems are >= Android 4.1 (API 16) and >= iOS 8.0.

A while ago our library was miss configured to use 9.1 this is long fixed now.
If you are still having issues with it feel free to reopen it.
