### ISSUE TITLE
Android: failed to assembleRelease

### ISSUE THREAD

**Issue by petromoldovan** [getsentry/react-native-sentry#128]
@HazAT thanks a lot for the SDK! 

Works great for me except for assembling a release apk for android. I saw similar issues that were closed with reference to 0.12.5 version of the SDK. 

I am on 
```
"react-native-sentry": "0.14.0",
"react-native": "0.44.0"
```

the following issue occurs:
![screen shot 2017-06-29 at 4 56 11 pm](https://user-images.githubusercontent.com/15109844/27694469-70b2f398-5cec-11e7-94ea-d2a9eb717194.png)

before posting the issue I tried linking, relinking, reinstalling, creating a fresh project etc. I cannot find the way to generate apk. 

Could you please check it out?

**Comment by HazAT** [comment]
You get a `403` which seems that something with your `sentry.properties` file isn't right.
Please check that you use the correct `authtoken` and have the correct `org` and `project` in your file.

**Comment by petromoldovan** [comment]
@HazAT thanks for the fast answer! I tried all possible options already. other guys seem to have the same problem:
https://github.com/getsentry/react-native-sentry/issues/63

does it work for you? can you actually assemble a release apk?

**Comment by HazAT** [comment]
Yeah, it works here. 
Do you have a `sentry.properties` file?

**Comment by petromoldovan** [comment]
@HazAT yes!

```
defaults.url=https://sentry.io/org/garden
defaults.org=org
defaults.project=garden
auth.token=mytoken
```

I even tried exporting the SENTRY_DSN link before I would assemble release. Still no luck

**Comment by HazAT** [comment]
I am not sure if it makes any difference, but can you change
`defaults.url=https://sentry.io/org/garden`
to
`defaults.url=https://sentry.io/`

**Comment by petromoldovan** [comment]
@HazAT it worked!!! unbelievable! many thanks for the awesome work and support!
