### ISSUE TITLE
error: Is a directory (os error 21) Pods

### ISSUE THREAD

**Issue by jinxac** [getsentry/react-native-sentry#129]
I was trying following command to upload source map from cli.

`node_modules/sentry-cli-binary/bin/sentry-cli releases files <release-name> upload-sourcemaps --dist 1 --strip-prefix . --rewrite .`

I am using few packages with pods and I get following error after running above command:-

`> ~/node_modules/react-native/node_modules/core-js/library/modules/es7.reflect.has-> ~/node_modules/react-native/node_modules/core-js/library/modules/es7.reflect.has-> ~/node_modules/react-native/Libraries/Renderer/src/renderers/shared/hooks/ReactHo> ~/node_modules/react-native/Libraries/Renderer/src/renderers/shared/hooks/ReactHo> ~/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/reconci> ~/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/reconci> ~/node_modules/react-native/local-cli/server/middleware/heapCapture/src/heapCaptu> ~/node_modules/react-native/local-cli/server/middleware/heapCapture/src/heapCaptu> ~/ios/Pods/Intercom/Intercom/Intercom.framework/Versions/A/Resources/Intercom.bunerror: Is a directory (os error 21)`

Can someone please help?

**Comment by HazAT** [comment]
This error seems odd, also you usually shouldn't have to run this command by yourself.
This should be in the run script in Xcode itself.

**Comment by HazAT** [comment]
I will close this issue for now, If you are still having this problem, please comment again.
