### ISSUE TITLE
React Native CLI build error: KSCrash

### ISSUE THREAD

**Issue by jonathanpeterwu** [getsentry/react-native-sentry#13]
Ran into an error building react-native-sentry using the react-native cli.

On running `react-native run-ios` the build error is

KSCrash which seems to be a dependency of sentry cannot be dynamic loaded as a library.

Can anyone point me in the right direction. 

![image](https://cloud.githubusercontent.com/assets/862695/24131916/e5ecd6fc-0dc7-11e7-9ee0-7ae396386822.png)

Error referenced when building w/ xcode
![image](https://cloud.githubusercontent.com/assets/862695/24132198/06050598-0dca-11e7-98ff-f52acfab3299.png)

**Comment by HazAT** [comment]
Did you check that you did everything described here ...
https://docs.sentry.io/clients/react-native/

**Comment by bulkyracehorse512** [comment]
@HazAT seeing the same issue. `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` set to `YES` and project and build folders have been cleaned

**Comment by bulkyracehorse512** [comment]
if i just run `cmd b` the build will be successful. but if i hit the run button for a specific device the build fails with 
![image](https://cloud.githubusercontent.com/assets/5141166/24157350/87c898b4-0e2f-11e7-8a06-6bed67bd797f.png)

![image](https://cloud.githubusercontent.com/assets/5141166/24157360/8daa5f9c-0e2f-11e7-9c64-c6258d39b1db.png)

**Comment by HazAT** [comment]
Can you double check if you changed this build step?
https://docs.sentry.io/clients/react-native/#xcode-build-steps

**Comment by bulkyracehorse512** [comment]
yeah bitcode is disabled and the build script is there.  still returning the dyld error

**Comment by HazAT** [comment]
@bulkyracehorse512 Last try ^^
https://github.com/getsentry/react-native-sentry/issues/11#event-1009361134

Will fix the `react-native run-ios` nevertheless though

**Comment by bulkyracehorse512** [comment]
@HazAT still seeing 
![image](https://cloud.githubusercontent.com/assets/5141166/24171347/7842abca-0e5a-11e7-81b9-5bf9373237be.png)

**Comment by bulkyracehorse512** [comment]
ok so now it runs through xcode run but not command line `react-native run-ios`
