### ISSUE TITLE
No source maps uploaded in dev and no events generated for iOS beta builds

### ISSUE THREAD

**Issue by jinxac** [getsentry/react-native-sentry#130]
I tried following the steps mentioned in [https://docs.sentry.io/clients/react-native/](url). Integration worked fine.

I tried creating throwing an error using:-

```
  setTimeout(function () {
      throw new Error('We crashed!!!!!');
  }, 10);
```

On **dev** this generates event and I can see them on sentry dashboard but source maps are not uploaded in dev mode according to [https://github.com/getsentry/react-native-sentry/issues/121](url) . So I tried adding `--allow-fetch ` but that also does not work. 

On **release(beta builds)** though source maps are uploaded but I cannot see any events being fired on sentry dashboard.

I tried creating a release build on my local and in console I am seeing following:-

```
Sentry Started -- Version: 3.1.2
    ************************ Crash Handler Notice ************************
    *     App is running in a debugger. Masking out unsafe monitors.     *
    * This means that most crashes WILL NOT BE RECORDED while debugging! *
    **********************************************************************
2017-06-29 23:40:05.779 [error][tid:com.facebook.react.JavaScript] We crashed!!!!!
2017-06-29 23:40:05.780715 wlv1[2404:803225] We crashed!!!!!
2017-06-29 23:40:05.783 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: We crashed!!!!!
2017-06-29 23:40:05.783019 wlv1[2404:803215] Unhandled JS Exception: We crashed!!!!!
2017-06-29 23:40:05.928283 wlv1[2404:803215] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: We crashed!!!!!', reason: 'Unhandled JS Exception: We crashed!!!!!, stack:
<unknown>@365:232
callTimer@32:601
callTimers@32:1002
value@30:2603
<unknown>@30:838
<unknown>@30:106
value@30:810
```

Can some please help me on this?

**Comment by HazAT** [comment]
In dev, the app does not crash if there is a JS error. 
In release it does (expected behavior).
If you crash on startup after 10ms, there is no time for Sentry to actually send the crash to the server. It will however store them and send them whenever it can.
