### ISSUE TITLE
Crash on iOS 8

### ISSUE THREAD

**Issue by yosimasu** [getsentry/react-native-sentry#131]
Hi @HazAT ,

Environment:

iOS: 8.1
react-native: 0.42.3
react-native-sentry: 0.13.0

iOS: 8.1
react-native: 0.42.3
react-native-sentry: 0.14.0

I have tried above environments. Still not work, crash on startup...

[#114](https://github.com/getsentry/react-native-sentry/issues/114)

**Comment by HazAT** [comment]
Ok, I was able to reproduce the crash. I get the following error:
```
dyld: lazy symbol binding failed: Symbol not found: _objc_unsafeClaimAutoreleasedReturnValue
  Referenced from: /Users/haza/Library/Developer/CoreSimulator/Devices/5BEE3DA5-B1E6-4306-A81D-72FB503A7B07/data/Containers/Bundle/Application/6C105581-B29D-404F-9DCF-619EC035DBF6/AwesomeProject.app/AwesomeProject
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libobjc.A.dylib
```

the line responsible for the is `[SentryClient.sharedClient.breadcrumbs addBreadcrumb:crumb];`
I have no idea why yet. If it help you could uncomment this line and continue until I found out whats actually going on.

**Comment by yosimasu** [comment]
Hi @HazAT ,

According to [the topic on stackoverflow](https://stackoverflow.com/questions/39486064/xcode-8-ios-8-simulator-with-crash-dyld-lazy-symbol-binding-failed-symbol-n), I have changed the deployment target of `SentryStatic` to `iOS 8.0`.

It works.

![2017-07-05 16 48 29](https://user-images.githubusercontent.com/716511/27857009-a2891cac-61a2-11e7-8640-fd62778fc755.png)

![2017-07-05 16 48 52](https://user-images.githubusercontent.com/716511/27857020-af249662-61a2-11e7-8474-7e96963c887e.png)
