### ISSUE TITLE
Source code not found for debuggerWorker.js and index.ios.bundle

### ISSUE THREAD

**Issue by braco** [getsentry/react-native-sentry#134]
Getting this in web console with default install on RN

```
There were 2 errors encountered while processing this event
Source code was not found for app:///debuggerWorker.js Collapse
{
  "url": "app:///debuggerWorker.js"
}
Source code was not found for app:///index.ios.bundle Collapse
{
  "url": "app:///index.ios.bundle"
}
```

**Comment by HazAT** [comment]
Are you running it on the simulator? 
Because this issue indicates that no source maps have been uploaded.
https://docs.sentry.io/clients/react-native/manual-setup/#build-steps

**Comment by HazAT** [comment]
I will close this issue now since the link to the docs should solve the problem.
If you are still having troubles, feel free to reopen it.
