### ISSUE TITLE
wanted: do not upload sourcemaps on release build for test environment.

### ISSUE THREAD

**Issue by awitherow** [getsentry/react-native-sentry#140]
Hello!

I am running e2e testing using Appium within my project.

During our test process we have to create a new build of iOS or Android at release version.

During this phase we noticed that the `sentry-cli` builds and sends the sourcemaps.

This is only happening on our staging server at the moment, but it might be making redundant uploads/falsely tagged uploads.

Is it possible to add a flag somewhere in the deployment process that would be picked up and would disable sending the sourcemaps?

Example: 

```
export SENTRY_TEST_ENV=true

scripts/test.sh ... ...

```

and React-Native-Sentry would be aware of this variable?

Thanks!

**Comment by HazAT** [comment]
Would you consider setting the `environment` tag to e.g.: `staging` and use the `setDist` function to separate builds on Sentry.
Every `dist` (Distribution) will have its own source map files.

I am pretty sure we will not add this specific feature because you could check in the run script phase or gradle build step for the current environment and just don't call `sentry-cli`.

Would the solution with distributions work for you?

**Comment by awitherow** [comment]
Yeah this sounds more reasonable, I was unaware that is why I requested something.

I will work that into our workflow, thank you.

**Comment by awitherow** [comment]
@HazAT just a quick follow up... my intention is to NOT upload any sourcemaps or files to sentry during this test, but am unsure how I could setDist to NONE... I need to cancel the sentry-cli thing in general.

**Comment by HazAT** [comment]
I see, but since `sentry-cli` will be called in the run script phase, it should be possible to not call it for specific build types. I thought it would make sense to also get the correct stacktraces on the staging env.

**Comment by awitherow** [comment]
You do make a good point! Thanks for the insights and letting me bounce this off of you. I am satisfied with this paradigm 👍

**Comment by kunall17** [comment]
@HazAT I'm also facing a similar problem where I'm using detox for e2e tests, I need to disable the sentry as the key is not public and the project is an open source
```
Jul 27 11:30:20 asd ZulipMobile[27355]: Sentry Started -- Version: 3.1.3
Jul 27 11:30:20 asd ZulipMobile[27355]: Sentry - Error:: Project ID path component of DSN is missing
Jul 27 11:30:20 asd ZulipMobile[27355]: *** Terminating app due to uncaught exception 'SentryReactNative', reason: 'Project ID path component of DSN is missing'
	*** First throw call stack:
```

I used some scripts in the bundle phase, where the the sentry was being bundled
```
if [[ $SDKROOT == *"iPhoneSimulator10"* ]]; then
    export NODE_BINARY=node\n../node_modules/react-native/scripts/react-native-xcode.sh
else
export SENTRY_PROPERTIES=sentry.properties
export NODE_BINARY=node
../node_modules/sentry-cli-binary/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh
fi
```
I also disabled it in the AppDelegate  (this line `[RNSentry installWithRootView:rootView];`  )

It will be fine (for now) if the sentry is bundled with the App, but how can I disable the auto start of the sentry on the native side, as I don't want to include the key?

**Comment by HazAT** [comment]
@kunall17 I would disable it in javascript with something like
```
if (__DEV__) { // Check for env here
    Sentry.config({}).install();
}
```

**Comment by kunall17** [comment]
@HazAT The above stacktrace 
```
Jul 27 11:30:20 asd ZulipMobile[27355]: Sentry Started -- Version: 3.1.3
Jul 27 11:30:20 asd ZulipMobile[27355]: Sentry - Error:: Project ID path component of DSN is missing
Jul 27 11:30:20 asd ZulipMobile[27355]: *** Terminating app due to uncaught exception 'SentryReactNative', reason: 'Project ID path component of DSN is missing'
	*** First throw call stack:
```

is for the start of the application, and I'm already not calling the Sentry.config in the js side! 
Apologies, I forgot to mention this above! 

Any other way I can prevent the sentry initialization?

**Comment by kunall17** [comment]
Ok there was some problem with the packager, @HazAT is there any way I can avoid this error message
`error: http error: Invalid token (401)` for `auth.token=ADD-DSN-HERE`

**Comment by HazAT** [comment]
@kunall17 Just to clear things up: `auth.token=ADD-DSN-HERE` you don't need the DSN here you need an auth token, created in the Sentry Backend https://sentry.io/api/

And if you don't want to upload anything, just don't provide the properties in the Sentry.properties file.

**Comment by kunall17** [comment]
Thanks @HazAT for your help, got it working :) 

If someone wants to take help in this problem they can view this PR https://github.com/zulip/zulip-mobile/pull/940
