### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode error

### ISSUE THREAD

**Issue by tokict** [getsentry/react-native-sentry#144]
Hi, I am trying to link the files using react-native link ant this error pops up. How can I get rid of it?

/node_modules/react-native-sentry/scripts/postlink:17
let cachedDsn = null;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by HonzaHK** [comment]
Hello,
i resolved this error by upgrading nodejs to newer version. You can check yours by typing "node -v" in terminal. On Ubuntu, apt-get installs v4.x by default.
Check this answer to get newer versions: https://askubuntu.com/a/850947

Good luck

**Comment by tokict** [comment]
Thanks mate, just what I needed. My default node version in repo was v4.
