### ISSUE TITLE
Breadcrumbs are not working in android

### ISSUE THREAD

**Issue by denstepa** [getsentry/react-native-sentry#145]
Hi there,
we've faced an issue that breadcrumbs are not shown in sentry.
I've activated the logging to see what is actually getting sent to sentry.io, and they are present there, but in the project interface they are missing.
Example of what is send, and what is shown in sentry interface (json) by raven-js https://gist.github.com/denstepa/adef096b5611bd992046369172ef95eb
Same for react-native-sentry https://gist.github.com/denstepa/c7e7d3535267cacacf2c65d5a94e7390

The Breadcrumbs are send in both cases, but in second one they are not visible in the interface.. Is that smth to do with library configuration ? We have for now to migrate back to raven-js as this feature is really important for us.

**Comment by HazAT** [comment]
Can you try and not run it through the remote debugger?

**Comment by HazAT** [comment]
Can you please upgrade to `0.14.8`, this should be resolved now.
