### ISSUE TITLE
Production app size

### ISSUE THREAD

**Issue by zifeo** [getsentry/react-native-sentry#149]
We are happy to see Sentry embracing React Native and providing a tailored solution for it. However after having setup everything the final iOS app size was increased by more than 30Mo (could be some Swift libraries) compared to using Raven-js. What are you plan about this? 30Mo is definitely a no-go for us and for all end customers.

**Comment by HazAT** [comment]
Hmm, that's strange.
With version `v0.11.0` we switched from our Swift client to Obj-C which shouldn't add that much to the app size.
Make sure that you use the latest version and do not bundle the Swift runtime.

**Comment by zifeo** [comment]
Thanks for getting back. Indeed since this version the app only increases of 1.7MB, great job!
