### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by oblador** [getsentry/react-native-sentry#15]
Hey guys, 

Awesome release! Just a question, any plans on supporting CocoaPods?

**Comment by HazAT** [comment]
Of course, shouldn't be that big of a deal ... already started a PR but there is still an issue I need to fix.
See PR:
https://github.com/getsentry/react-native-sentry/pull/16

**Comment by HazAT** [comment]
Added with `0.5.0` ... Thx @oblador 🤜 🤛
