### ISSUE TITLE
error: Invalid JSON data: Data too long

### ISSUE THREAD

**Issue by braco** [getsentry/react-native-sentry#150]
I'm getting hard app crashes with an error seemingly reported by the ios/KSCrash package. I'm still trying to hunt down the origin, or what data exactly is too long, but this error is pretty opaque.

It would be better to truncate the data with a warning, if anything. Should I file this as a request somewhere?

**Comment by HazAT** [comment]
Hey,
Please upgrade to the latest version, the problem should be fixed there.
https://github.com/getsentry/react-native-sentry/releases/tag/v0.14.6
