### ISSUE TITLE
user context is not showing up for iOS

### ISSUE THREAD

**Issue by willlaserlike** [getsentry/react-native-sentry#154]
I have Sentry.setUserContext({...}) in my code but when I cannot see the userID or username in my console. The only information it has is the IP address. I'm pretty sure the Sentry.setUserContext line is executed before the crash, since it crashes at that line if I don't pass in userID. 

But the same build works on Android. Any suggestions on what I missed here? Thanks!

**Comment by HazAT** [comment]
Please make sure to write `userId`, this should fix your issue.

**Comment by willlaserlike** [comment]
@HazAT  well, I did write userID. Are you saying I should try write userId instead of userID?  It gives me an exception if I don't do userID, as people mentioned in this issue. 
https://github.com/getsentry/react-native-sentry/issues/98

**Comment by HazAT** [comment]
Also please upgrade to the latest version `0.14.10`

**Comment by HazAT** [comment]
I've recently release `0.15.0` which tests this behavior. Please upgrade and report back if you are still having this issue.
