### ISSUE TITLE
Documentation requested

### ISSUE THREAD

**Issue by braco** [getsentry/react-native-sentry#155]
- How do one remove the automatic binding to console events?
- How does one disable automatic binding to error events?
- How does one disable reporting in emulator?

**Comment by HazAT** [comment]
Hey, you can actually pass all available options that raven-js provides.
https://docs.sentry.io/clients/javascript/config/
This is how you can disable binding console event.
```
autoBreadcrumbs: {
    'xhr': false,      // XMLHttpRequest
    'console': false,  // console logging
    'dom': true,       // DOM interactions, i.e. clicks/typing
    'location': false  // url changes, including pushState/popState
}
```
> How does one disable automatic binding to error events?

I am not really sure what you mean there.

> How does one disable reporting in emulator?

You can actually just not call `.install()` this should do the trick.

**Comment by braco** [comment]
Thanks, will check these out.
 
> > How does one disable reporting in emulator?
> You can actually just not call .install() this should do the trick.

This doesn't work, as after require, Sentry will randomly throw `Cannot read property 'logLevel' of undefined` because of this line:

```
  static _log(...args) {
    if (Sentry.options.logLevel >= 2) {
      console.log.apply(null, args);
    }
  }
```
https://github.com/getsentry/react-native-sentry/blob/master/lib/Sentry.js#L61

I believe the only thing being called is the original require, no config() or install().

**Comment by HazAT** [comment]
I don't understand if you just run 
`Sentry.config("your dsn");` without the `.install()`
this should work fine. The options will be initialized there.

**Comment by albinekb** [comment]
I came here because I got the same error `Cannot read property 'logLevel' of undefined`, I was trying to set user context without having called Sentry.config, I think the lib should throw an error that it needs to be set up with `.config` before calling the other methods. Thoughts?

**Comment by HazAT** [comment]
@albinekb have you tried this
```
import {
  Sentry,
  SentrySeverity,
  SentryLog
} from 'react-native-sentry';
```

**Comment by albinekb** [comment]
No, are you suggesting that the bundler is excluding important files for `react-native-sentry`, and those get imported by calling  `Sentry.config()`?

Because I fixed my problem by changing my code to always run `Sentry.config` (even for local dev builds) and that made it not throw the error.

That's why I'm suggesting that the lib should throw an error if you try to use setUserContext without having called `Sentry.config` first?

**Comment by HazAT** [comment]
Oh, that's what you meant, sorry, got it.
Actually, that would mean a lot of internal code changes, I will think about an elegant solution for that thanks for pointing this out.
