### ISSUE TITLE
Support sentry.properties per Android buildType/flavor

### ISSUE THREAD

**Issue by AndrewJack** [getsentry/react-native-sentry#157]
Any chance of adding the ability to specify a sentry.properties file per buildType/Flavor like the `sentry-android-gradle-plugin`?

https://github.com/getsentry/sentry-java/issues/437
https://github.com/getsentry/sentry-java/pull/440

Thanks 

cc @bretthoerner

**Comment by AndrewJack** [comment]
Or which may be more useful with react-native. check if the environment variable `SENTRY_PROPERTIES` has been set?

**Comment by mitsuhiko** [comment]
@AndrewJack Yeah, this came up before. I will have a look at adding this. I suppose you primarily want to change the project?

**Comment by AndrewJack** [comment]
Yes, just making the `sentry.gradle` file aware of existing environment variables and skipping a few steps.

**Comment by HazAT** [comment]
I've just released a `0.22.0` which should be able to achieve what you want.
You have to add:
```
project.ext.sentry = [
    flavorAware: true
]
```
before
`apply from: "../../node_modules/react-native-sentry/sentry.gradle"`

This adds the flavor name to the sentry properties file see: https://github.com/getsentry/react-native-sentry/pull/212

**Comment by bimusiek** [comment]
For future generations finding this issue, proper naming is:

`sentry-prod-release.properties` for `prod` flavor
`sentry-rc-release.properties` for `rc` flavor 
etc.

**Comment by fabiendem** [comment]
https://github.com/getsentry/sentry-react-native/issues/157#issuecomment-816856009

Is that still the case?
Documentation suggests to use `cameCase`

**Comment by krystofwoldrich** [comment]
@fabiendem Yes, it's the case.
