### ISSUE TITLE
Sentry is delaying react-navigation transition

### ISSUE THREAD

**Issue by buesing** [getsentry/react-native-sentry#158]
I was investigating https://github.com/react-community/react-navigation/issues/608 and it looks like Sentry takes very long to parse an error during a transition. On a physical iPhone 6, it was delaying a transition by over 3 seconds. I found this by profiling with Instruments on macOS. Here's a screenshot of the stacktrace, where you can see that Sentry calls are blocking the transition for a long time. Removing Sentry from the app fixes the problem. I tried upgrading to the latest version, problem persists. Let me know if I can help with further details.

![bildschirmfoto 2017-07-19 um 16 50 39](https://user-images.githubusercontent.com/1181371/28373531-dcd35b10-6ca2-11e7-8e91-5e7ae2c1d7eb.jpg)

**Comment by HazAT** [comment]
Hey, thx for reporting this.
For now you can just disable the stacktrace merging which should resolve the performance issue.
`deactivateStacktraceMerging: true`
https://docs.sentry.io/clients/react-native/config/
We are currently looking into improving the performance so this does not happen at all.

**Comment by jordanmkoncz** [comment]
I was having the same issue with react-navigation where I was experiencing a 1-2 second delay before transitioning to a new screen. After deactivating the stacktrace merging functionality in Sentry, the issue appears to be fixed.

**Comment by titonton** [comment]
Where exactly is Sentry I don't seem to have it in my project

**Comment by huhuanming** [comment]
I was having the same issue with react-navigation and sentry.

**Comment by kesha-antonov** [comment]
Same here. App become slow when I add sentry !
What to do with this?

**Comment by huhuanming** [comment]
😳

**Comment by willlaserlike** [comment]
Same here. Hope a fix will be available soon. It slows down so much that almost make the app unusable.

**Comment by HazAT** [comment]
Hey @huhuanming @willlaserlike,
Do you still have troubles when deactivating stacktrace merging?

**Comment by willlaserlike** [comment]
@HazAT Deactivating stacktrace seems to fix it. But stacktrace merging is kind of the key reason I choose Sentry so I wanna have it back plz...

**Comment by HazAT** [comment]
@willlaserlike Are you running the latest version `0.20.0`
We've released some performance improvements in the last few releases, I am still trying to reproduce this.
In the meantime, you could maybe upgrade to the latest version and try it again.

**Comment by huhuanming** [comment]
thx.
I will be update and test it later.

**Comment by plasticine** [comment]
Can confirm the issue persists with the latest `react-native-sentry`
release. Fine in dev, slow transitions in release builds.

Disabling stack trace merging seems to continue to resolve the issue as a
temporary workaround for now.

**Comment by HazAT** [comment]
I've just released `0.22.0` which should fix the problem. Please try it out and tell me if it works.

**Comment by tommeier** [comment]
Hi @HazAT - Can confirm it has fixed the issue for us in deployed versions 🎉 thanks!
