### ISSUE TITLE
High CPU in iOS Simulator - only on iPhone 5

### ISSUE THREAD

**Issue by phillbaker** [getsentry/react-native-sentry#162]
Thanks for all the hard work on this. I don't think this is a dupe of other issues, but I sorry if I missed one.

When using the iOS simulator with an iPhone 5 device with iOS 10.3, the CPU is maxed out and the app is eventually killed with the following error printed to console:
```
app(45423,0xb043d000) malloc: *** mach_vm_map(size=1048576) failed (error code=3)
	*** error: can't allocate region securely
	*** set a breakpoint in malloc_error_break to debug
```

I've tried versions `0.12.12`, `0.14.8`, and `deactivateStacktraceMerging: true`. Commenting out the `Sentry.config().install()` does fix the CPU usage. Note that this doesn't appear on other simulator devices such as the iPhone 5s or iPhone 6.

Happy to provide more debugging info if it'd help.

**Comment by HazAT** [comment]
Hey, I'm trying to reproduce it but with no luck.
I am running this example project and have no issues as you can see:
https://github.com/getsentry/examples/tree/master/react-native

<img width="1261" alt="screenshot 2017-07-24 14 02 20" src="https://user-images.githubusercontent.com/363802/28522562-bf68b00a-7078-11e7-93e6-274cc7c9fbef.png">

**Comment by phillbaker** [comment]
@HazAT thanks for investigating, I'll try to get a reproducible test case, but at this point it's also possible that there was something else in the app causing this. I'll close for now and re-open if I can provide more detail.
