### ISSUE TITLE
Android fails to compile

### ISSUE THREAD

**Issue by JulioC** [getsentry/react-native-sentry#165]
After installing and linking react-native-sentry on my project, the Android version doesn't build anymore, with an error related to `io.sentry` package not being found.

After some time, I found that the sentry project is not being compiled, due to a missing entry on the `dependencies` of `android/app/build.gradle`. To fix this issue, I had to add this line:

```gradle
dependencies {
    // ...
    compile project(':react-native-sentry') // added this line
    compile "com.facebook.react:react-native:+" 
}
```

I'd like some to know if this issue is related to my project or it should be fixed in react-native-sentry.

My setup is:
* compileSdkVersion 25
* buildToolsVersion 25.0.1
* react-native: 0.46.4
* react-native-sentry: 0.14.8
* Windows 10

**Comment by HazAT** [comment]
Usually, if you run `react-native link react-native-sentry` this line should be added by react-native.
Did you run the link step?

**Comment by JulioC** [comment]
I did, but it doesn't look to be related to the react-native-sentry.

I had the same issue with another package. I believe it's some issue with the react-native cli.

Thanks for the help!
