### ISSUE TITLE
Does this work with a self-hosted Sentry?

### ISSUE THREAD

**Issue by alvaromb** [getsentry/react-native-sentry#17]
Or we should wait for a future release?

**Comment by mitsuhiko** [comment]
It does work with self hosted sentry however currently the general iOS story on self hosted sentry is not great because of the lack of system symbols. So YMMV.

**Comment by alvaromb** [comment]
So, what should we set in the build script in the following steps?

```sh
export SENTRY_ORG=YOUR_ORG_SLUG
export SENTRY_PROJECT=YOUR_PROJECT_SLUG
export SENTRY_AUTH_TOKEN=YOUR_AUTH_TOKEN
...
```

**Comment by mitsuhiko** [comment]
You set the values from the URLs for the slug and the auth token you get from your local sentry. Additionally you will need to export `SENTRY_API_URL` as mentioned in the docs. You can find a bit of information on these in the CLI docs: http://docs.sentry.io/learn/cli/

**Comment by alvaromb** [comment]
Cool, thanks @mitsuhiko.

We were missing the `SENTRY_URL` export.

**Comment by zhelyabuzhsky** [comment]
When I try to export `SENTRY_URL`, I get an error 

> error: http error: generic error (400)

What's wrong?

(Jenkins + Fastlane)

**Comment by mitsuhiko** [comment]
@zhelyabuzhsky i strongly recommend using forum.sentry.io for support. I can't tell you whats wrong like this though, you would need to enable debug output.
