### ISSUE TITLE
KSCrash/KSCrash.h not found when archiving

### ISSUE THREAD

**Issue by messense** [getsentry/react-native-sentry#175]
RN version 0.47
RNSentry version: 0.15.0

Debug build is ok, when archiving it fails.

![image](https://user-images.githubusercontent.com/1556054/28874473-8c4e4b64-77c4-11e7-94ff-1ba77045267e.png)

**Comment by HazAT** [comment]
Is this a new project or did you upgrade your existing project?
Also, did you change something in the Xcode settings?
It's working for me.

**Comment by messense** [comment]
An upgrade. Changed nothing.

发自我的 iPhone

**Comment by HazAT** [comment]
Hey, sorry for the inconvenience.
Please upgrade to `0.15.1` this is fixed now.

**Comment by messense** [comment]
Thanks!
