### ISSUE TITLE
Stacktrace merging not yet implemented

### ISSUE THREAD

**Issue by btoueg** [getsentry/react-native-sentry#177]
Hi,

I'm having this error in prod.

User says the app just won't launch. Is there anything I can do to get further info?

![image](https://user-images.githubusercontent.com/498190/28925653-c2229eb0-7865-11e7-840a-85294b21f370.png)

**Comment by HazAT** [comment]
Hey, the error of `Stacktrace merging not yet implemented` is just on android, stacktrace merging does not exist there yet.
Can you send me the link to the issue to daniel@sentry.io I want to check something?

**Comment by btoueg** [comment]
Here you go https://sentry.io/mobeye/mobeyereact/issues/293462309/

**Comment by HazAT** [comment]
Ok, so the actual error is 
`undefined is not a function (evaluating '(0,X.toggleFormType)()')`
And it also seems your version of react-native-sentry is pretty outdated, the new version should show you a proper JS error in Sentry.

**Comment by btoueg** [comment]
Depends on what you mean by "pretty outdated", is 0.14.0 pretty outdated ?

0.14.0 dates back to early July.

For an app in production, which requires a lot of quality assurance, I'm not sure I agree with you on that!

Other than this error, every other stack traces are unwrapped, so why this one in particular has not been deciphered?

**Comment by HazAT** [comment]
OK, sorry if that sounded a bit too drastic, I know the mobile eco system works a bit different and shipping updates is more work than on the web.
But I am pretty sure this user is running a version below `0.13` probably version `0.12.x` or react-native-sentry.
Can you advise the user to update the app? Since the newer version of your app also has to the newer version of `react-native-sentry`.

**Comment by HazAT** [comment]
I will close this for now if you need anything else just let me know.
Also starting from version `0.16.0` we've fixed the SDK information so we always know which version the user is running.


<img width="352" alt="screenshot 2017-08-10 16 50 46" src="https://user-images.githubusercontent.com/363802/29176457-3721f4aa-7dec-11e7-8213-a6400e993903.png">
