### ISSUE TITLE
Trying to upload dsyms for build that is already in the store

### ISSUE THREAD

**Issue by stancho-dynoden** [getsentry/react-native-sentry#180]
Hi friends,
I have an iOS app and using sentry for crash loggs. The app has bitcode disabled.
I have received a few crashes but they are not symbolicated and I am trying to upload the dsyms.
I have downloaded the required dsyms from xcode organiser for my build and used sentry-cli manual upload method:  

`sentry-cli --auth-token YOUR_AUTH_TOKEN upload-dsym --org YOUR_ORG_SLUG --project YOUR_PROJECT_SLUG PATH_TO_DSYMS`

The upload completes successfully but the crashes on sentry does not update or does not get symbolicated and the lines that are  with my AppName have unknown status. Am I wrong to expect that the crash logs will be updated after the upload and is my way of doing it wrong? Thank you for your time.

**Comment by HazAT** [comment]
Hey, 
Events that don't have valid symbols by the time they happen, will not have a useable stacktrace IF you don't have reprocessing active.
If you enable reprocessing in your projects settings, events will be on hold until you upload the necessary debug symbols.
You can find it under `Projects Settings / Processing Issues`
If you enable it, you can upload the symbols whenever you want.
In this case we recommend uploading the symbols while building your app see: 
https://docs.sentry.io/clients/react-native/manual-setup/#ios

**Comment by stancho-dynoden** [comment]
Thanks for the help! :)
