### ISSUE TITLE
Question: When will JS crash be reported to Sentry?

### ISSUE THREAD

**Issue by JAStanton** [getsentry/react-native-sentry#187]
If I have an uncaught JS exception it will crash my app. Will it be uploaded on next boot of the app? It seems to be in my tests the only way to get it to upload is if I have a native crash after my JS crash then on next boot it uploads both of them together. What's the correct behavior I should be expecting?

**Comment by HazAT** [comment]
So it works differently depending on if the native integration is available or not.

With native integration:
- Native Crash: will be sent after launch
- JS Error will be sent before crash

Just with raven-js:
- Native Crash: nothing
- JS Error will be sent after crash

This should be the behavior in `0.17.0` there was a bug before that not working correctly without the native integration.

**Comment by JAStanton** [comment]
Hey @HazAT thanks for being so responsive! The `With native integration` behavior is the same for both iOS and Android regarding when crashes are sent in `0.17`?

Thanks for the explanation, upgrading now :)

**Comment by HazAT** [comment]
Yeah, it should be the same on both iOS and Android.

**Comment by JAStanton** [comment]
@HazAT I am only seeing JS crashes being uploaded after native crashes on `1.17.1`
