### ISSUE TITLE
Freeze on JS crash

### ISSUE THREAD

**Issue by Amurmurmur** [getsentry/react-native-sentry#188]
Seems like after switching from raven-js to react-native-sentry, it stopped reporting crashes, but instead it just freezes the app entirely and no reports get sent to sentry, but sometimes they do to crashlytics.

Maybe crashlytics (I use react-native-fabric) is not needed anymore, since sentry handles both native and js now ?!

**Comment by HazAT** [comment]
Hey,
Yeah we handle js and native crashes on both iOS and Android.
How does your config look like, did you disable the native integration?

**Comment by Amurmurmur** [comment]
Hi @HazAT 
I've tried to disable native integration in the sentry's config but seems like it didnt change the behaviour at all.
App freezes for a very long time, but doesnt crash completely, more like hangs forever.
Here is my config
```
 Sentry.config('https://...@sentry.io/...', {
    deactivateStacktraceMerging: true,
    disableNativeIntegration: true
  }).install()

  Sentry.setTagsContext({
...
  })
```

**Comment by HazAT** [comment]
Which version of `react-native-sentry` are you running?

**Comment by Amurmurmur** [comment]
👍 👍 👍 👍 👍  Thank you very much 👍 👍 👍 👍 👍 

@HazAT Just upgraded to 0.17.0
Same config, problem solved.

👍 👍 👍 👍 👍  Thank you very much 👍 👍 👍 👍 👍
