### ISSUE TITLE
setRelease on JS doesn't set release on native

### ISSUE THREAD

**Issue by JAStanton** [getsentry/react-native-sentry#190]
_Platform:_
- [x]  iOS
- [ ]  Android

paranoid redacted `npm ls`:
```
@REDACTED@0.0.0
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.3
├── react-native@0.44.3
├── react-native-code-push@2.1.1-beta
├── react-native-sentry@0.17.0
```

Config:

```
Sentry.config(__CONFIG__.sentry.dsn, {
  deactivateStacktraceMerging: false, 
  logLevel: SentryLog.Verbose, 
  disableNativeIntegration: false, 
  ignoreModulesExclude: [], 
  ignoreModulesInclude: ["RNSentry"], 
}).install();
```

---
I am using a custom release name for JS and native. I've got it all wired up and it's working great (I upload source maps from my own script not through xcode or android build process). When app boots I run `Sentry.setRelease` after my `.install()`. However when iOS native crashes are being reported I am getting the default release name `my.app.identifier@1.10.0`. Is there any way to persist the release name changes on native? I'm pretty sure it's just uploading before running the JS code that changes release name.

**Comment by HazAT** [comment]
I will check this right now.

**Comment by HazAT** [comment]
OK, so I tried it.

Start App -> Set Release -> Native Crash (by calling `Sentry.nativeCrash();`)-> Restart App -> Crash will be sent with Release I set before

What is really strange it was working every other time, so it must be a threading issue.
I've noticed that if I wait a few seconds after I set the release and then crash it works if I set the release and immediately crash afterward, it doesn't work (it sometimes does work).

I also found another issue in `sentry-cocoa` where it will not work when you call `reportUserException` multiple times (which isn't called from react native at all).

I am still trying to figure out where I have the race condition, just so I know, were you doing the same, trying out a crash? 
OR 
Did that happen in the wild?

**Comment by JAStanton** [comment]
Yeah it was a debug option in my app I was pressing that causes a JS crash, then I triggered another that caused a native crash.

I forgot if I was in debug mode which just shows a red screen I can dismiss and keep using the app or if it was a production environment that actually crashes the app. I think it was in a production environment.

**Comment by HazAT** [comment]
@JAStanton Can you please upgrade to `0.17.1` 
This should be fixed there.

**Comment by JAStanton** [comment]
sure, let me give it a try
