### ISSUE TITLE
Build Failing for assembleRelease: Invalid api key

### ISSUE THREAD

**Issue by SeunLanLege** [getsentry/react-native-sentry#195]
Trying to `assembleRelease` without luck.

```bash
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
error: http error: Invalid api key (401)
:app:bundleReleaseJsAndAssets FAILED
```

**Comment by SeunLanLege** [comment]
```toml
defaults.url=https://sentry.io/api/ID/csp-report/?sentry_key=KEY (gotten from client keys.CSP endpoint)
defaults.org=c2g-consulting
defaults.project=td-mobilesfa
auth.token=[permissions = project:releases]
cli.executable=/home/seunlanlege/Projects/td-mobile/sfa/node_modules/sentry-cli-binary/bin/sentry-cli
``

**Comment by SeunLanLege** [comment]
@HazAT

**Comment by HazAT** [comment]
Hey, please make sure your defaults url looks like this
`defaults.url=https://sentry.io/`

**Comment by SeunLanLege** [comment]
Works, thanks. Should probably put that in a documentation :thinking_face:

**Comment by HazAT** [comment]
@SeunLanLege Just so we can improve the flow, do you remember why you pasted 
`defaults.url=https://sentry.io/api/ID/csp-report/?sentry_key=KEY (gotten from client keys.CSP endpoint)`
did the docs direct you there?

**Comment by SeunLanLege** [comment]
Actually I configured it with that when I ran the link command. It asked for endpoint so I hopped over to client keys and copied the endpoint.

**Comment by mitsuhiko** [comment]
@daniel we should probably add a hint that the default in link is correct unless you use self hosted sentry
