### ISSUE TITLE
Can sentry.properties cli.executable be relative instead of absolute?

### ISSUE THREAD

**Issue by fforres** [getsentry/react-native-sentry#196]
_Platform:_
- [x]  iOS
- [x]  Android

---
I have following issue:
I have correctly installed and configured sentry's react-native client, but i'm facing a different issue. 

In both ios and android `sentry.properties` file, the current cli path is absolute.
```
cli.executable=/Users/fforrres/Github/AxiomZen/PROJECT_NAME/node_modules/sentry-cli-binary/bin/sentry-cli
```

Is there a way I can make it relative to the current file path?

**Comment by SeunLanLege** [comment]
you could install sentry cli globally and replace the absolute path with just `sentry-cli` since it's now a global command.

**Comment by HazAT** [comment]
@fforres 
You should be able to change it to 
`cli.executable=../node_modules/sentry-cli-binary/bin/sentry-cli`

**Comment by fforres** [comment]
Thank you both

In the end i ended up using 
`cli.executable=../node_modules/sentry-cli-binary/bin/sentry-cli`


Although @HazAT... if you remove it altogether it does have a fallback right?

**Comment by HazAT** [comment]
It should work if it's installed globally, I will try to change it back so the path is relative again.

**Comment by qqhann** [comment]
Our team has both Mac and Windows users, and the `cli.executable` for Windows uses backslash, which makes it incompatible with Mac users. I hope this can be improved.
