### ISSUE TITLE
JS only reports crash on next boot after native crash

### ISSUE THREAD

**Issue by JAStanton** [getsentry/react-native-sentry#198]
_Platform:_
- [x]  iOS
- [ ]  Android

paranoid redacted `npm ls`:
```
@REDACTED@0.0.0
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.3
├── react-native@0.44.3
├── react-native-code-push@2.1.1-beta
├── react-native-sentry@0.17.1
```

Config:

```
Sentry.config(__CONFIG__.sentry.dsn, {
  deactivateStacktraceMerging: false, 
  logLevel: SentryLog.Verbose, 
  disableNativeIntegration: false, 
  ignoreModulesExclude: [], 
  ignoreModulesInclude: ["RNSentry"], 
}).install();
```

As mentioned here: https://github.com/getsentry/react-native-sentry/issues/187#issuecomment-322896741  I am only seeing JS crashes being uploaded after native crashes on `1.17.1` on iOS. This is with `disableNativeIntegration: false`. 

How to reproduce:
- boot app with xcode in simulator
- close xcode because debugger mode nothing will report
- open app, cause JS crash
- re-open app
- check sentry web app
- expected: a JS bug to be reported
- actual: no bugs reported
- re-open app
- cause native crash
- re-open app
- expected: Native crash in sentry web app
- actual: sentry web app has both JS and native crash.

**Comment by JAStanton** [comment]
update: I'm using CocoaPods to install sentry. This is the the podfile.lock
```
  - Sentry (3.4.2):
    - Sentry/Core (= 3.4.2)
  - Sentry/Core (3.4.2)
  - Sentry/KSCrash (3.4.2):
    - KSCrash/Core (~> 1.15.11)
  - SentryReactNative (0.17.1):
    - React
    - Sentry (~> 3.4.2)
    - Sentry/KSCrash (~> 3.4.2)
```

**Comment by JAStanton** [comment]
I downgraded to `1.70.0` and I'm seeing this as well:
```
- Sentry (3.4.2):
  - Sentry/Core (= 3.4.2)
- Sentry/Core (3.4.2)
- Sentry/KSCrash (3.4.2):
  - KSCrash/Core (~> 1.15.11)
- SentryReactNative (0.17.0):
  - React
  - Sentry (~> 3.4.2)
  - Sentry/KSCrash (~> 3.4.2)
```

**Comment by JAStanton** [comment]
Also something I've notice is that you've bumped `Bump sentry-cocoa to 3.4.3` but podspec wasn't updated? Is this where the fix is?

**Comment by JAStanton** [comment]
hmmm manually bumped to `3.4.3` via forking, but that didn't seem to do the trick

**Comment by JAStanton** [comment]
Well I spent a full day trying to figure out why it suddenly started working and trying to figure out why it was originally broken, but I cannot figure it out. I'll close this for now.

**Comment by HazAT** [comment]
I've learned that deleting `node_modules` from time to time when working with react-native helps a lot, so I am guessing that this could have been the issue.
Still, if you encounter it again, feel free to reopen it.
