### ISSUE TITLE
[Android] Uploads source maps on react-native run-android --variant=release

### ISSUE THREAD

**Issue by kesha-antonov** [getsentry/react-native-sentry#199]
Hello!

_Platform:_
- [!]  Android

Config:

```
Sentry.config('https://...@sentry.io/...', {
deactivateStacktraceMerging: true
}).install()
```

---
I have following issue:

When I run  ```react-native run-android --variant=release``` react-native-sentry uploads source maps. I think it should not do it.

**Steps to reproduce:**
``` rm -rf android/app/build && cd android && ./gradlew assembleRelease && react-native run-android --variant=release```

**Actual result:**
Uploads on build and on installing release on device

**Expected result:**
Uploads only on build

**Comment by kesha-antonov** [comment]
Hello!
It's still happening even if I just run ```react-native run-android --variant=release```

**Comment by HazAT** [comment]
This issue is already really old, I will close this now.
You can always change the gradle file and remove sentry from there, then we don't upload anything.
