### ISSUE TITLE
iOS Setup Instructions

### ISSUE THREAD

**Issue by JAStanton** [getsentry/react-native-sentry#200]
In the manual setup instruction docs iOS: https://docs.sentry.io/clients/react-native/manual-setup/#ios We are asked to install initialize RNSentry like so:

```objective-c
#if __has_include(<React/RNSentry.h>)
#import <React/RNSentry.h> // This is used for versions of react >= 0.40
#else
#import "RNSentry.h" // This is used for versions of react < 0.40
#endif

/* in your didFinishLaunchingWithOptions */
[RNSentry installWithRootView:rootView];
```

Should we just drop this completely? The source for `installWithRootView` says: `// For now we don't need this anymore` https://github.com/getsentry/react-native-sentry/blob/master/ios/RNSentry.m#L37-L39

**Comment by HazAT** [comment]
Hey, good find. We've discussed this and you are right we don't do anything with it right now, we did in the past. We decided that we leave it in there in case we ever need it again. It's also possible that we drop it in the future we will see but for now, we will leave it like this.
