### ISSUE TITLE
Support for stacktrace: true

### ISSUE THREAD

**Issue by JAStanton** [getsentry/react-native-sentry#201]
_Platform:_
- [x]  iOS
- [x]  Android

paranoid redacted `npm ls`:
```
@REDACTED@0.0.0
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.3
├── react-native@0.44.3
├── react-native-code-push@2.1.1-beta
├── react-native-sentry@0.17.1
```

Config:

```
Sentry.config(__CONFIG__.sentry.dsn, {
  deactivateStacktraceMerging: false, 
  logLevel: SentryLog.Verbose, 
  disableNativeIntegration: false, 
  ignoreModulesExclude: [], 
  ignoreModulesInclude: ["RNSentry"], 
}).install();
```

---
I have following issue:

I want to be able to `Sentry.captureMessage` an error with a stacktrace:

```js
Sentry.captureMessage(new Error('Hello'), { level: SentrySeverity.Error, stacktrace: true });
```

This is supported in Raven https://github.com/getsentry/raven-js/pull/582 but unsure why It's not working.

When I log something like this, I get:

![image](https://user-images.githubusercontent.com/645300/29473545-05952b10-840d-11e7-9cc0-9720e80eae70.png)

When I should expect a stacktrace:

![image](https://user-images.githubusercontent.com/645300/29473559-1773370a-840d-11e7-828d-738e796ad2ff.png)

**Comment by HazAT** [comment]
Hey, sorry for not replying earlier.
This should already work if you use:
```
Sentry.captureException(new Error('Oops!'), {
      logger: 'my.module'
    });
```

**Comment by JAStanton** [comment]
Ah I see why I didn't do that earlier, `captureException` defaulted to level fatal , I see now that I can override with `level: SentrySeverity.Error`. 👍 beautiful.
