### ISSUE TITLE
Getting the following error 

### ISSUE THREAD

**Issue by AlmogRnD** [getsentry/react-native-sentry#202]
I'm getting the following error when I build my app for release 

Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
error: http error: [7] Couldn't connect to server (Failed to connect to 976bc55ffa624352ba7aa5a1c630f783 port 443: Operation timed out)

**Comment by HazAT** [comment]
It seems like that you pasted the wrong string on the setup.
Open your `sentry.properties` file and make sure your url looks something like this:
`defaults.url=https://sentry.io/`

**Comment by AlmogRnD** [comment]
Thanks

**Comment by AlmogRnD** [comment]
@HazAT I'm still getting the following error after updating the url 

```
Batch 1
> Found 1 debug symbol files.
> Checking for missing debug symbol files on server
error: http error:  (404)
```

My settings 

```
defaults.url=https://sentry.io/
defaults.org=construction-cloud
defaults.project=construction-cloud-mobile-ap
auth.token=27e54aa905be469392a57ad99afcb8349fd12c335c0a47c89fed6faf96378b33
cli.executable=/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/sentry-cli-binary/bin/sentry-cli
```

**Comment by HazAT** [comment]
Hey, I think you are missing one `p` in your project's slug:
`construction-cloud-mobile-app`
Also you might consider changing your auth token, since it should be kept in secret.

**Comment by AlmogRnD** [comment]
Thanks that was it
