### ISSUE TITLE
Use of undeclared identifier 'RNSentry'

### ISSUE THREAD

**Issue by Tomatoo** [getsentry/react-native-sentry#206]
_Platform: ios simulator

after "react-native link react-native-sentry", i get error 'Use of undeclared identifier 'RNSentry''.

i find that, the link command add `[RNSentry installWithRootView:rootView];`in appdelegate.m file ,but not include some .h file, is right?

**Comment by HazAT** [comment]
There should be something like this on top of the `AppDelegate.h` file:
```
#if __has_include(<React/RNSentry.h>)
#import <React/RNSentry.h> // This is used for versions of react >= 0.40
#else
#import "RNSentry.h" // This is used for versions of react < 0.40
#endif
```
https://docs.sentry.io/clients/react-native/manual-setup/#appdelegate

**Comment by KkkkKernc** [comment]
@HazAT hi there,
i've added those code on the top of the `AppDelegate.h` file,
but i get some new errors in the `RCTRootView.h` file, like this:
```
Redefinition of 'RCTRootViewSizeFlexibility'
```

**Comment by HazAT** [comment]
It seems like something went really wrong when setting up your react-native project.
Did you follow this guide?:
https://facebook.github.io/react-native/docs/getting-started.html#installing-dependencies
Since this error indicates that either react-native has been imported twice.
Also you can checkout the example project:
https://github.com/getsentry/examples/tree/master/react-native
https://github.com/getsentry/examples/blob/master/react-native/AwesomeProject/ios/AwesomeProject/AppDelegate.m

**Comment by HazAT** [comment]
@Tomatoo @KkkkKernc Can you paste your output of
`npm ls --prod --depth=0` please?

**Comment by Tomatoo** [comment]
thans, it is our problems and we have solved it.

**Comment by prithsharma** [comment]
I just did these two steps on codebase -
- `npm i --save react-native-sentry`
- `react-native link react-native-sentry`

and I am getting this 'undeclared identifier' error when building for iOS.

To confirm what @Tomatoo said, the link step doesn't add [these](//#import <React/RNSentry.h>) import statements to `AppDelegate`. Manually adding those lines leads to the errors that @KkkkKernc talks about [here](https://github.com/getsentry/react-native-sentry/issues/206#issuecomment-325268997).
@Tomatoo what was the solution in your case?

@HazAT the output of `npm ls --prod --depth=0` for me -
```
├── babel-plugin-transform-remove-console@6.8.5
├── babel-preset-react-native-stage-0@1.0.1
├── color@1.0.3
├── lodash.debounce@4.0.8
├── moment@2.18.1
├── moment-timezone@0.5.13
├── native-base@0.5.20
├── node-emoji@1.8.1
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
├── react-native@0.44.3
├── react-native-action-button@2.0.20 (git+https://github.com/cvquant/react-native-action-button.git#2e56d8a88c82be1d1f062075c85ad5afeaf2213a)
├── react-native-android-statusbar@0.1.3
├── react-native-appstate-listener@1.0.0
├── react-native-blur@3.1.2
├── react-native-chart-android@1.0.3 (git+https://github.com/cvquant/react-native-chart-android.git#a3df9c2cfd226c8e507ff1277ba540cd0a67fc96)
├── react-native-code-push@2.0.3-beta
├── react-native-cookies@3.1.0
├── react-native-deprecated-custom-components@0.1.0
├── react-native-extended-stylesheet@0.3.2
├── react-native-fabric@0.4.1
├── react-native-fbsdk@0.6.1
├── react-native-gifted-chat@0.1.3 (git+https://github.com/cvquant/react-native-gifted-chat.git#c5ec75bb22d00c5b634c411a9beb1e00a9cfcc43)
├── react-native-google-signin@0.10.0 (git+https://github.com/prithsharma/react-native-google-signin.git#fcf945cae2ae41b7272afcf51d54232c709713b2)
├── react-native-instabug@0.2.8 (git+https://github.com/cvquant/react-native-instabug.git#f34253704b0b9d21fa5b237104aa8e88f4159f22)
├── react-native-interactable@0.0.9
├── react-native-intercom@5.9.0
├── react-native-ios-charts@0.3.0 (git+https://github.com/cvquant/react-native-ios-charts.git#51a0a2289022cd0cf6ffdba0d9bb2d7100aa41d1)
├── react-native-keyboard-aware-scroll-view@0.2.9
├── react-native-keyboard-spacer@0.3.1
├── react-native-linear-gradient@2.3.0
├── react-native-material-design@0.3.8 (git+https://github.com/cvquant/react-native-material-design.git#25810fc29b9e57964317338a9fa65ce0f816d981)
├── react-native-modal@2.5.0
├── react-native-modal-picker@0.0.16 (git+https://github.com/cvquant/react-native-modal-picker.git#525bf444ac6b19251d99cafb2b603998a501b5af)
├── react-native-parallax-scroll-view@0.19.0
├── react-native-picker@4.0.19
├── react-native-router-flux@3.39.2
├── react-native-scrollable-tab-view@0.5.5
├── react-native-segment-io-analytics@0.0.6 (git+https://github.com/cvquant/react-native-segment-io-analytics.git#ddd164370104c09156261e5abad5bbebbe9f53ad)
├── react-native-sentry@0.23.2
├── react-native-share@1.0.20
├── react-native-shimmer@0.1.0 (git+https://github.com/cvquant/react-native-shimmer.git#75dbe9592465ca9606504c7471591c910fd22cf6)
├── react-native-simple-toast@0.0.6
├── react-native-slider-android@1.1.2
├── react-native-snap-carousel@2.1.4
├── react-native-vector-icons@4.3.0
├── react-native-webview-android@1.1.10
├── react-navigation@1.0.0-beta.11
├── react-redux@4.4.8
├── reactotron-react-native@1.11.1
├── redux@3.6.0
├── redux-actions@2.2.1
├── redux-form@6.8.0
├── redux-logger@2.10.2
├── redux-persist@4.8.0
├── redux-thunk@2.2.0
├── reselect@2.5.4
└── uuid@3.0.1
```

Any ideas?

**Comment by HazAT** [comment]
@prithsharma Please run `react-native unlink react-native-sentry` twice and make sure there are no signs left of Sentry in your project (check Frameworks, libraries, AppDelegate).
After that link it again, these errors indicate that your project isn't set up correctly.

**Comment by fibbers** [comment]
I also experienced this issue and what worked for me was modifying `AppDelegate.m` as follows:

```objectivec
// replace this:
#import "RCTRootView.h"

// with:
#import <React/RCTRootView.h>
```

NB: this was on another project, however I had the same error and came here after searching for a solution 😃 
NB2: I'm using RN 0.48

**Comment by karla** [comment]
I am getting same issue with RNSentry.h file not found, but it should ask for <React/RNSentry.h> which is in the project and react native is > 0.40

**Comment by HazAT** [comment]
@karla Can you verify you Xcode project contain `RNSentry`?
<img width="213" alt="screenshot 2018-07-13 08 56 31" src="https://user-images.githubusercontent.com/363802/42677040-af4c2f12-867a-11e8-96b5-ae48c5022a26.png">

**Comment by karla** [comment]
@HazAT no it is not containing this... I have seen that a manual update for pods, could solve that, but I prefer not to update pods due to the way my project is configured, so I am wonder if there is any aditional way to solve it? thanks

**Comment by HazAT** [comment]
@karla Well, you would have to manually include it in your project. Since this is different depending on your setup we did not really document it since it's different for every project. But basically what you have to do is drag & drop `RNSentry.xcodeproj` into your project.

Also, you should be able to pin the versions of your Pods and update them anytime.

**Comment by sasurau4** [comment]
I met same error `Use of undeclared identifier 'RNSentry` after following [manual setup](https://docs.sentry.io/clients/react-native/manual-setup/#ios)

I found it is important the order of `[RNSentry installWithRootView:rootView];`

My `AppDelegate.m` when error occurred.
```
...
  [RNSentry installWithRootView:rootView];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"myApp"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
...
```

changed `AppDelegate.m` when worked fine
```
...
RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"myApp"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
[RNSentry installWithRootView:rootView];
...
```

If you met same error, be sure to locate `[RNSentry installWithRootView:rootView];` after `RCTRootView`.
