### ISSUE TITLE
No such module 'KSCrash'

### ISSUE THREAD

**Issue by niftylettuce** [getsentry/react-native-sentry#21]
Not using Expo, followed all instructions, getting this error:

<img width="264" alt="screen shot 2017-03-26 at 5 02 22 pm" src="https://cloud.githubusercontent.com/assets/523141/24335161/0cd377da-1246-11e7-9438-23f992d3316a.png">

**Comment by niftylettuce** [comment]
`ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` is set to `YES` as well

Cleaned + built

Also did all the stuff with "Bundle React Native code and images"

**Comment by niftylettuce** [comment]
I'll just not use this for now, but it seems like the documentation isn't really accurate.

Also there is a typo in your docs:

https://docs.sentry.io/clients/react-native/#client-configuration

```diff
+#import "RNSentry.h"
-#import <React/RNSentry.h>
```

**Comment by HazAT** [comment]
Hey,
which version of `react-native` do you use?

**Comment by cihancil** [comment]
Same issue. RN 0.43.0-rc.2

<img width="247" alt="screen shot 2017-03-31 at 16 14 02" src="https://cloud.githubusercontent.com/assets/9278709/24551923/34cf4ad0-162d-11e7-8340-16ac627b9a1e.png">

**Comment by farhansalam** [comment]
Same problem with 

```bash
react-native-cli: 2.0.1
react-native: 0.38.1
```

```bash

/...RN-project/node_modules/react-native-sentry/ios/Sentry/Sources/Contexts.swift:10:8: error: no such module 'KSCrash'
import KSCrash
       ^
```

**Comment by ozsirma** [comment]
Any progress for this issue ? I have same error.

**Comment by samratshekhar** [comment]
Having the same issue.
```
react-native: ~0.39.0
react-native-sentry: ^0.7.0
```

Here's what I've tried so far
Tried building individual schemes in the given order 
`KSCrash-iOS` > `Sentry-iOS` > `RNSentry`

First two build successfully, **no KSCrash issue** . But building RNSentry gives compile error `"RCTBridge.h file not found`" in `RNSentry.h`

**Comment by pvinis** [comment]
is cant we just use the libs we alredy have in a project? i use sentry-swift from carthage, so i have sentry and kscrash already. cant i use react-native-sentry with these ones?

**Comment by JoschaP** [comment]
+1

**Comment by secobarbital** [comment]
I got past this by adding `KSCrash.framework` to the _Build Phases > Link Binary With Libraries_ list of _RNSentry.xcodeproj > Libraries > Sentry.xcodeproj_.

Then I ran into an error finding `RCTEventEmitter.h` which I solved by adding `$(SRCROOT)/../../react-native/React` (recursive) to the _Build Settings > Header Search Paths_ of `RNSentry.xcodeproj`.

**Comment by mitsuhiko** [comment]
We tried reproducing this in various ways now and we did not manage to encounter this issue. Are you using it with carthage or cocoapods?

**Comment by secobarbital** [comment]
No carthage and no cocoapods for me. BTW I had the same problem with the example app in the repo.

**Comment by niftylettuce** [comment]
I switched to Bug Snag 😀

**Comment by mitsuhiko** [comment]
@secobarbital any chance you could zip up the example project as it exists on your machine since you say this shows this bug for you? (including `node_modules` and all other stuff).

**Comment by mitsuhiko** [comment]
The theory is that something messes up the xcode project under some circumstances.

**Comment by HazAT** [comment]
Hey, please upgrade to the latest release 0.11.0.
We switched our internal client from swift to objc, this should resolve all related issues here.

**Comment by robertmerten** [comment]
We're still seeing issues when we're trying to archive the app with fastlane. Probably has to do something with the release build. 

Fastlane tries to build with the release config and there the libraries aren't included properly anymore. Works with Debug build in XCode.

`
xcodebuild -scheme {ProjectName} -project ios/{ProjectName}.xcodeproj -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/{username}/Library/Developer/Xcode/Archives/2017-05-31/{ProjectName}\ 2017-05-31\ 20.00.38.xcarchive clean archive CODE_SIGN_IDENTITY={CodeSignIdentity}
....
 Copying SentrySerializable.h
▸ Copying SentryFrame.h
▸ Copying SentryBreadcrumbStore.h
▸ Copying Sentry.h
▸ Copying SentryNSURLRequest.h
▸ Copying SentryBreadcrumb.h
▸ Copying RSSwizzle.h
▸ Copying SentryDefines.h
▸ Copying SentryClient.h
▸ Copying SentryThread.h
▸ Copying SentryUser.h
▸ Copying SentryStacktrace.h
▸ Copying SentryEvent.h
▸ Copying SentryContext.h
▸ Copying SentryLog.h
▸ Copying SentryDebugMeta.h
▸ Copying SentryException.h
▸ Copying SentrySwizzle.h
▸ Copying SentryFileManager.h
▸ Copying SentryQueueableRequestManager.h
▸ Copying SentryRequestOperation.h
▸ Copying NSDate+Extras.h
▸ Copying SentryKSCrashReportSink.h
▸ Copying SentryKSCrashReportConverter.h
▸ Copying NSData+Compression.h
▸ Copying SentryAsynchronousOperation.h
▸ Copying SentryDsn.h
▸ Copying SentryKSCrashInstallation.h
▸ Copying SentryError.h
▸ Running script 'Run Script'
▸ Building RNSentry/RNSentry [Release]
▸ Check Dependencies

❌  /Users/robertmerten/dev/AboutYouMobileApp/node_modules/react-native-sentry/ios/RNSentry.m:10:9: 'KSCrash/KSCrash.h' file not found

#import <KSCrash/KSCrash.h>
'

**Comment by jarredwitt** [comment]
We're seeing the exact same issue as above. Archiving in release mode causes an 'KSCrash/KSCrash.h' file not found error.

**Comment by HazAT** [comment]
@robertmerten @jarredwitt 
Sorry guys for running into that issue, please upgrade to `0.11.2` this will fix it!

**Comment by HazAT** [comment]
`0.11.3` 😅
