### ISSUE TITLE
SetUserContext doesn't work on IOS 10.4.3

### ISSUE THREAD

**Issue by OlivierNguyen** [getsentry/react-native-sentry#211]
I wrapped `setUserContext` into function and call it in the `ComponentDidMount` of my app.
```
export const sentrySetUserContext = (user) => {
  Sentry.setUserContext(getUserInfo(user));
};

const getUserInfo = (user) => ({
  userID: user.id.toString(),
});
```

To test, I add a button which calls `Sentry.nativeCrash()`. 
I received the error in the Sentry console but without information about UserID. 
It only shows my IP.

IOS version: 10.4.3
Sentry version: 0.21.1

I did not test on Android.

**Comment by HazAT** [comment]
Hey, can you enable verbose logging:

```
Sentry.config("DSN", {
  logLevel: SentryLog.Verbose
}).install();
```

You should see a output similar to this:
```
'react-native-sentry (setUserContext):', { userID: '12341' }
```

I wasn't able to reproduce this, please make sure your setUserContext is called.

**Comment by OlivierNguyen** [comment]
I see the output:
![capture d ecran 2017-08-29 a 15 32 46](https://user-images.githubusercontent.com/1394184/29823686-af60ec54-8ccf-11e7-94e0-e0039300b836.png) but on the website (Sentry console), i did not see theses informations.

I created a new project using `create-react-native-app` and did the same steps, and it seems to work. I'll investigate more to understand what happened.

Thanks you

**Comment by OlivierNguyen** [comment]
I still don't know why the `userID` is not shown in the Sentry console.

Is it possible to see easily the content that is sent to your Sentry server when a crash occurs ? It seems that the information about user is lost, but i do not know where.

Thanks

**Comment by OlivierNguyen** [comment]
I come with some insights:

Using Charles, I saw a difference in the body request between my app (which doesn't work) and the mini-app (which works).
 The function called on both app is : 
```
Sentry.setUserContext({ userID: "12345", extra: { country: 75 } })
```

Content of data sent to Sentry API in my App (not working): 
```
"user": {
		"id": "12345",
		"username": "(null)",
		"email": "(null)",
		"extra": {
			"country": 75,
		}
	}
```

And content of data sent to Sentry API with mini-app (works): 
```
"user": {
		"userID": "12345",
		"extra": {
			"country": 75,
		}
	}
```

I don't know why it added "username" and "email" keys and set them to "(null)". Because `"(null)"` is not a valid email, it won't display the user context in the Sentry console.

My little fix was to set username and email with fake values in `setUserContext`function.

I'm using Sentry@0.21.2

**Comment by HazAT** [comment]
Thank you very much for investigating this so thoroughly, I will release a fix for this soon.
