### ISSUE TITLE
XCode Simulator - Logs Sentry Errors that don't correspond to actual code

### ISSUE THREAD

**Issue by blairvanderhoof** [getsentry/react-native-sentry#215]
_Platform:_
- [x ]  iOS
- [ ]  Android

I have following issue:

1. Make some code changes
2. Run app in simulator.
3. After app loads, check Sentry, errors show that don't exist in the codebase.  They also point to lines that don't make sense (random lines in my StyleSheet). It's complaining a variable does not exist whereas it does in the code.
4. I even renamed that variable to something else, but Sentry still logs the error with the old name.

I feel like Sentry is taking an old error and keeps uploading it when deployed in the simulator. It also says Fatal, but my app never crashes.

**Comment by HazAT** [comment]
Hey,

This sounds very strange, I assume your app is running in `DEBUG` right?
Can you enable verbose logging and send the output to daniel@sentry.io over a few app start maybe.
```
Sentry.config('DSN',
  {
    logLevel: SentryLog.Verbose
  }
).install();
```

Thx

**Comment by HazAT** [comment]
I will close this for now since I didn't get a reply.
Please feel free to reopen it when you are able to add more information about the issue.
