### ISSUE TITLE
`react-native link react-native-sentry` does nothing

### ISSUE THREAD

**Issue by poffdeluxe** [getsentry/react-native-sentry#218]
_Platform:_
- [x ]  iOS
- [ x]  Android

I have following issue:
Recently attempted to update my version of `react-native-sentry` in my app. I installed the latest version of react-native-sentry with yarn. Ran `react-native unlink react-native-sentry` followed by `react-native link react-native sentry`. Nothing is linked or added. Output looks like this

```
poffdeluxe:app (build-fixes)$ react-native link react-native-sentry
Scanning 808 folders for symlinks in /Users/poffdeluxe/Development/app/node_modules (7ms)
poffdeluxe:app (build-fixes)$
```

If I attempt to re-run `react-native unlink react-native-sentry` I get:
```
rnpm-install info Android module react-native-sentry is not installed
rnpm-install info iOS module react-native-sentry is not installed
```

According to docs, I should have files added and patched with the link but none of that is happening.

Using:
react: 16.0.0-alpha.12
react-native: 0.47.0
sentry-cli: 1.19.1
react-native-sentry: 0.22.0

**Comment by HazAT** [comment]
Hey, thanks for reporting.
Can you please upgrade to react-native `0.47.2` this should fix this error.
This was an error in react-native itself.

**Comment by poffdeluxe** [comment]
Dang! Thought I was all up-to-date. I'll give this a shot soon. Thanks for the help and sorry for cluttering up your issues 😆

**Comment by poffdeluxe** [comment]
Worked! All good!
