### ISSUE TITLE
setEventSentSuccessfully has bare data on Android

### ISSUE THREAD

**Issue by JAStanton** [getsentry/react-native-sentry#220]
_Platform:_
- [ ]  iOS
- [x]  Android

Output of `npm ls --prod --depth=0`

paranoid redacted `npm ls`:
```
@REDACTED@0.0.0
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.3
├── react-native@0.44.3
├── react-native-code-push@2.1.1-beta
├── react-native-sentry@0.22.0
```

Config:

```js
Sentry.config(__CONFIG__.sentry.dsn, {
  deactivateStacktraceMerging: false, 
  logLevel: SentryLog.Verbose, 
  disableNativeIntegration: false, 
  ignoreModulesExclude: [], 
  ignoreModulesInclude: ["RNSentry"], 
}).install();
```

---
I have following issue:

When I get a callback for `setEventSentSuccessfully` on iOS I have _a lot_ of useful information. but on Android there is only `event_id` & `level`. To be fair this is documented as something that could happen I just wasn't aware that on Android this was always the case. Any idea when we could get more details? Just the error message itself would be super useful.

**Comment by HazAT** [comment]
I've released version `0.23.0` which now also includes 

- `message`
- `tags`
- `extra`
- `release`
- `dist`
