### ISSUE TITLE
Invalid DSN, the following properties aren't set '[secret key]'

### ISSUE THREAD

**Issue by antoinerousseau** [getsentry/react-native-sentry#224]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && yarn version`

```
v6.10.2
yarn version v0.27.5
```

Config:

```
Sentry.config('https://...@sentry.io/...').install()
```

---
I have following issue:

I followed the auto install steps, the java files seem properly modified, but the app crashes.

**Steps to reproduce:**
- `yarn add react-native-sentry``
- `react-native link react-native-sentry` & answer questions
- My `sentry.properties` is properly generated:

```
defaults.url=https://sentry.io/
defaults.org=tribeez
defaults.project=wedofamilies
auth.token=8bfxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx219
cli.executable=node_modules/sentry-cli-binary/bin/sentry-cli
```

**Actual result:**

<img width="566" alt="capture d ecran 2017-09-06 22 16 23" src="https://user-images.githubusercontent.com/160279/30132575-1ec3659a-9351-11e7-9a00-01876c0bed6e.png">

**Expected result:**
- Working app

**Comment by antoinerousseau** [comment]
OK found the cause, I was using a public DSN instead of the one including the secret key.
The error was quite clear in the end, thanks!
I was migrating from raven-js which was using the public DSN.

**Comment by HazAT** [comment]
Hey, thanks for pointing this out. We will in some point in the future remove the secret part of the DSN so this should no longer happen.

**Comment by miracle2k** [comment]
I was searching for this, because I had this exact question. Isn't it a bad thing to ship the secret key with the app? I'd essentially be exposing it publicly. Or is it not a big deal?

**Comment by HazAT** [comment]
It's not a big deal, the security implication is only that someone can send events on your behalf, which your only resolve is to revoke the API key and ship a new one. There's no other access given by default with client keys.
This is mostly the same for all analytics/error tracking apps out there.

**Comment by miracle2k** [comment]
Thanks. I found this discussion with more information about the difference: https://github.com/getsentry/sentry/issues/3696

**Comment by leethree** [comment]
I don't think it's a good idea to ship secrets within the app. Client apps should be treated the same as browsers. If the secrets don't make a difference, Sentry SDK should allow using Public DSN instead of DSN with secrets.

**Comment by HazAT** [comment]
@leerhree You are right and we are currently working on this. 
Technically it‘s no secret, we will drop the „secret“ part in the future but nothing to announce yet.
For now please use the DSN with secret.

**Comment by leethree** [comment]
@HazAT Glad to hear! Thanks a lot!

**Comment by BaptisteT** [comment]
Hello @HazAT, is there any plan to drop the secret part soon?

**Comment by HazAT** [comment]
@BaptisteT inofficially it has been merged today and will soon hit prod, but psst 🤐 
https://github.com/getsentry/sentry/pull/6786

**Comment by vladikoff** [comment]
@HazAT when would that be available in the open source release? I don't see any releases this year at https://github.com/getsentry/sentry/releases

**Comment by HazAT** [comment]
@vladikoff We are currently in the process of releasing a major update (Sentry 9).
Sorry, for the inconvenience please stay tuned.

**Comment by vladikoff** [comment]
No worries, just checking!

**Comment by jamesisaac** [comment]
Got caught out by this as the [docs](https://docs.sentry.io/clients/react-native/#client-configuration) suggest using the new style DSN.  And the error message doesn't really bubble up, so you just see a cryptic `Error during init / createErrorFromErrorData` (I suspect this was the issue for #432).

**Comment by HazAT** [comment]
@jamesisaac I just tried it with a clean example and it works just fine with the "public" DSN.

**Comment by jamesisaac** [comment]
Hmm, anything I can do to help you debug?  RN 0.55.3 project.  I first installed/linked Sentry a couple of days ago, yarn.lock:

```
react-native-sentry@^0.38.1:
  version "0.38.1"
  resolved "https://registry.yarnpkg.com/react-native-sentry/-/react-native-sentry-0.38.1.tgz#a65540db41886cc0dd803012b0044b8e9f38199a"
```

After adding `e.getMessage()` to the `promise.reject` call I saw the error was:

```
07-09 11:29:56.282 22024 22082 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
07-09 11:29:56.282 22024 22082 W ReactNativeJS: Error: Error during init Invalid DSN, the following properties aren't set '[secret key]'
07-09 11:29:56.282 22024 22082 W ReactNativeJS: createErrorFromErrorData@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:2039:26
```

Switching back to legacy DSN did indeed solve the error.

**Comment by jamesisaac** [comment]
One more note is that this only happened when running in dev (OS: Windows / Platform: Android). Integration seemed to work fine in release builds with the public DSN.

**Comment by HazAT** [comment]
@jamesisaac version `0.38.2` is on its way fixing this issue.

**Comment by jamesisaac** [comment]
Great!  Thanks.

**Comment by Lrgbird** [comment]
I am using version 1.7.3 of the SDK. The DSN configuration I copied from the Sentry backend to the project does not take effect. Sentry.init("https://c5239d53ffcca0341672565857e7c9ff@o4505798742441984.ingest.sentry.io/4505821052993536",new AndroidSentryCl ientFactory (this.getApplicationContext()));
