### ISSUE TITLE
Performance issues in production with react-native-sentry@0.15.0+

### ISSUE THREAD

**Issue by OlivierNguyen** [getsentry/react-native-sentry#225]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

I have some performance issues (app very slow and freeze) using `react-native-sentry@0.15.0+`in release mode.

I tested each version of react-native-sentry on an `iPhone 7 iOS 10.3.3`.
- `react-native-sentry@0.15.0` until `0.23.0` => Performance issues
- `react-native-sentry@0.14.16` => Work well

It is weird because:
- In debug mode, everything works. (Simulator & iPhone)
- On simulator, everything works. (release & debug mode / each versions of sentry since `0.14.16`)
- On external device (iPhone 7): performance issue with `0.15.0+` but good with `0.14.6`

I read the commits between 0.14.16 and 0.15.0 and nothing looks weird.
Do you have any tips or idea about this bug ?

I'll investigate more and come back if i find something.

Thanks.

**Comment by HazAT** [comment]
Are you using `react-navigation`?
Because this should be fixed with the latest release `0.23.0`
https://github.com/getsentry/react-native-sentry/issues/158
You can also try to do this:
https://github.com/getsentry/react-native-sentry/issues/158#issuecomment-316619835

**Comment by OlivierNguyen** [comment]
Yes i'm using `react-navigation`.
I tried and it works by adding `deactivateStacktraceMerging: true` in `Sentry.config()`.

Thank you !

**Comment by HazAT** [comment]
Ok, still the issue should be resolved with the latest version `0.23.0` many people also confirmed that. 
Please make sure to delete your `node_modules` folder, make a clean build in Xcode and try it again.

**Comment by OlivierNguyen** [comment]
My bad, i don't use `react-navigation` but the Navigator used by react-native (which is deprecated now). Everything seems ok now.
