### ISSUE TITLE
Using react-native-sentry only for react native side?

### ISSUE THREAD

**Issue by julienfouilhe** [getsentry/react-native-sentry#226]
_Platform:_ iOS

I have a native app with some views in React native. I'm using Crashlytics right now to handle the native errors, but I don't like it for the react native errors since it doesn't handle the stack trace and doesn't map it with the source map, so I wanted to use Sentry for them, while still keeping Crashlytics for the native side.

So my question is: is it possible to use this client for that or do you recommend using the raven-js client with the deprecated plugin for react-native still?
If it is possible to use _react-native-sentry_, should I use `disableNativeIntegration: true`?

Thanks for your help!
Sorry I know it's not really an issue but I think it would benefit the repo if something like that was documented or at least if an answer was available in the issues :)

**Comment by HazAT** [comment]
Hey,
Yes you can disable the native tracking with `disableNativeIntegration: true`

But just keep in mind your experience may not be as good since for many features we rely on our native SDK (device information, more detailed breadcrumbs, mixed stack traces ...)

**Comment by pkantsedalov** [comment]
@HazAT Hi. Is there any way to integrate **both** Crashlytics & Sentry? Because when we follow the plain integration examples from docs we get on Sentry output, it seems like it outpaces Crashlytics in crash catching.
