### ISSUE TITLE
tags and capturing from objc, swift, and js

### ISSUE THREAD

**Issue by pvinis** [getsentry/react-native-sentry#23]
hi, right now we have an app with objc, swift and js with react native. currently we use sentry-swift, and we have a small wrapper that we can call from all three.
with react-native-sentry, can we still do that? do we need to make the wrapper call to the js part? or can we use `Sentry.capture..` from js and `[Sentry capture..]`, etc?

(we get some weird errors on the website when crashes happen and the stack is incomplete. so maybe this library will help with that.)

**Comment by HazAT** [comment]
Hey, yeah this should be possible ...
For javascript SDK usage read: https://docs.sentry.io/clients/react-native/
For native SDK usage read: https://docs.sentry.io/clients/cocoa/

Also the example project is quiet helpful for sentry-swift https://github.com/getsentry/sentry-swift

**Comment by pvinis** [comment]
so i have to install and link all both react-native and swift-sentry then?

**Comment by HazAT** [comment]
If you install react-native-sentry you will get sentry-swift which you can then use in your custom native code.
Just import it `@import Sentry`

**Comment by pvinis** [comment]
aha ok. so they i use the swift one for native code, and the other for js.

but can i set the tags and the dsn etc from js? or only native? or do i have to set it up from both?

**Comment by HazAT** [comment]
If you want to use sentry in both your custom js code and swift code ... you have to set them up separately ... see docs.

**Comment by pvinis** [comment]
ok. so i treat them as separate things. thanks. in the docs for react-native it doesnt say anything about using sentry in the native part, so i was confused.

**Comment by pvinis** [comment]
@HazAT is `@import Sentry` still a thing thats possible? i cant seem to be able to import it.

**Comment by HazAT** [comment]
@pvinis How did you install it?
`@import` should work if you install it via CocoaPods
If you use the latest version you have to import it like this
```
#import <KSCrash/KSCrash.h>
#import <Sentry/Sentry.h>
```

**Comment by pvinis** [comment]
i am not using cocoapods.
i just installed via yarn, and linked.
on objc, i can import, but on swift i cant.
