### ISSUE TITLE
Breadcrumbs should display JSON representation of objects instead of "[object Object]"

### ISSUE THREAD

**Issue by Buthrakaur** [getsentry/react-native-sentry#231]
Sentry Breadcrumbs display `object.toString()` representation for `console.log('message', {value: 1})`, which is quite useless. The console arguments should be sent to Sentry in JSON (`JSON.stringify()`) so as the values are displayed instead of `[object Object]`.

![image](https://user-images.githubusercontent.com/126757/30311827-60a804f8-9797-11e7-9b20-89252fdea733.png)

**Comment by HazAT** [comment]
Hey,
I will look into this.

**Comment by fungilation** [comment]
Would be great if it's similar to console improvement made in Chrome since 60 (or 61), which show collapsed snippets of elements inside the Object before expanding the object in console logs.

**Comment by Toub** [comment]
Related to https://github.com/getsentry/raven-js/issues/623

**Comment by HazAT** [comment]
So, I guess we will not add this by default right now.
You could run `JSON.stringify(object)` yourself before adding a breadcrumb.

**Comment by felippepuhle** [comment]
can we use `beforeBreadcrumb` on `react-native-sentry`?

**Comment by nicotroia** [comment]
Is there a best practice for capturing objects in logs? Aside from refactoring the console logs in my app to JSON.stringify the contents? Thanks

**Comment by garrett-gottlieb** [comment]
Something like this:
```js
  beforeBreadcrumb: breadcrumb => {
    if (breadcrumb.category === 'console') {
      breadcrumb.message = JSON.stringify(breadcrumb.data.arguments)
    }
    return breadcrumb
  }
```
