### ISSUE TITLE
Sourcemap doesn't work

### ISSUE THREAD

**Issue by doochik** [getsentry/react-native-sentry#235]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.5.0
5.4.2

├── babel-preset-react-native@2.0.1
├── debug@3.0.1
├── lodash@4.17.4
├── moment@2.18.1
├── prop-types@15.5.10
├── react@16.0.0-alpha.12
├── react-native@0.48.3
├── react-native-appmetrica@0.0.1 (git://github.com/doochik/react-native-appmetrica.git#eae1237a98a23671655f300ab429c8f567b57d86)
├── react-native-communications@2.2.1
├── react-native-deprecated-custom-components@0.1.1
├── react-native-device-info@0.11.0
├── react-native-fabric@0.5.0
├── react-native-fabric-crashlytics@0.1.8
├── react-native-fbsdk@0.6.1
├── react-native-google-analytics-bridge@5.2.2
├── react-native-imagepicker@2.0.0
├── react-native-l20n@0.0.8
├── react-native-linear-gradient@2.2.0
├── react-native-pagecontrol@4.0.0
├── react-native-photo-view@1.3.0
├── react-native-sentry@0.23.2
├── react-native-simple-action-sheet-ios@0.0.1
├── react-native-svg@5.4.1
├── react-native-tab-navigator@0.3.4
├── react-native-vkontakte-login@0.1.17
├── react-redux@5.0.6
├── redux@3.7.2
├── redux-logger@3.0.6
├── redux-thunk@2.2.0
└── whatwg-fetch@2.0.3
```

Config:

```
// I use default config
Sentry.config('https://...@sentry.io/...', {}).install()
```

---
I have following issue:

Sentry doesn't expand error stacktrace and I see processing error "Source code was not found for app:///main.jsbundle".

At release tab I see that sourcemaps are uploaded with names `~/main.jsbundle` and `~/main.jsbundle.map`, not "app:///main.jsbundle".

Is this bug or I've missed something in Sentry config?

I use Sentry 8.19.0

**Comment by HazAT** [comment]
That should be fine, `~/` will be matched to the `app:///` prefix.
Can you link to an event so I can take a look at it?

**Comment by doochik** [comment]
Sorry, my Sentry installation is private.

May be I can provide some additional info?

**Comment by HazAT** [comment]
The release/dist also have to match in order for Sentry to symbolicate the frames correctly.

**Comment by swl367** [comment]
I'm having the same issue here, but when I build a release build via xcode, it looks like my sourcemap doesn't get uploaded to the version I want.

My Bundle React Native code and images build phase has the correct commands from running react-native link.

Any reason why my sourcemaps aren't uploading?

**Comment by HazAT** [comment]
@swl367 https://docs.sentry.io/clients/react-native/codepush/
Also you have to upload source file + sourcemap by yourself with `sentry-cli`

**Comment by swl367** [comment]
That's where I'm having trouble. If I upload the sourcemap using rewrite, strip-common-prefix, and the other commands, I still see the "cannot find source for app:///mainbundle.js" error.

**Comment by HazAT** [comment]
@swl367 I've just updated our docs and fixed bunch of stuff.
https://docs.sentry.io/clients/react-native/codepush/

Also make sure to use the latest sentry-cli version `1.20` which soon will be released.

**Comment by HazAT** [comment]
@doochik To clear things up, your upload looks fine but you have to make sure that your event version matches the release on the server where you uploaded the sourcemaps.

**Comment by valeryq** [comment]
@HazAT Right now in Sentry I see full path to main.jsbundle (/Users/development/Library/Developer/CoreSimulator/Devices/2E07D1E4-2C5F-4B9C-844F-F05443C2D3E7/data/Containers/Bundle/Application/AEFD1C68-0E1C-4160-AD1A-39B9231E29B4/Application.app/main.jsbundle)
Artifacts for this release uploaded with names (*~/main.jsbundle* and *~/main.jsbundle.map*), but it not matched with full path and logs are not parsed. Any idea?

**Comment by HazAT** [comment]
@valeryq Which version of `react-native-sentry` are you using. It should not upload frames with the full path it should look like `app:///main.jsbundle`.
If release a fix for this in the latest version, make sure to upgrade.

**Comment by valeryq** [comment]
@HazAT I'm using pure raven-js, but earlier it worked correctly :) Maybe you have some tips for me?

**Comment by HazAT** [comment]
@valeryq I would use `react-native-sentry`, and if you are not comfortable with using the native integration you can just disable it (I do not recommend doing so)
```
 Sentry.config('DSN', {
    disableNativeIntegration: true,
  }).install();
```

There are so many things to consider when running a react-native app, we do no longer support using just `raven-js` without `react-native-sentry`

**Comment by valeryq** [comment]
@HazAT so, I switched to react-native-sentry, and after that I really see `app:///main.jsbundle` in logs, great. But can I specify release name manually from JS client? And can I disable automatic sourcemap handling?

**Comment by HazAT** [comment]
@valeryq  There are:
```
Sentry.setRelease(release);
Sentry.setDist(dist);
Sentry.setVersion(version);
```
try out which fits your needs.
What do mean with automatic source map handling? If you don't want to upload source maps you can remove the run script from Xcode or gradle plugin from your android project.

**Comment by valeryq** [comment]
@HazAT super, it's working, but only need to upload sourcemaps via sentry-cli (it convert map file) and then it will be working as expected! Great!

**Comment by swl367** [comment]
@HazAT How would the documentation work for android codepush?

$ code-push release-react YourApp ios --outputDir build
$ export SENTRY_PROPERTIES=./ios/sentry.properties
$ sentry-cli react-native codepush YourApp ios ./build

Would we replace all of the 'ios' with 'android'?

**Comment by HazAT** [comment]
@swl367 right, that should do it

**Comment by swl367** [comment]
@HazAT I'm having issues with pushing a code-push release. When my account shows 0 releases, I expect v1 to be the latest code push release.

However, when I run the commands in the documentation, I get the following output:

> Fetching latest code-push package info
> Processing react-native code-push sourcemaps
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
> Uploading source maps for release com.app.id-0.1.1-codepush:**v3**

Source Map Upload Report
  Minified Scripts
    ~/main.jsbundle (sourcemap at main.jsbundle.map)
  Source Maps
    ~/main.jsbundle.map

Any ideas?

**Comment by luongs3** [comment]
@swl367 @HazAT I had the same issue, source map just not work

**Comment by HazAT** [comment]
@Kinka should be: `--url-prefix "~"` 
Also make sure you properly set up the sdk.

**Comment by Kinka** [comment]
@HazAT thanks, I'll have a try.

**Comment by tangnv** [comment]
Hi, for Android, it works well for me.
Like that:
![image](https://user-images.githubusercontent.com/4475472/55594985-02688700-576c-11e9-9a4e-3824aa451a67.png)

But for iOS, it can not get the source map 

![image](https://user-images.githubusercontent.com/4475472/55594999-13b19380-576c-11e9-9fc8-4b8e37b5cba3.png)

Any idea @HazAT ?

**Comment by Kinka** [comment]
@HazAT I have to mention again that the **source** and **sourcemap** file both need to be uploaded.

**Comment by ysfzrn** [comment]
Any progress ?  @tangnv did you solve this problem ?

**Comment by yawnr** [comment]
Getting the same @ysfzrn @tangnv -- any ideas?

**Comment by ysfzrn** [comment]
Actually, I have reset my changes and I have reinstalled carefully according to docs and it worked. I don't know what's the reason for this error.

**Comment by yawnr** [comment]
@ysfzrn Ah, interesting. Did you install manually or via CocoaPods? Which version of react native are you on?

Would you mind elaborating on your workflow?

Right now I’m doing this (after a Cocoapods install and setup per the docs):
```
// codepush
appcenter codepush release-react --app <app name> --mandatory --deployment-name Production --output-dir ./src/build/ios --sourcemap-output-dir ./src/build/ios

// upload to sentry    SENTRY_PROPERTIES=./ios/sentry.properties sentry-cli react-native appcenter --deployment Production --org=<mysentryorg> --project=<mysentryproject> ios ./src/build/ios
```

Thanks!
