### ISSUE TITLE
Build iOS failed after follow official install instruction

### ISSUE THREAD

**Issue by tavriaforever** [getsentry/react-native-sentry#239]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.4.0
5.3.0
atlantm@1.3.0 /Users/tavria/sites/atlantm
├── babel-eslint@7.2.3
├── lodash@4.17.4
├── moment@2.18.1
├── native-base@2.3.2
├── prop-types@15.5.10
├── react@16.0.0-alpha.12
├── react-native@0.47.1
├── react-native-cached-image@1.4.0
├── react-native-communications@2.2.1
├── react-native-datepicker@1.6.0 (github:tavriaforever/react-native-datepicker#7d727c0d5133fcfe7bd819b96cfb65be3ceeb73a)
├── react-native-device-info@0.11.0
├── react-native-keyboard-aware-scroll-view@0.3.0
├── react-native-loading-spinner-overlay@0.5.2
├── react-native-maps@0.16.4
├── react-native-optimized-flatlist@1.0.2
├── react-native-sentry@0.23.2
├── react-native-splash-screen@3.0.1
├── react-native-vector-icons@4.3.0
├── react-navigation@1.0.0-beta.12
├── react-redux@5.0.6
├── redux@3.7.2
├── redux-form@7.0.4
├── redux-logger@3.0.6
├── redux-persist@4.9.1
└── redux-thunk@2.2.0
```

Config:

```
Sentry.config('https://...@sentry.io/...').install()
```

---
I have following issue:

I use bitcode in my ios build. So I read about changing in this case into https://docs.sentry.io/clients/react-native/manual-setup/#build-steps

But I couldn`t archive build in iOS. I got an error 

![sentry-ios-error-1](https://user-images.githubusercontent.com/975906/30665539-fd36446a-9e59-11e7-9c97-9c8bd64524b8.png)

![sentry-ios-error-2](https://user-images.githubusercontent.com/975906/30665544-0088e47e-9e5a-11e7-9a27-9a66920ee6a6.png)

**Steps to reproduce:**
- follow official installation tutorial
```
npm install react-native-sentry --save
react-native link react-native-sentry
```
add all required information after installation.

**Actual result:**
- build crashed

**Expected result:**
- build success without uploading dSYM

**Comment by HazAT** [comment]
@tavriaforever Xcode cannot find you node installation, make sure it is exported correctly in your ENV.
Also if you are using nvm look at this: https://docs.sentry.io/clients/react-native/manual-setup/#using-node-with-nvm
