### ISSUE TITLE
ios uploading debug symbols

### ISSUE THREAD

**Issue by JasonHenson** [getsentry/react-native-sentry#248]
OS:
- [ ]  Windows
- [/ ]  MacOS
- [ ]  Linux

_Platform:_
- [ /]  iOS
- [ ]  Android

I am able to upload my bundles fine to sentry.io during the build process, but one issue I am having is that for IOS build it always uploads as main.jsbundle instead of index.ios.bundle resulting in error "Source code was not found for app:///index.ios.bundle" when I a view an issue. For Android the proper bundle "index.android.bundle" is uploaded. I looked at script "react-native-xcode.sh" and it definitely has a bundle file of main.jsbundle. I am wondering whether I misconfigured react-native-sentry or is it just something on my end?

**Comment by JasonHenson** [comment]
was just an issue on my end -- closing.

**Comment by jessym** [comment]
Can you remember how you fixed this? I'm running into the same issue.
