### ISSUE TITLE
Source code was not found for app:///index.android.bundle

### ISSUE THREAD

**Issue by JAStanton** [getsentry/react-native-sentry#249]
When uploading source maps, what are the rules in which sentry looks up the source maps by?

In the web ui for *additional data* I have `release: xxxxx` and in releases tab in the web ui I have a release with that exact version, then under artifacts with that release name I have a file uploaded entitled `~/index.android.bundle` and `~/index.android.map`, and if I look in the file for  `~/index.android.bundle` at the bottom of it there is this line:
```
//# sourceMappingURL=index.android.bundle.map
```
![image](https://user-images.githubusercontent.com/645300/31101659-98ea3c5e-a783-11e7-9f0f-41ebd59ccbfb.png)

This works for my iOS app but not my android app, (for iOS basically replace `ios` anywhere I mentioned `android` and that's how iOS is setup). 

Additional context:
I setup source map uploading myself outside of react-native setup docs, I tied it into my release process to upload docs for example.  I use Code Push so every time the app boots I call `Sentry.setExtraContext({ release: 'xxx' })` and `Sentry.setRelease()`,

perhaps I need to also call `setVersion`?
I noticed on iOS where sourcemaps works under tags there is `release`, but android there isn't? Maybe setting release is broken on Android?

**Comment by HazAT** [comment]
Hey, I've recently updated the CodePush docs 
https://docs.sentry.io/clients/react-native/codepush/
with these settings, I tried it with iOS and Android and it worked.

Note that also the dist has to match the release in sentry.

Also, can you link a few events here so I can check whats wrong?

**Comment by JAStanton** [comment]
@HazAT can I PM / email you the links directly?

**Comment by HazAT** [comment]
So we continued the conversion via email. 
The gist of it is that the release and dist have to match in order to have the source map to match.

**Comment by adnan1naeem** [comment]
Hi i am facing same issue .I dont know what am i missing.It is working fine in debugger mode but fails to load the source map when error occurs though sourcemaps have been loaded in artifacts but still facing this error.Please review my screenschots
<img width="892" alt="Screenshot 2020-10-17 at 11 37 29 PM" src="https://user-images.githubusercontent.com/22443038/96350940-dc969f00-10d1-11eb-9089-cf9829acdb10.png">
<img width="800" alt="Screenshot 2020-10-17 at 11 37 44 PM" src="https://user-images.githubusercontent.com/22443038/96350942-df918f80-10d1-11eb-8b89-bf4228c4ff6d.png">
<img width="83" alt="Screenshot 2020-10-17 at 11 38 11 PM" src="https://user-images.githubusercontent.com/22443038/96350943-e0c2bc80-10d1-11eb-8c73-e817f6f31129.png">
<img width="1181" alt="Screenshot 2020-10-17 at 11 38 15 PM" src="https://user-images.githubusercontent.com/22443038/96350945-e0c2bc80-10d1-11eb-83b0-bfeb68bc93af.png">
