### ISSUE TITLE
Blacklist errors?

### ISSUE THREAD

**Issue by JAStanton** [getsentry/react-native-sentry#250]
Is there a way to blacklist which errors to upload? I am getting spammed heavily for one error type and I would like to not send it over the wire.

**Comment by HazAT** [comment]
Hey, there are two options you can take.
First, you could use the `setShouldSendCallback` which I haven't exposed yet -> will do a release with today.
Secondly, you could go into your project settings, inbound filters, to the section called:
`Filter errors by error message:`
if you play around with that, errors filtered with this do not count against your quota.

**Comment by HazAT** [comment]
I've released `0.26.0` where you can set `setShouldSendCallback` to check if you want to send the event.
