### ISSUE TITLE
Would Sentry catch crashes if we allocate too much memory?

### ISSUE THREAD

**Issue by JAStanton** [getsentry/react-native-sentry#252]
Would sentry catch crashes if we allocate too much memory? From what I can tell on Android and possible iOS If I allocate too much memory (dealing with large images for example), the OS doesn't tell the app it just stops it. On next boot would Sentry be able to understood we crashes because the app ran out of memory?

**Comment by HazAT** [comment]
Sadly there is no way see: https://github.com/kstenerud/KSCrash/issues/10
