### ISSUE TITLE
Xcode build fails due SentryReactNative

### ISSUE THREAD

**Issue by hccoelho** [getsentry/react-native-sentry#254]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

v7.9.0
4.2.0
xxx@0.0.1 
├── apisauce@0.5.0
├── format-json@1.0.3
├── querystringify@0.0.4
├── ramda@0.22.1
├── UNMET PEER DEPENDENCY react@15.5.3
├── react-addons-perf@15.5.0-rc.2
├── react-addons-test-utils@15.5.1
├── react-dom@15.5.3
├── UNMET PEER DEPENDENCY react-native@0.42.3
├── react-native-animatable@1.2.0
├── react-native-code-push@1.17.4-beta
├── react-native-device-info@0.11.0
├── react-native-drawer@2.3.0
├── react-native-fabric@0.4.1 invalid
├── react-native-firebase@3.0.0-alpha.2 invalid
├── react-native-i18n@1.0.0
├── react-native-router-flux@3.38.0
├── react-native-sentry@0.26.0
├── react-native-vector-icons@4.1.1
├── react-native-windows@0.33.4
├── reactxp@0.42.0-rc.1
├── resub@0.0.12
└── seamless-immutable@6.3.0

Hi, 

I have XCode Version 9.0 (9A235), when I install SentryReactNative via cocoa pods I get the following errors:
```
SentryReactNative Group
Lexical or Preprocessor Issue Group
/node_modules/react-native-sentry/ios/RNSentry.m:457:5: Editor placeholder in source file
Semantic Issue Group
/node_modules/react-native-sentry/ios/RNSentry.m:103:81: Incompatible pointer types sending 'NSUInteger *' (aka 'unsigned long *') to parameter of type 'unsigned long long * _Nullable'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSScanner.h:33:56: Passing argument to parameter 'result' here
/node_modules/react-native-sentry/ios/RNSentry.m:246:21: Undeclared selector 'invokeWithBridge:module:arguments:'
/node_modules/react-native-sentry/ios/RNSentry.m:277:20: Undeclared selector 'callNativeModule:method:params:'
Value Conversion Issue Group
/node_modules/react-native-sentry/ios/RNSentry.m:247:15: Incompatible pointer to integer conversion initializing 'uintptr_t' (aka 'unsigned long') with an expression of type 'IMP' (aka 'void (*)(void)')
/node_modules/react-native-sentry/ios/RNSentry.m:278:15: **Incompatible pointer to integer conversion initializing 'uintptr_t' (aka 'unsigned long') with an expression of type 'IMP' (aka 'void (*)(void)')** 
```
I'm not an expert in building xcode projects so I was wondering if you have thoughts on how to workaround this problem.

**Comment by HazAT** [comment]
Hey, sorry for the late reply.
Maybe this helps: https://github.com/getsentry/react-native-sentry/issues/260

I will look into this and keep you posted.

**Comment by hccoelho** [comment]
Hi HazAT, thank you for the pointer. Unfortunately, it didn't. For me, the Libraries folder is empty and the RNSentry is not in the build phases. It seems something else.

**Comment by HazAT** [comment]
Hey, I've just created an example project with CocoaPods and had no trouble setting in up like this.
https://github.com/getsentry/examples/tree/master/react-native/ios-swift-cocoapods

Compare this to your project and see if you find any differences.

**Comment by HazAT** [comment]
I will close this for now.
If you are still having troubles feel free to reopen it.
