### ISSUE TITLE
'React/RCTBridgeDelegate.h' file not found

### ISSUE THREAD

**Issue by chrismllr** [getsentry/react-native-sentry#260]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`
```
v6.9.1
5.4.2
my-project@0.5.0 /Users/**/MyProject
├── react@16.0.0
├── react-native@0.47.2
├── react-native-sentry@0.26.0
```

Config:
```
Sentry.config('https://...@sentry.io/...', {
  // No updates to config
}).install()
```

---
I have following issue:
`'React/RCTBridgeDelegate.h' file not found` when installing into project using cocapods

**Podfile**
```
platform :ios, '9.0'

target 'MyProject' do
  use_frameworks!

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTAnimation',
    'RCTNetwork',
    'RCTActionSheet',
    'BatchedBridge',
    'RCTWebSocket',
    'RCTImage',
    'DevSupport',
    'RCTNetwork',
    # Add any other subspecs you want to use in your project
    'RCTLinkingIOS'
  ]

  # Pods for MyProject
  # Sentry
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  target 'MyProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

**Steps to reproduce:**
- `yarn add react-native-sentry`
- `react-native link react-native-sentry`
- Update `Podfile` to what you see above ^^
- `pod install`
- Build in XCode

**Actual result:**
- Build fails with `'React/RCTBridgeDelegate.h' file not found`

**Expected result:**
- Successful build

![screen shot 2017-10-12 at 2 18 48 pm](https://user-images.githubusercontent.com/9942917/31514753-525fb322-af58-11e7-9241-3a7248570568.png)

**Comment by chrismllr** [comment]
Issue resolved: 
1. Delete React native sentry from `Libraries` folder in workspace
2. Remove RNSentry.a from `Build Phases -> Link Binary With Libraries`

Could not find these steps in the docs anywhere - It may be more helpful to move `Setup with CocoaPods` into the `Manual Setup for iOS` docs, and outline that it must be done instead of react-native-link

**Comment by HazAT** [comment]
Hey, thanks for pointing this out, I will fix this.

**Comment by MaheshNandam** [comment]
removed 'BatchedBridge' from pod file,

after I got 'React/RCTNetworking.h' file not found,

did anyone get the same issue?

react - 16.0.0
react-native  - 0.54
XCode Version 9.3 (9E145)

**Comment by aurnik** [comment]
@MaheshNandam Did you figure this out?

**Comment by pmadruga** [comment]
@MaheshNandam I have the same issue as you. Did you manage to solve it?

**Comment by KushalDesai1** [comment]
Downgrading RN version is not the solution.

Sometimes I think, cold-war is going on between React-Native & Xcode.

Some or the other issues arises.

**Comment by daksamedia** [comment]
not working
