### ISSUE TITLE
Using Sentry.setShouldSendCallback causes Invariant Violation in AppRegistry

### ISSUE THREAD

**Issue by fivepointseven** [getsentry/react-native-sentry#268]
OS:
- [ ]  Windows
- MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- Android

Config:

```
Sentry.config('https://...@sentry.io/...').install()
```

---
I have following issue:

When trying to disable reporting in dev mode the app crashes on startup.

**Steps to reproduce:**
Set the config
Set `Sentry.setShouldSendCallback(() => false);`
Run the app

**Actual result:**
`Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`

**Expected result:**
App launching

**Comment by HazAT** [comment]
Hey, are you sure this is related to react-native-sentry?
If you don't want to report in dev just don't call `install()`
```
if (__DEV__ === true) {
....
}
```

**Comment by fivepointseven** [comment]
@HazAT thanks for the prompt reply! When I comment out Sentry stuff altogether it still sends the reports

**Comment by HazAT** [comment]
hmm, this does not make sense, Sentry only sends stuff if you call install.
Can you paste the part of your code where you include and use Sentry?

**Comment by fivepointseven** [comment]
```
import { AppRegistry } from 'react-native';
import { Sentry } from 'react-native-sentry';
import app from './app'

Sentry.config('https://...@sentry.io/...').install(); // <-- if this is commented and I throw something, it shows up in Sentry anyway

AppRegistry.registerComponent('app', () => app);

```

**Comment by HazAT** [comment]
I've just tried it if I comment out this line it does nothing.
Make sure you have this call nowhere else.

**Comment by fivepointseven** [comment]
Somehow cleaning my android build and re-installing the app on the device fixed it.
Thanks for your help!
