### ISSUE TITLE
Android : gradlew assembleRelease faild

### ISSUE THREAD

**Issue by songxiaoliang** [getsentry/react-native-sentry#269]
error: organization or project not found

Now I want to know where the organization and project are configured? Expect the author to reply as soon as possible

**Comment by HazAT** [comment]
Hey, all the auth parameters are stored in a file called `sentry.properties`.
This file will be created when calling `react-native link react-native-sentry` see:
https://docs.sentry.io/clients/react-native/

**Comment by songxiaoliang** [comment]
@HazAT origazation and project the two values where should I find it? Now I do not know where to copy

**Comment by songxiaoliang** [comment]
@HazAT I now do not know origazation and project which two values from the URL copy? Looking forward to reply

**Comment by songxiaoliang** [comment]
@HazAT yeah，I am dealing with this problem, thank you very much
