### ISSUE TITLE
captureException is level fatal on iOS and error on Android

### ISSUE THREAD

**Issue by entropitor** [getsentry/react-native-sentry#274]
I have following issue:

The log level for Android and iOS is different when using captureException

**Steps to reproduce:**
- Log an exception using captureException

**Actual result:**
- iOS logs the exception with level 'fatal'

**Expected result:**
- iOS logs the exception with level 'error'

**Comment by HazAT** [comment]
Thanks for reporting, I will check this.

**Comment by entropitor** [comment]
@HazAT shouldn't it go to "error" for both? I think fatal should be for app crashes, no?

**Comment by HazAT** [comment]
@entropitor You are absolutely right 💯
