### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForDebug'

### ISSUE THREAD

**Issue by ricbermo** [getsentry/react-native-sentry#278]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`
`7.5.0`
`4.1.2`
<img width="510" alt="screen shot 2017-10-19 at 3 53 32 pm" src="https://user-images.githubusercontent.com/2601363/31793778-d3bca4ce-b4e5-11e7-9da1-06e624c26100.png">

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```
---
I have following issue:

After installing and linking successfully `react-native-sentry` my project fails to build throwing the following error
<img width="1440" alt="screen shot 2017-10-19 at 3 56 36 pm" src="https://user-images.githubusercontent.com/2601363/31793948-47557816-b4e6-11e7-8988-92d0a3cd47d8.png">

**Steps to reproduce:**
Just install the module and run `react-native run-android`

**Actual result:**
Error described above

**Expected result:**
The app builds successfully

**Notes** I can make it work by adding `multiDexEnabled true` and `compile 'com.android.support:multidex:1.0.0'` in `android/app/build.gradle`.

**Comment by HazAT** [comment]
Hey, I am no Android guru but have you tried this also this?
https://stackoverflow.com/a/30660809/1139707
So I am pretty confident that Sentry isn't the culprit, probably only because it was added as the last plugin which causes the method overflow, so I will close this for now.
`multiDex` should solve this.
