### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by oblador** [getsentry/react-native-sentry#28]
Missing this great feature from the RN implementation. JS client has it and it's really good for tracking down bugs. Thx!

**Comment by HazAT** [comment]
Hey,
I am currently working on this PR
https://github.com/getsentry/react-native-sentry/pull/26
Which should bring all the features raven-js had and combine it with our native client ...
Stay tuned, scheduled release -> next week

**Comment by fungilation** [comment]
@oblador @HazAT  this is old issue but I'm looking for how to add custom breadcrumbs in the RN client (in JS). I'm looking at https://docs.sentry.io/clients/javascript/usage/#raven-js-recording-breadcrumbs, but no documentation on breadcrumbs in the React Native SDK.

Assuming it's been implemented, how is custom breadcrumbs done in RN? Would (occasional) console.log() statements (in production) be a shortcut to having those logs sent as Sentry breadcrumbs?

**Comment by fungilation** [comment]
Seeing https://github.com/getsentry/react-native-sentry/blob/master/typescript/Sentry-tests.ts. I assume I just do
```js
import { Sentry } from 'react-native-sentry'

Sentry.setUserContext...
Sentry.config...
Sentry.setVersion...

Sentry.captureBreadcrumb({
  message: 'Item added to shopping cart',
  category: 'action',
  data: {
     isbn: '978-1617290541',
     cartSize: '3'
  }
});
```

This should be documented/linked still, on the React Native docs section.

**Comment by HazAT** [comment]
@fungilation 
It is here on the bottom
https://docs.sentry.io/clients/react-native/config/

**Comment by fungilation** [comment]
Hidden under another link in a list of links I see. This should simply be on the same page as https://docs.sentry.io/clients/react-native/, imho
