### ISSUE TITLE
Performance issues on iOS native integration

### ISSUE THREAD

**Issue by edo1493** [getsentry/react-native-sentry#280]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v6.9.4
3.10.10
├── babel-preset-es2015@6.24.1
├── deep-equal@1.0.1
├── email-validator@1.1.1
├── es6-symbol@3.1.1
├── loadash@1.0.0
├── moment@2.19.1
├── node-emoji@1.8.1
├── react@16.0.0
├── react-native@0.49.3
├── react-native-actionsheet@2.3.0
├── react-native-background-timer@1.3.0
├── react-native-code-push@5.1.3-beta
├── react-native-collapsible@0.9.0
├── react-native-config@0.9.0
├── react-native-custom-tabs@0.1.7
├── react-native-deck-swiper@1.4.2
├── react-native-device-info@0.12.1
├── react-native-facebook-account-kit@0.9.0
├── react-native-fbsdk@0.6.3
├── react-native-fingerprint-scanner@2.2.0
├── react-native-globalize@1.2.2
├── react-native-linear-gradient@2.3.0
├── react-native-masked-text@1.6.2
├── react-native-menu@0.23.0
├── react-native-modalbox@1.4.2
├── react-native-onesignal@3.0.6
├── react-native-permissions@1.0.1
├── react-native-push-notification@3.0.1
├── react-native-safari-view@2.1.0
├── react-native-sentry@0.29.0
├── react-native-snap-carousel@3.3.4
├── react-native-splash-screen@3.0.1
├── react-native-store-review@0.1.3
├── react-native-swipeable@0.6.0
├── react-native-textinput-effects@0.4.1
├── react-navigation@1.0.0-beta.15
├── react-redux@5.0.6
├── redux@3.7.2
├── redux-ignore@1.2.4
├── redux-logger@3.0.6
├── redux-persist@4.10.1
├── redux-thunk@2.2.0
├── redux-undo@0.6.1
├── rn-viewpager@1.2.4
├── shallow-equal@1.0.0
└── xcode@1.0.0
```

Config:

```
Sentry.config(Config.SENTRY_DSN, {deactivateStacktraceMerging: true}).install();

```

---
I have following issue:

If I use raven-js, I don't see any problem. Whenever I link sentry to start tracking native events, the performance of the app drops. I see frames being dropped for pretty much every action I dispatch (I use react-redux) and also nav transitions (react-navigation). 

I have tried to deactivate the merging of the stacktrace, but I don't see much difference. I have tried both debug and release environments. I have no idea what could be conflicting here and I can understand this bug report is not really clear.

**Steps to reproduce:**
- Two actions dispatched to refresh a scrollview or a simple navigation transition.

**Actual result:**
- All the frames dropped and lag on the refresh animation. 

**Expected result:**
- 60 frames per second

**Comment by HazAT** [comment]
Hey, are you running your app in `DEV`?
If so try running in in `RELEASE`, also if you have time can you maybe try this branch and see if it fixes your problem:
https://github.com/getsentry/react-native-sentry/pull/282

It's just changes in `RNSentry.m` so you could copy the content and replace it locally and try if the performance issues are still there.

**Comment by edo1493** [comment]
@HazAT I tried both Release and Dev. I will give the branch a go, thanks!
