### ISSUE TITLE
Feature request: Report promise rejections

### ISSUE THREAD

**Issue by leethree** [getsentry/react-native-sentry#281]
It would be greatly helpful if Sentry can report unhandled promise rejections from React Native. They are often caused by hard-to-find bugs. 

`bugsnag-react-native` supports this feature. See documentation:
https://docs.bugsnag.com/platforms/react-native/configuration-options/#handlepromiserejections

And their code:
https://github.com/bugsnag/bugsnag-react-native/blob/660a2352113539f56e82b7cc14becb918c82f825/src/Bugsnag.js#L62-L72

**Comment by HazAT** [comment]
Hey, thanks I will look into this.
