### ISSUE TITLE
Incorrect code-push version created when using sentry cli

### ISSUE THREAD

**Issue by swl367** [getsentry/react-native-sentry#283]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.2.1
5.4.2

── amplitude@3.5.0
├── immutable@3.8.1
├── jwt-decode@2.2.0
├── lodash@4.17.4
├── moment@2.18.1
├── prop-types@15.5.10
├── pubnub@4.15.1
├── UNMET PEER DEPENDENCY react@15.6.1
├── react-apollo@1.4.2
├── react-dom@15.6.1
├── react-native@0.42.3
├── react-native-actionsheet@2.2.2
├── react-native-code-push@1.17.3-beta
├── react-native-config@0.3.1
├── react-native-device-info@0.10.2
├── react-native-gifted-chat@0.1.5
├── react-native-keyboard-aware-scroll-view@0.2.9
├── react-native-keychain@1.2.1
├── react-native-lightbox@0.6.0
├── react-native-local-auth@1.4.1
├── react-native-passcode-status@1.1.0
├── react-native-privacy-snapshot@1.0.0
├── react-native-progress@3.4.0
├── react-native-rsa@0.0.3
├── react-native-sentry@0.23.2
├── react-native-smart-badge@1.1.1
├── react-native-user-avatar@1.0.3
├── react-native-uuid@1.4.9
├── react-native-vector-icons@4.3.0
├── react-navigation@1.0.0-beta.11
├── react-redux@5.0.6
├── redux@3.7.2
├── redux-enhancer-react-native-appstate@0.2.0
├── redux-immutable@4.0.0
├── redux-logger@3.0.6
├── redux-thunk@2.2.0
└── url-parse@1.1.9

```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

I'm having issues with pushing a code-push release to prod. When my account shows 0 releases, I expect v1 to be the latest code push release.

However, when I run the commands in the documentation, I get the following output:

Fetching latest code-push package info
Processing react-native code-push sourcemaps
Analyzing 2 sources
Rewriting sources
Adding source map references
Uploading source maps for release com.app.id-0.1.1-codepush:v3
Source Map Upload Report
Minified Scripts
~/main.jsbundle (sourcemap at main.jsbundle.map)
Source Maps
~/main.jsbundle.map

Any ideas? My staging environment has versions up to v3, but prod does not.

I'm currently using the latest version of sentry-cli (1.21.0).

I wiped my prod/staging so that they're both on V1 and that seems to work.

**Comment by HazAT** [comment]
Have you tried running this command:
`sentry-cli react-native codepush YourApp ios ./build`

with
`sentry-cli react-native codepush YourApp ios ./build --deployment=Production`

?

**Comment by swl367** [comment]
Yes

**Comment by HazAT** [comment]
@swl367 Do you have any update on this issue?

**Comment by swl367** [comment]
@HazAT I have not tried it yet since I've just been promoting staging to production. I will give you an update once we release our next build.

**Comment by HazAT** [comment]
I will close this for now.
If you are still having troubles with this let me know.

**Comment by badaz** [comment]
The --deployment=Production is working for me
