### ISSUE TITLE
NoSuchKeyException: couldn't find key stacktrace in dynamic object

### ISSUE THREAD

**Issue by Zycon42** [getsentry/react-native-sentry#286]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.6.0
5.4.2
pzrb2b@1.7.0 /Users/honza/Projects/pzrb2b
├── chroma-js@1.3.4
├── content-disposition@0.5.2
├── diacritics@1.3.0
├── hoist-non-react-statics@2.3.1
├── humps@2.0.1
├── intl@1.2.5
├── invariant@2.2.2
├── mime-types@2.1.17
├── moment@2.18.1
├── normalizr@3.2.3
├── prop-types@15.5.10
├── query-string@5.0.0
├── ramda@0.24.1
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.12
├── react-intl@2.4.0
├── react-native@0.48.4
├── react-native-branch@2.0.0
├── react-native-config@0.6.1
├── react-native-device-info@0.11.0
├── react-native-fbsdk@0.6.1 invalid
├── react-native-fcm@8.0.1
├── react-native-fetch-blob@0.10.8
├── react-native-google-analytics-bridge@5.3.3
├── react-native-keyboard-aware-scroll-view@0.3.0
├── react-native-mixpanel@0.0.16 invalid
├── react-native-modal-dropdown@0.5.0
├── react-native-orientation@3.1.0
├── react-native-sentry@0.26.0
├── react-native-share@1.0.21
├── react-native-star-rating@1.0.8
├── react-native-svg@5.4.1
├── react-native-swiper@1.5.13
├── react-native-vector-icons@4.3.0
├── react-native-version-check@1.5.0
├── react-navigation@1.0.0-beta.13
├── react-redux@5.0.6
├── recompose@0.25.0
├── redux@3.7.2
├── redux-form@7.0.3
├── redux-logger@3.0.6
├── redux-observable@0.16.0
├── redux-persist@4.9.1
├── reselect@3.0.1
├── rxjs@5.4.3
└── validator@8.2.0

npm ERR! peer dep missing: react@^0.14.9 || ^15.0.0 || ^16.0.0, required by react-intl@2.4.0
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by recompose@0.25.0
npm ERR! invalid: react-native-fbsdk@0.6.1 /Users/honza/Projects/pzrb2b/node_modules/react-native-fbsdk
npm ERR! invalid: react-native-mixpanel@0.0.16 /Users/honza/Projects/pzrb2b/node_modules/react-native-mixpanel
```

Config:

```
Sentry.config('https://...@sentry.io/227024').install();
```

---
I have following issue:

We see folowing error in sentry:
com.facebook.react.bridge.NoSuchKeyException: couldn't find key stacktrace in dynamic object
    at com.facebook.react.bridge.ReadableNativeMap.getMap(ReadableNativeMap.java)
    at io.sentry.RNSentryModule.captureEvent(RNSentryModule.java:246)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:743)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:150)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:833)

In breadcrumbs I see
<img width="984" alt="screen shot 2017-10-27 at 11 54 40" src="https://user-images.githubusercontent.com/1699787/32098660-b00579a6-bb0d-11e7-88f8-73345b28e396.png">

The error is AjaxError from rxjs. It happens only sometimes and we are unable to reproduce. I don't know the internals but it looks to me like sentry is unable to get stacktrace from this exception and crashes. Anyway I looked into Raven.js source and in function `_processException` it's indeed possible for Raven to pass undefined stacktrace to Sentry so it should handle that and do not crash imho.

**Steps to reproduce:**
- Send such exception to sentry, for which TraceKit is unable to capture stacktrace.

**Actual result:**
- Sentry crashes

**Expected result:**
- Sentry doesn't crash

**Comment by HazAT** [comment]
Hey, can you upgrade to `0.30.0` an try again?

**Comment by Zycon42** [comment]
Okay, I'm unable to reproduce it myself, I see it only as crash events in production. I updated and waiting for release. I will let you know if the crashes continue showing up in production.

**Comment by HazAT** [comment]
Ok, I will close this for now.
If you find out something new, feel free to reopen it.
