### ISSUE TITLE
Question: react-native-windows support

### ISSUE THREAD

**Issue by jpshelley** [getsentry/react-native-sentry#291]
OS:
- [X]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [ ]  Android
- [X] Windows

More of a question then an issue:
Will react-native-sentry ever support react-native-windows for UWP apps? If not in the main repo, what about as a third party? Is there steps to take to support it?

From my understanding it will support it by falling back on the pure javascript solution as there is no linking currently, but if there was a way to link the two then we could have hybrid crash reporting across React Native and Native.

Thoughts?

**Comment by HazAT** [comment]
Hey, so currently we have no plans supporting native crashes for Windows.
But like you said, `react-native-sentry` should fallback to use `raven-js` and work out of the box (never tested it though).
In theory, we only need to include native windows crash handling and it should work.
Does this answer your question?

**Comment by jpshelley** [comment]
Definitely, follow up question. If I submitted a PR would Sentry support Windows UWP? I'm unsure if this repo does the native handling, or if thats in a separate private repo.

**Comment by HazAT** [comment]
So we don't support UWP yet, but it shouldn't break anything.
I will discuss it internally what we could do here, I will keep you posted.

**Comment by HazAT** [comment]
I will close this for now since we can't do anything more with this issue.
