### ISSUE TITLE
Question: Sourcemap Support

### ISSUE THREAD

**Issue by jpshelley** [getsentry/react-native-sentry#292]
OS:
- [X]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [ ]  Android
- [X] Windows

Question, not an issue: For whatever reason I cannot get the sourcemaps to upload correctly for my react-native-windows project. Is it a limitation of using react-native-windows?

Does the `upload-sourcemaps` command in the cli supposed to take a bundle and a map file? ie: `index.windows.bundle` and `windows.main.bundle.map`? I was able to get them uploaded to the Sentry Release I created just fine, but my Issue which also has the same release tag cannot be deciphered.

It also still shows:
```
Source code was not found for app:///index.windows.bundle?platform=windows&dev=true&hot=false Collapse
{
  "url": "app:///index.windows.bundle?platform=windows&dev=true&hot=false"
}
```

Thoughts?

**Comment by jpshelley** [comment]
Using --validate shows `- Warning: missing sourcecode ...` too

**Comment by HazAT** [comment]
So there currently is a bug when uploading sourcemaps in debug mode see:
https://github.com/getsentry/react-native-sentry/issues/294
This might be related, I will take a look at this.

**Comment by jpshelley** [comment]
I was finally able to get it working, the final command was something akin to:
```
sentry-cli releases files $RELEASE upload-sourcemaps --dist $DIST --strip-prefix $CHECKOUT_DIR --rewrite --validate $CHECKOUT_DIR\index.windows.bundle $CHECKOUT_DIR\index.windows.bundle.map
```

and when I generated my sourcemap I needed to make sure the following was run:
```
node node_modules/react-native/local-cli/cli.js bundle --platform windows --entry-file index.windows.js --bundle-output index.windows.bundle --assets-dest windows/MyApp/ReactAssets --dev false --sourcemap-output index.windows.bundle.map --sourcemap-sources-root ./
```

the key part was the `sourcemap-sources-root ./` which might have been because of the way my project was setup with all of the source files/folders being at the root of the project

**Comment by HazAT** [comment]
Thanks, so I will close this for now.
