### ISSUE TITLE
iOS: NSString(s) are not getting deallocating

### ISSUE THREAD

**Issue by jdzak** [getsentry/react-native-sentry#293]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
➜  tend-rn git:(jd-fix_visit_clock_in) ✗ node -v && npm -v && npm ls --prod --depth=0
v8.5.0
5.3.0
TendRN@0.0.1 /Users/tablexi/Code/tend-rn
├── @storybook/addon-storyshots@3.2.8
├── UNMET PEER DEPENDENCY @storybook/addons@3.1.6
├── UNMET PEER DEPENDENCY @storybook/channels@3.1.6
├── deep-equal@1.0.1
├── enzyme@2.8.2
├── humps@2.0.1
├── js-joda@1.5.2
├── UNMET PEER DEPENDENCY react@15.4.2
├── react-native@0.42.3
├── react-native-actionsheet@2.1.0
├── react-native-calendar@0.12.3
├── react-native-communications@2.2.1
├── react-native-fabric@0.4.1
├── react-native-fabric-crashlytics@0.1.8
├── react-native-fetch-blob@0.10.8
├── react-native-gifted-chat@0.1.5
├── react-native-image-picker@0.26.3
├── react-native-img-cache@1.4.0
├── react-native-keyboard-aware-scroll-view@0.2.9
├── react-native-modal-datetime-picker@4.8.0
├── react-native-sentry@0.6.0
├── react-native-swipeout@2.1.1
├── react-native-vector-icons@4.1.1
├── react-redux@5.0.4
├── redux@3.6.0
└── redux-saga@0.14.6

npm ERR! peer dep missing: @storybook/addons@^3.2.6, required by @storybook/addon-storyshots@3.2.8
npm ERR! peer dep missing: @storybook/channels@^3.2.0, required by @storybook/addon-storyshots@3.2.8
npm ERR! peer dep missing: react@^15.5.4, required by react-dom@15.5.4
npm ERR! peer dep missing: react@^15.5.0, required by react-test-renderer@15.5.4
npm ERR! missing: react-native-lightbox@github:oblador/react-native-lightbox#c84a8543d4511fe6a44c3d7820747c9c1bddd875, required by react-native-gifted-chat@0.1.5
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
      deactivateStacktraceMerging: true,
      logLevel: SentryLog.Debug,
}).install()
```

---
I have the following issue:

When I log anything, there are NSString(s) being allocated but not deallocated resulting in a memory leak. In my app, I'm logging redux state changes that are pretty large and this amplifies the memory leak.

**Steps to reproduce:**
- Create a project with just react-native-sentry and something to trigger sentry logging
- Attach the iOS allocation instrument to watch allocations/deallocations
- Trigger a bunch of logging

**Actual result:**
- See NSString objects are allocated but not deallocated

**Expected result:**
- See NSString are allocated and deallocated

**Comment by HazAT** [comment]
Thank you for reporting this, I will fix this.

**Comment by HazAT** [comment]
Hey, so I was trying to reproduce this.
I can confirm that the memory is slowly rising when triggering many logs, though I am not sure if Sentry is responsible for this.
I haven't found and memory leaks or anything, I suspect react-native itself is caching some stuff internally and may free memory if needed.
So I will close this for now, if you are able to point me to the code that "leaks" I will fix it.

**Comment by HazAT** [comment]
For more context:
<img width="917" alt="screenshot 2017-11-21 15 16 30" src="https://user-images.githubusercontent.com/363802/33077073-0729c672-cecf-11e7-9d09-ddb1785ae5e4.png">

**Comment by jdzak** [comment]
Sounds good, I'll see if I can narrow down the problem a little more. Thanks for investigating.
