### ISSUE TITLE
Adding this causes code signing errors

### ISSUE THREAD

**Issue by robbiet480** [getsentry/react-native-sentry#3]
After adding this I can no longer build my project. Xcode throws an error that looks like this:

![Xcode build error](https://i.stack.imgur.com/75WRH.png)

Removing react-native-sentry from my project fixes builds.

Been tearing my hair out for 3 hours now on this as I didn't cleanly add Sentry the first time. Tried clicking around to figure out what would be causing it. Nothing I tried (setting code signing identity or code signing RNSentry.h on copy) has fixed it.

**Comment by mitsuhiko** [comment]
We are looking for a better way to do this but for now you can solve this issue by going to the react-native sentry frameworks and enabling code signing in xcode (needs to be done for the sentry framework and kscrash one).

Alternatively you can remove the copy build step (`cp -r ...`) for the two frameworks and add the frameworks (kscrash and sentry) as embedded binaries (note that there are currently two similarly named kscrash frameworks and only one will do the trick).

**Comment by mitsuhiko** [comment]
We added a script now that does this better. If you upgrade to a new version of `react-native-sentry` you can add this script to your build step instead:

```
../node_modules/react-native-sentry/bin/bundle-frameworks
```

This replaces the previous `cp` calls.

**Comment by Gp2mv3** [comment]
I still have this issue. Is it really closed ?
I tried versions 0.5.2 and 0.6.0.
I checked multiple times the Code Signing Identities and those are set to be signed...

**Comment by mitsuhiko** [comment]
@Gp2mv3 did you add the bundle-frameworks script into your project?

**Comment by Gp2mv3** [comment]
Yes...

**Comment by mitsuhiko** [comment]
@Gp2mv3 did you try making a clean build? Can you paste your build and run log?

**Comment by Gp2mv3** [comment]
Here is the full build log (from Xcode).

[buildXCodeLog.txt](https://github.com/getsentry/react-native-sentry/files/894223/buildXCodeLog.txt)

**Comment by mitsuhiko** [comment]
Can you add `set -x` as first line to your build step that invokes `bundle-frameworks` and then paste again? The build log does not spit out the command execution.

**Comment by Gp2mv3** [comment]
Here you are.
But really weird, when I search for sentry, I don't find anything in the log...

[buildXCodeLog.txt](https://github.com/getsentry/react-native-sentry/files/894257/buildXCodeLog.txt)

**Comment by mitsuhiko** [comment]
It does not look like your build step is being executed. Can you double check you added the build step correctly as mentioned in the docs?

**Comment by Gp2mv3** [comment]
It seems to be there. But I agree it's not executed... Do I have something to do in addition to putting the script there ?

![buildsteppng](https://cloud.githubusercontent.com/assets/1221806/24675269/ca49f9c6-197e-11e7-8b6d-f8ae301757e5.png)

**Comment by Gp2mv3** [comment]
Hi I have a new input about this issue. It cannot work with the script as this error is triggered at compilation and the script is supposed to run after compilation and link.
The error comes from the compilation of dependencies of the project.

The only solution I found was to set the signing to every component by hands...

**Comment by farhansalam** [comment]
@Gp2mv3 I am having the same problem, can you please tell me how you fixed it?
