### ISSUE TITLE
Can't load TypeScript definitions

### ISSUE THREAD

**Issue by itchingpixels** [getsentry/react-native-sentry#301]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [X]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.9.0
5.5.1
```

Config:

```
Sentry.config('https://...@sentry.io/...', {}).install()
```

---
I have following issue:

Typescript definitions won't load

**Steps to reproduce:**
- `yarn add react-native-sentry`
- `import Sentry from 'react-native-sentry'`

**Actual result:**
- `Could not find a declaration file for module 'react-native-sentry'. '/node_modules/react-native-sentry/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-sentry` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-sentry';``

**Expected result:**
- Be able to use the bundled typescript definitions

**Comment by HazAT** [comment]
Version `0.32.0` has been released which should fix this issue.
