### ISSUE TITLE
Some device is "iPhone10,x" or "iPhone9,x"

### ISSUE THREAD

**Issue by KkkkKernc** [getsentry/react-native-sentry#308]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v6.11.2
3.10.10
```

Config:

```
Sentry.config('https://...@sentry.io/...').install()
```
---
I have following issue:

I found that some issue's device is "iPhone10,x" or "iPhone9,x", it's weird, as we known they don't have those devices. Screenshot:
![image](https://user-images.githubusercontent.com/6129982/33466199-5ccb11e8-d687-11e7-8313-b031a9637d34.png)

**Comment by HazAT** [comment]
Hey, thank you for reporting!
We have to update our device -> name mapping library since there are new devices.
Will close this once it's done.
