### ISSUE TITLE
Android :  Sentry.nativeCrash

### ISSUE THREAD

**Issue by songxiaoliang** [getsentry/react-native-sentry#309]
Call sentry.nativeCrash method to crash the App, but can not receive error statistics, in the ios is normal

**Comment by HazAT** [comment]
Is the native integration running on Android?
Can you link me to another android event so I can take a look it?

**Comment by songxiaoliang** [comment]
@HazAT Solve the problem, can not be submitted to the error on the simulator, but in the real machine is ok.
