### ISSUE TITLE
Logs In Release Mode

### ISSUE THREAD

**Issue by edo1493** [getsentry/react-native-sentry#31]
Hi guys! 

I was just wondering if you were printing out some logs in Release mode without knowing. We have just had someone who came up with this stuff (below) in our App, which is live on the App Store. 

```
{"timestamp":,"type":"http","category":"fetch","data":{"method":"GET","url":"","status_code":200}}
{"timestamp":,"type":"http","category":"xhr","data":{"method":"GET","url":"","status_code":200}}
{"timestamp":,"type":"http","category":"fetch","data":{"method":"POST","url":"","status_code":422}}
{"timestamp":,"type":"http","category":"xhr","data":{"method":"POST","url":"","status_code":422}}]},"event_id":""}

```

From this conversation (https://github.com/getsentry/sentry/issues/2632), this seems to be a stacktrace from raven-js; but I have no idea where it comes from and how to read it.

**Comment by HazAT** [comment]
Do you have set `logLevel: SentryLog.Debug`?

**Comment by edo1493** [comment]
I only have: 

Sentry.config(sentry, {
  deactivateStacktraceMerging: true
}).install();

Do I need to specify not to log in prod?

**Comment by HazAT** [comment]
nope ... will check that

**Comment by edo1493** [comment]
@HazAT is there a way I can reach you in private?

**Comment by HazAT** [comment]
daniel@sentry.io

**Comment by HazAT** [comment]
Update to latest version `0.6.0` should fix the problem
