### ISSUE TITLE
How to configure it on our own Sentry server?

### ISSUE THREAD

**Issue by XHTeng** [getsentry/react-native-sentry#311]
OS:
- [ ]  Windows
-  MacOS
- [ ]  Linux

_Platform:_
- iOS
- [ ]  Android

When I execute the `npm link react-native-sentry` , just can only jump to sentry.io .If our own Sentry service address is http://123.287.234.548:9000/  , how to configure it ?

**Comment by HazAT** [comment]
Hey,
you can call `SENTRY_WIZARD_URL=http://123.287.234.548:9000/ npm link react-native-sentry`
if your installation doesn't support this yet, we fall back to asking you stuff.

**Comment by padupuy** [comment]
@HazAT this information `SENTRY_WIZARD_URL` is really useful for self hosted sentry instance, could you update the doc ?

**Comment by arelstone** [comment]
It would be nice if this was mentioned in the documentation for setting up

**Comment by cwilby** [comment]
https://github.com/getsentry/sentry-react-native/pull/736

**Comment by HazAT** [comment]
It's in the readme now
