### ISSUE TITLE
 > Checking for missing debug symbol files on server  --->  error: http error:  (404) 

### ISSUE THREAD

**Issue by songxiaoliang** [getsentry/react-native-sentry#312]
Run the project on the iOS simulator with the following error：

----------------------------------------------------------------
> Found 1 debug symbol files.

> Checking for missing debug symbol files on server

error: http error:  (404)

** BUILD FAILED **

The following build commands failed:
        PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry build/Build/Intermediates.noindex/uniApp.build/Debug-iphonesimulator/uniApp.build/Script-1C46DC39377443AF91420C3A.sh
(1 failure)

----------------------------------------------------------------

Last week was normal.
Look forward to the author reply as soon as possible.

**Comment by HazAT** [comment]
Hey,

Can you please post the content of your `sentry.properties` file?

**Comment by songxiaoliang** [comment]
ok，this is my sentry.properties:

defaults.url=https://sentry.io/
defaults.org=uniqueway
defaults.project=rn-uniapp
auth.token=xxxxxxxxxxxxxxxxxxxxxxxxx
cli.executable=node_modules/sentry-cli-binary/bin/sentry-cli

Look forward to the author reply as soon as possible.

**Comment by HazAT** [comment]
So you project is wrong as far as I can tell. 
It should be just `uniapp`.

**Comment by songxiaoliang** [comment]
thank you !
