### ISSUE TITLE
Fatal error: 'React/RNSentry.h' file not found

### ISSUE THREAD

**Issue by mounlion** [getsentry/react-native-sentry#317]
OS: MacOS
Platform:  iOS

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.9.3
5.5.1
├── @yfuks/react-native-action-sheet@0.0.4
├── native-base@2.3.3
├── react@16.0.0
├── react-native@0.51.0
├── react-native-cookies@3.2.0
├── react-native-device-info@0.10.2
├── react-native-google-analytics@1.3.2
├── react-native-google-analytics-bridge@5.4.1
├── react-native-htmlview@0.12.1
├── react-native-image-picker@0.26.7
├── react-native-image-progress@1.0.1
├── react-native-maps@0.19.0
├── react-native-permissions@0.2.7
├── react-native-photo-view@1.5.2
├── react-native-router-flux@4.0.0-beta.24
├── react-native-segmented-control-tab@3.2.1
├── react-native-sentry@0.32.0
├── react-native-share@1.0.23
├── react-native-store-review@0.1.3
├── react-native-vector-icons@4.4.2
├── react-redux@5.0.6
├── react-static-container@1.0.2
├── redux@3.6.0
├── redux-actions@1.2.1
├── redux-logger@2.8.1
└── redux-thunk@2.2.0
```

Config:

```
Sentry.config('****').install();
```

---
I have following issue:

Description goes here ...

**Steps to reproduce:**
- create new project
- npm install react-native-sentry --save &&  react-native link react-native-sentry
- reatc-native run-ios

**Actual result:**
- fatal error: 'React/RNSentry.h' file not found
#import <React/RNSentry.h>

**Comment by mounlion** [comment]
I solved problem. Manual link binary lib&

**Comment by pcooney10** [comment]
When doing `react-native link react-native-sentry`, a `SentryReactNative` pod gets added to my Podfile. I was also experiencing this issue when importing `<React/RNSentry.h>`, but seem to have resolved it by importing `<SentryReactNative/RNSentry.h>` instead.

**Comment by joaom182** [comment]
You must run manually on `ios` folder `pod repo update && pod install`

**Comment by antoinerousseau** [comment]
Why is [the doc](https://docs.sentry.io/clients/react-native/manual-setup/) saying `<React/RNSentry.h>` when it should be `<SentryReactNative/RNSentry.h>`? Is it an error? Or is it CocoaPods or Xcode specific? @HazAT
