### ISSUE TITLE
Link without modify podfile and ignore sentry wizard. 

### ISSUE THREAD

**Issue by thphu** [getsentry/react-native-sentry#318]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v6.9.5
3.10.10
EHLife@1.17.1-sentry /Users/phutang/workspace/eh-mobile-pro
├── @expo/ex-navigation@3.1.0 invalid
├── @remobile/react-native-splashscreen@1.0.8
├── babel-polyfill@6.26.0
├── bluebird@3.5.1
├── date-fns@1.29.0
├── es6-symbol@3.1.1
├── faker@4.1.0
├── getstorybook@1.7.0
├── global@4.3.2
├── hoothoot@0.0.10
├── lodash@4.17.4
├── lottie-react-native@2.2.0
├── moment@2.19.4
├── node-emoji@1.5.1
├── node-inspector@0.12.10
├── node-uuid@1.4.7
├── prop-types@15.6.0
├── pusher-js@4.1.0
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.12
├── react-dom@16.0.0-alpha.12
├── UNMET PEER DEPENDENCY react-native@0.51.0
├── react-native-collapsible@0.9.0
├── react-native-communications@2.2.1
├── react-native-config@0.9.1
├── react-native-controlled-listview@0.1.0
├── react-native-drawer@2.3.0
├── react-native-fcm@10.0.3
├── react-native-fetch-blob@0.10.8
├── react-native-google-analytics-bridge@5.2.2
├── react-native-infinite-scroll-view@0.4.2
├── react-native-interactable@0.1.7
├── react-native-keyboard-aware-scroll-view@0.3.0
├── react-native-keyboard-spacer@0.4.1
├── react-native-material-kit@0.5.1 invalid
├── react-native-md-textinput@2.0.5 invalid
├── react-native-mixpanel@0.0.15
├── react-native-pdf-view@0.4.0 invalid
├── react-native-photo-view@1.5.2
├── react-native-sentry@0.32.0
├── react-native-share@1.0.23
├── react-native-simple-modal@5.1.1
├── react-native-svg@5.5.1
├── react-native-tab-view@0.0.70
├── react-native-vector-icons@4.4.2
├── react-redux@5.0.3
├── recompose@0.22.0
├── redux@3.6.0
├── redux-actions@2.0.1
├── redux-api-call@0.3.16
├── redux-batched-actions@0.1.6
├── redux-form@6.5.0
├── redux-ignore@1.2.4
├── redux-observable@0.14.1
├── redux-state-action@1.0.7
├── redux-thunk@2.2.0
├── reselect@2.5.4
├── rxjs@5.5.5
└── victory-native@0.16.0
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
Hi,

I'm trying to upgrade sentry from deprecated version. But I'm facing 3 problesm at this time. 
 - Sentry Wizard keep asking me everytime when I run `yarn` and modify my my native code. Is there any way to avoid it?
 - you add `pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'`, to podfile. The problem is it's clone another version (react/yoga, etc) and can't load bundle because of duplicate package json from react. is there any way to setup with you add this pod (like link ios project like other 3rd libraries instead of link by pod?)
- I have 2 config, one for staging, one for production. Is it possible to config setting point to staging sentry project and production sentry project (the old version I just simply name the config in ENV, I already have for 2 difference projects for staging and production).

**Comment by Titozzz** [comment]
Same Problem

**Comment by HazAT** [comment]
Hey, just to clear things up.

1. The wizard always asks you stuff even if you just do `yarn` and not `react-native link react-native-sentry`? If that's the case then it's a bug.

2. Not really sure if I fully understand the problem. `react-native-sentry` does not clone a version of yoga or react so I don't understand why it should be duplicate see:
https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies

3. So we do not fully support this yet and we recommend setting a tag env with 
```
Sentry.setTagsContext({
  "environment": "production",
});
```

With this, you can filter incoming events easily and do not have to submit a new build if you want to release it in iTunes Connect.

**Comment by thphu** [comment]
Hi @HazAT 

1. Please check attached file. How about if it's disabled by some flag or command?
2. I know the integration guide, but our project j 100% react-native and I linked library by manual (add in xcode), the problem if moving to pod (add project as a pod module) is a lot of things to do like moving react from node_module to pod and other project, I just want to link it like manual way (or react-native 0.4x way) I do manual but it modify and modify by the wizard eveytime I run `yarn`
3. Agree with you, I will update code. 

![dec-28-2017 09-52-45](https://user-images.githubusercontent.com/7285771/34398886-0497b5f6-ebb5-11e7-8d50-e1c7c7108cf8.gif)

**Comment by thphu** [comment]
Update: about pod issue (no2 issue), I found a way to work around. Downgrade to 0.49 then add library then upgrade again to 0.51. It's not add podfile anymore.

**Comment by HazAT** [comment]
@thphu There is a link step running in your `install` script ... do you see the first grey line starting with:
`RNFB_ANDROID_PERMISSION=true ....` ?
The command called in there is `.... index.js link`

So your build process is definitely special, check your package.json for the install/link command.
If you can't change it you can try to add 
`SENTRY_WIZARD_QUIET=true` so the wizard will not ask anything.

**Comment by thphu** [comment]
thanks @HazAT I add SENTRY_WIZARD_QUIET=true and seem eveything is ok now. I think it's not an issue anymore
