### ISSUE TITLE
Debug symbol upload failed

### ISSUE THREAD

**Issue by XHTeng** [getsentry/react-native-sentry#319]
OS:
- [ ]  Windows
- MacOS
- [ ]  Linux

_Platform:_
- iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.9.1
5.5.1
/Users/sean
└── (empty)
```

Config:

```
Sentry.config('http://2336ee6847934d6fcc61d9614bbbb939:e3156280dcd54d1c9693b377c842ea7e@123.11.81.121:9000/9').install();
```

---
I have following issue:

When I run Xcode , I get the warning 
![image](https://user-images.githubusercontent.com/17663111/34397587-38bac2f4-ebb2-11e7-84af-92253f962e89.png)

I click the Show Details , I get the follow info : 
![image](https://user-images.githubusercontent.com/17663111/34397601-5e624644-ebb2-11e7-90dd-79bc633ff672.png)

I'm sure my sentry.properties is correct , I have any wrong operation?

**Comment by HazAT** [comment]
Which version of Sentry are you running?

**Comment by ngandhy** [comment]
0.29 for me

**Comment by XHTeng** [comment]
"react-native-sentry": "^0.32.0",

**Comment by HazAT** [comment]
Are you running your own version of Sentry Server, not sentry-react-native.
If so please post the version.
cc @XHTeng @ngandhy

**Comment by XHTeng** [comment]
Sentry 8.22.0
http://123.206.79.148:9000/lkker/
@HazAT

**Comment by HazAT** [comment]
Hey, so there "must" be an issue with your installation.
Either a proxy or some webserver setting is blocking this large request.
It's hard to debug, you can run the command with `SENTRY_LOG_LEVEL=info` to get more output.
