### ISSUE TITLE
iOS: No visible @interface for 'SentryClient'

### ISSUE THREAD

**Issue by Gp2mv3** [getsentry/react-native-sentry#32]
Hi guys,
After adding the plugin to my app, I receive this error at build:
```
node_modules/react-native-sentry/ios/RNSentry.m:239:28: No visible @interface for 'SentryClient' declares the selector 'reportReactNativeCrashWithError:stacktrace:terminateProgram:'
node_modules/react-native-sentry/ios/RNSentry.m:249:32: No visible @interface for 'SentryClient' declares the selector 'reportReactNativeCrashWithError:stacktrace:terminateProgram:'
```

I'm building with target 9.3 and had issues with the Signing for Framework (which is now solved).

Do you have a solution ?

Thanks !

**Comment by HazAT** [comment]
Hey, did you change anything in `RNSentry.m` this error seems weird.
Also did you make sure you did everything stated here? https://docs.sentry.io/clients/react-native/#xcode-build-settings

**Comment by Gp2mv3** [comment]
Yes I followed this (which doesn't help much for the Signin error though... see issue #3 ).
I only commented those two lines to continue working...

Where is SentryClient defined normally ?

**Comment by HazAT** [comment]
It's located here (see screenshot), but there is something funky with your build process. The swift file should generate a `Sentry-Swift.h` which should contain 
```
- (void)reportReactNativeCrashWithError:(NSError * _Nonnull)error stacktrace:(NSArray * _Nonnull)stacktrace terminateProgram:(BOOL)terminateProgram;
```
<img width="885" alt="sentry_swift" src="https://cloud.githubusercontent.com/assets/363802/24873291/1ff85e62-1dd5-11e7-8c45-3bf6f1bd0e32.png">

**Comment by Gp2mv3** [comment]
Here is my build log with the error.
I don't change anything except what's in the link you sent before...
[log.txt](https://github.com/getsentry/react-native-sentry/files/910864/log.txt)

**Comment by neilakoh** [comment]
Install/Uninstall package many times then install/uninstall Pods many times (including removing Podfile.lock and package.lock) then clean xcode many times and then restart mac many times . . NOTHING WORKED . .

So decided to bump down the version from Sentry 2.0.0 to 1.8.2

and it worked! Finally, build successfully...

**Comment by gebsl** [comment]
@neilakoh thanks for the hint! Version 2.0.0 didn't work but after downgrading to 1.9.0 it worked flawlessly.

**Comment by todorone** [comment]
@gebsl @neilakoh No need to downgrade, please look this comment for workaround - https://github.com/getsentry/sentry-react-native/issues/1186#issuecomment-725745836

**Comment by neilakoh** [comment]
@todorone - yes it worked and it said "**_This is probably the cleanest workaround until whatever is wrong is fixed._**". I will just wait for that fix since I want to avoid workarounds as much as possible.

**Comment by muratozgul** [comment]
Upgrading to 2.0.2 seems to fix it.
(I deleted node_modules and Podfile.lock and installed everything again, just to be safe)

**Comment by messycoding** [comment]
This also works while using version 2.0.0

https://github.com/getsentry/sentry-react-native/issues/1186#issuecomment-725745836
