### ISSUE TITLE
error: failed to invoke sentry-cli

### ISSUE THREAD

**Issue by kdong007** [getsentry/react-native-sentry#323]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

v8.9.3
5.5.1
ReactNativeApp@0.0.1 /Users/kdong/react-native-app
├── apollo-cache-inmemory@1.1.4
├── apollo-client@2.0.4
├── apollo-link@1.0.6
├── apollo-link-error@1.0.3
├── apollo-link-http@1.3.1
├── apollo-link-logger@1.1.0
├── appcenter@1.1.0
├── appcenter-analytics@1.1.0
├── coordtransform@2.1.2
├── d3@4.12.0
├── d3-shape@1.2.0
├── dateformat@3.0.2
├── graphql@0.11.7
├── graphql-tag@2.6.0
├── lodash@4.17.4
├── node-fetch@1.7.3
├── prop-types@15.6.0
├── UNMET PEER DEPENDENCY react@16.2.0
├── react-apollo@2.0.4
├── react-apollo-temp@2.0.2
├── react-native@0.51.0
├── react-native-animatable@1.2.4
├── react-native-code-push@5.2.1
├── react-native-collapsible@0.9.0
├── react-native-device-info@0.13.0
├── react-native-flurry-analytics@3.0.1
├── react-native-keychain@2.0.0-rc
├── react-native-linear-gradient@2.4.0
├── react-native-maps@0.18.3
├── react-native-material-textfield@0.11.0
├── react-native-mixpanel@0.0.16
├── react-native-phone-call@1.0.4
├── react-native-sentry@0.32.0
├── react-native-shimmer@0.3.2
├── react-native-splash-screen@3.0.6
├── react-native-swiper@1.5.13
├── react-native-tab-view@0.0.69
├── react-native-vector-icons@4.4.2
├── react-navigation@1.0.0-beta.15 invalid
├── react-redux@5.0.6
├── react-style-proptype@3.1.0
├── redux@3.7.2
├── redux-state-change-listener@0.1.6
└── redux-thunk@2.2.0

I got this when building in Xcode 

error: failed to invoke sentry-cli
Error: spawn /Users/kdong/react-native-app/node_modules/@sentry/cli/sentry-cli ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by HazAT** [comment]
Hey, can you check your node_modules folder if there is are these folders?
```
@sentry
├--- cli
└--- wizard
```
Did you install `react-native-sentry` with `yarn` or with `npm`?

**Comment by magrinj** [comment]
@HazAT I have the same problem, I install this package with yarn, this one doesn't rename "sentry-cli-binary" folder to "@sentry" in node_modules, it works with npm

**Comment by HazAT** [comment]
Can you please completely remove the `node_modules` folder clear your npm cache and make a fresh clean install?

**Comment by magrinj** [comment]
I already done it, this package works great when the installation is made from npm, but not when yarn is used, because as I say with yarn the directory "sentry-cli-binary" is not renamed in "@sentry"

**Comment by HazAT** [comment]
what version of yarn are you running?
And did you remove the yarn lockfile and cleaned the yarn cache?

**Comment by magrinj** [comment]
I use yarn v0.20.3
I just try to remove the cache, it works, it seams to be the problem :) Thanks!

**Comment by HazAT** [comment]
OK, I suppose @kdong007 will have the same problem.
I am closing this for now.

**Comment by kcfgl** [comment]
@HazAT So I'm hitting this same issue after upgrading to 0.46.0, react-native-sentry@0.34.0.  Using yarn. I've tried all the steps mentioned above, clearing cache, etc.

I'm on RN 46.1

I have an @sentry folder in node_modules. IN my build phases I added this (from another thread)
```
export SENTRY_PROPERTIES=sentry.properties
export NODE_BINARY=node
../node_modules/sentry-cli-binary/cli/bin/sentry-cli react-native xcode \
../node_modules/react-native/scripts/react-native-xcode.sh
```
I cant move forward until I get this solved.  Any additional thoughts on the issue?  Things to try?  Thanks!

**Comment by mmeylan** [comment]
We had this error in CI because we install dependencies with `npm ci --ignore-scripts` and sentry depends on an install time script to setup the binary.

**Comment by mohity777** [comment]
Any update ??? i am facing this issue

**Comment by Asleepace** [comment]
We were facing the same issue with our mono-repo, in the end it was also the `--ignore-scripts` issue, since we also use a mono-repo the solution became something like this:

```
yarn --ignore-scripts
cd example/ios
pod instsall
cd ../..
rm -rf node_modules
yarn
```
and also clearing the packager might have helped
```
rm -rf $TMPDIR/react-*; rm -rf $TMPDIR/haste-*; rm -rf $TMPDIR/metro-*; watchman watch-del-all; react-native start -- --reset-cache;
```
