### ISSUE TITLE
Manually send stored events

### ISSUE THREAD

**Issue by adbl** [getsentry/react-native-sentry#324]
_Platform:_
- [x]  iOS
- [ ]  Android ?

Sorry for ignoring the rest of issue template but this is more of a question/feature request.

Before trying out Sentry, we had our own global js error handler (using `ErrorUtils`). This provided us with some clues as to what went wrong, but we also used this to present a user friendy error popup + reloading the JS. Maybe this is unusual, but actually an upside of using React Native is that we can prevent crashes from killing the app, the app just disappearing on iOS can be pretty confusing. Another upside to this is that we are able to report JS errors directly when they occur and not when the app is launched the next time, which may not happen at all.

With Sentry we can get js stack traces 🙏 and other nice things. But we would like to keep our global handler which stops the app from getting killed, _after_ sentry has captured the error. This worked nicely, but the error doesn't get reported until the next app launch, bummer.

Here are some ideas that I would like to get feedback on, if we land on something good, we are willing to PR this:

- Avoid Sentry error global handler, and instead use `Sentry.captureException` in our own error handler. This might be accomplished by overwriting Sentry with our own handler after calling `Sentry.install`
  * but would we still get the same information in the report?
- Or, we could install our own handler before `Sentry.install`, so it runs after, and add to the JS bridge an option to call `[SentryClient sendAllEvents]` (https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryClient.m#L240)
  * would this work? I see something about `_internalEventStored` callback getting called after the event has been stored...

**Comment by HazAT** [comment]
So about Sentry sending it only after the next app launch.
Actually, it would send it whenever the next event was successfully sent, so if you send a message with `captureMessage` you should see the crash afterward. Can you try this if that works?

I know it means one additional event you could inbound filter it or something to it will be ignored.

**Comment by adbl** [comment]
Ok, interesting, will try that!

Right now though, I’m leaning towards overwrite sentry error handler and
use captureException. This should also make it possible to report two
errors which happen very close in time. Would we sacrifice anything by not
using Sentry error handler?

**Comment by HazAT** [comment]
No not really we are basically just calling `captureException` ourselves. 
Still, if it's an "exception" / fatal error we store it instead of sending it since the usual case is that react-native let the app crash, so you still would need to call something with `captureMessage` to get it instantly.

**Comment by HazAT** [comment]
I will close this issue for now since we not gonna change anything regarding this in the future.
Feel free to post again if you need further assistance.
