### ISSUE TITLE
Invalid Code Signing Entitlements on upload to App Store

### ISSUE THREAD

**Issue by joerick** [getsentry/react-native-sentry#34]
I'm getting the following error when submitting our app to App Store.

> [13:40:26]: [Transporter Error Output]: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'DQ40000PR5.com.parktechnology.tapp' for key 'application-identifier' in 'Payload/tapp-app.app/Frameworks/KSCrash.framework/KSCrash' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."
> [13:40:26]: [Transporter Error Output]: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'DQ40000PR5.com.parktechnology.tapp' for key 'application-identifier' in 'Payload/tapp-app.app/Frameworks/Sentry.framework/Sentry' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."
> [13:40:26]: Transporter transfer failed.
> [13:40:26]: 
> [13:40:26]: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'DQ40000PR5.com.parktechnology.tapp' for key 'application-identifier' in 'Payload/tapp-app.app/Frameworks/KSCrash.framework/KSCrash' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."
> ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'DQ40000PR5.com.parktechnology.tapp' for key 'application-identifier' in 'Payload/tapp-app.app/Frameworks/Sentry.framework/Sentry' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."
> [13:40:26]: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'DQ40000PR5.com.parktechnology.tapp' for key 'application-identifier' in 'Payload/tapp-app.app/Frameworks/KSCrash.framework/KSCrash' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."
> ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'DQ40000PR5.com.parktechnology.tapp' for key 'application-identifier' in 'Payload/tapp-app.app/Frameworks/Sentry.framework/Sentry' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."
> Return status of iTunes Transporter was 1: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'DQ40000PR5.com.parktechnology.tapp' for key 'application-identifier' in 'Payload/tapp-app.app/Frameworks/KSCrash.framework/KSCrash' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifie\nERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'DQ40000PR5.com.parktechnology.tapp' for key 'application-identifier' in 'Payload/tapp-app.app/Frameworks/Sentry.framework/Sentry' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."

I'm wondering if this is due to how the libraries get linked in with `bundle-frameworks`. I'm using manual code signing rather than Xcode automatic.

Strangely, `DQ40000PR5` is our team ID and `com.parktechnology.tapp` is our App ID. So the error message doesn't make much sense!

**Comment by mitsuhiko** [comment]
Does this still happen?

**Comment by joerick** [comment]
This was on v0.6.0 - I've not tested on v0.7.0, but I'll check that on Monday.

**Comment by joerick** [comment]
Managed to fix this... not by 0.7.0, but by changing our build script to do the newer export method with `xcodebuild`.

For future reference, that was this change in our Makefile:

```diff
-	xcodebuild -project $(PROJECT) \
-	           -exportArchive \
-	           -exportFormat ipa \
-	           -archivePath "build/ios/Tapp.xcarchive" \
-	           -exportPath "build/ios/Tapp.ipa" \
-	           -exportProvisioningProfile "match AppStore com.parktechnology.tapp"
+	xcodebuild -exportArchive \
+	           -exportOptionsPlist $(EXPORT_PLIST) \
+	           -archivePath "build/ios/Tapp.xcarchive" \
+	           -exportPath "build/ios/"
```

Cheers!

**Comment by chakri3130** [comment]
@joerick  
This is the steps we are following, But I am facing an issue, Please suggest me how to resolve this.
Step1:In  Buildphases Added a new script 
Step2: Copied the code suggested by you and changes the archive path(prefrences->location-> archeive path)
Step3: Build my project , Getting this error. 

line 2: EXPORT_PLIST: command not found
xcodebuild: error: The flag -archivePath is required when specifying -exportArchive.
Command /bin/sh failed with exit code 64
Please help me out this.
Thanks in Advance.

**Comment by joerick** [comment]
Hi there, the code posted above was from a makefile outside of the Xcode project, not in a build step. 

EXPORT_PLIST is a variable from that makefile, check xcodebuild docs for info on the -exportOptionsPlist option.
