### ISSUE TITLE
Unhandled JS Exception: undefined is not an object (evaluating 'e.construct...

### ISSUE THREAD

**Issue by m-vdb** [getsentry/react-native-sentry#342]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v6.11.2
5.3.0
myproject@0.8.2 /Users/mvdb/Sources/myproject
├── lodash@4.17.4
├── moment@2.19.2
├── prop-types@15.6.0
├── qs@6.5.1
├── react@16.2.0
├── react-instantsearch@4.2.0
├── react-native@0.52.2
├── react-native-android-notification-permission@1.0.1
├── react-native-app-settings@2.0.0
├── react-native-calendar-strip@1.2.4
├── react-native-config@0.11.5
├── react-native-device-info@0.12.1
├── react-native-fabric@0.5.1
├── react-native-fbsdk@0.6.3
├── react-native-infinite-scroll-view@0.4.3
├── react-native-message-bar@2.0.6
├── react-native-modal-datetime-picker@4.13.0
├── react-native-parsed-text@0.0.20
├── react-native-push-notification@3.0.2
├── react-native-router-flux@4.0.0-beta.24
├── react-native-sentry@0.30.2
├── react-native-snap-carousel@3.4.0
├── react-native-splash-screen@3.0.6
├── react-native-store-view@3.1.0
├── react-native-swipeout@2.3.1
├── react-native-vector-icons@4.4.2
└── realm@1.13.0
```

Config:

```
Sentry.config(Config.SENTRY_DSN, {}).install()
```

---
I have following issue:

When calling `Sentry.config()` with an undefined `dsn`, it will crash with the `Unhandled JS Exception: undefined is not an object (evaluating 'e.construct...`. It is not an issue in debug configuration, since it is easy to read the stacktrace, but in release configuration it is a bit cryptic, since the backtrace is totally minified and it is hard to know where it comes from:
```
Unhandled JS Exception: undefined is not an object (evaluating 'e.construct..., stack:
config@307:921
<unknown>@305:6588
d@2:755
<unknown>@12:55
d@2:755
n@2:326
global code@939:8
```

I was able to narrow it down to the call to `config()` [here](https://github.com/getsentry/react-native-sentry/blob/3decdccd53e657ce443cebb16454eb17abf673f3/lib/Sentry.js#L52) by using a stack beautifier. (I spent some time trying to figure out why my build failed on TestFlight...).

It is rather easy to fix, we could just check for `null` and `undefined` too.

**Steps to reproduce:**
`Sentry.config(undefined, {}).install()`

**Actual result:**
`Unhandled JS Exception: undefined is not an object (evaluating 'dsn.construct...`

**Expected result:**
`Sentry: A DSN must be provided`

**Comment by HazAT** [comment]
So the problem here is that we need it to be a string and we actually want to crash if it's not a string.
Otherwise, it's hard to decide what `config` should return.

I recently fixed an issue with the Platform selector here:
https://github.com/getsentry/react-native-sentry/issues/337

So we probably not gonna fix this since passing in undefined should never be valid.
But I am all ears for alternative solutions.

**Comment by m-vdb** [comment]
thanks!
