### ISSUE TITLE
'RCTEventEmitter.h' file not found while building iOS swift based | React Pod deprecated

### ISSUE THREAD

**Issue by Jflima92** [getsentry/react-native-sentry#344]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.9.0
5.5.1

├── react-apollo@2.0.4
├── react-dom@16.2.0
├── react-native@0.51.0
├── react-native-dash@0.0.8
├── react-native-fcm@11.2.0
├── react-native-firebase-crash-report@1.3.0
├── react-native-maps@0.17.1
├── react-native-sentry@0.33.0
├── react-native-svg@5.4.2
├── react-native-vector-icons@4.4.2
├── react-native-version-check@2.0.1
├── react-navigation@1.0.0-beta.13
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

I'm trying to setup sentry in my react-native project without success. 

I've already put up an issue in sentry-wizard regarding users that use swift instead of objC because the setup is not done properly when using swift.

But basically, after linking everything and manually add the excerpt of code to AppDelegate.swift I do pod install to get the Sentry libs, but apparently React Pod also comes as a dependency, despite being deprecated. I'm not sure if that's causing the issue, but after all these steps, while build the project I always get ``'RCTEventEmitter.h' file not found`` in ``RNSentryEventEmitter.h`` even though I can navigate to the RCTEventEmitter interface file.

Any help would be appreciated.
Thanks in advance.

**Steps to reproduce:**
- React Native project using swift for iOS
- yarn add react-native-sentry
- react-native link react-native-sentry
- pod install
- Manually add missing code to AppDelegate.swift
- Build Project

**Actual result:**
![image](https://user-images.githubusercontent.com/5619521/35688399-612c3468-0771-11e8-84f1-7b44c74df454.png)

**Expected result:**
- Successful build

**Comment by amsul** [comment]
I can confirm that I'm having this exact same issue. And I'm not using Swift, so I'm pretty sure it has nothing to do with that.

Not sure if downgrading with help - but gonna give it a shot

**Comment by amsul** [comment]
Got it working!

For anyone reading this, these are the steps I took:

1. Do NOT use CocoaPods for `react-native-sentry`
2. Follow the standard install steps:
	a) `yarn react-native-sentry`
	b) `react-native link react-native-sentry`
3. If your Podfile was modified by the setup script, remove any reference of ReactNativeSentry
4. Open Xcode and drag `node_modules/react-native-sentry/ios/RNSentry.xcodeproj` into your project's Libraries directory
5. Open your project's "Linked Frameworks and Libraries" and add `libRNSentry.a`

Hope that helps!

**Comment by Jflima92** [comment]
Hey @amsul thanks for the reply! I'll give it a shot and see it it works!

**Comment by amsul** [comment]
@Jflima92 since you're using Swift, you likely have to add the import to your bridging header first.

**Comment by Jflima92** [comment]
@amsul I've done that after adding the react-native-sentry ios folder to the headers search path with recursive mode, but still no luck. I'm a missing something? 😞

**Comment by ctoppel** [comment]
@amsul Thanks so much for your post. Was struggling to get this Sentry installed and built without errors and NOT using CocoaPods was the way to go.

**Comment by askielboe** [comment]
So am I correct to conclude that the official install instructions for react native on iOS are wrong?

Just trying to understand if this is a workaround for some rare issue, or if the documentation is outdated.

**Comment by amsul** [comment]
@askielboe not sure if it's "wrong" per se..I've seen other RN packages suggest similar steps of adding a dependency to the Podfile that points to `node_modules`. But I've never been able to get my builds to fully work in those cases.

However, this setup seems to always work.

**Comment by askielboe** [comment]
Yep, that's also my experience. Even for packages that very explicitly demands that I use cocoapods, I can never get it to work properly. But manually linking, as in this case, always seems to work.

Guess I was just wondering what the reason was to add the podspec when it seems not to work in a lot of cases. I like cocoapods for native development, and it would indeed be nice if it worked for RN native dependencies as well.

**Comment by sheminusminus** [comment]
@amsul this is the only thing that finally fixed this header files issue both locally and on our CI. thank you!

**Comment by othorin** [comment]
For me, this commit was the cause of the error: https://github.com/getsentry/react-native-sentry/commit/320651c23144664fb193c34a484a9fbee492dee9#diff-d8cd0abcb714ce13da6a6f2645e214af

After reverting that, the build finishes without problems. As a workaround until it's fixed or explained, I've added an npm post install script that reverts the commit.

```
if [ -f ./node_modules/react-native-sentry/SentryReactNative.podspec ]
then
  if ! grep "s.dependency 'React'" ./node_modules/react-native-sentry/SentryReactNative.podspec
  then
      sed -i.bak \
         $'s#s.dependency \'Sentry\'#s.dependency \'React\'\\\n  s.dependency \'Sentry\'#g' \
         ./node_modules/react-native-sentry/SentryReactNative.podspec
  fi
fi
```

(no sed-expert, but it seems to work...)

**Comment by HazAT** [comment]
@othorin Do you still have to error when using CocoaPods `1.4.0` as described here: https://github.com/getsentry/react-native-sentry/issues/395#issuecomment-388215879

TBH I don't really had time to wrap my head around this issue if the error lies on the CocoaPods or react-native side.
Both seem to have downsides but people seem to have more trouble now than before, I've asked the contributor to elaborate more on this, otherwise I will revert this back so React is in the podspec.

**Comment by HazAT** [comment]
Hey, so I reverted the change, `React` is back in the podspec.
Version `0.37.0` is on its way, sorry for the inconvenience this has caused.

**Comment by pitchourou** [comment]
Same issue 
react-native-sentry: ^0.37.1,
react-native: 0.51.0

**Comment by hoangvuanhdevelopervn** [comment]
i try all way above, it's still error =))))

**Comment by ChiAnTai** [comment]
@amsul You saved my life :D

**Comment by DusanDimitric** [comment]
@amsul's answer should be in Sentry's documentation.

**Comment by erwinjulius** [comment]
@amsul you're the best!

**Comment by kenjiUT** [comment]
good solution

**Comment by onmyway133** [comment]
@amsul Thanks, this works

**Comment by HazAT** [comment]
As a quick side note, I tried it on fresh clean swift ios project. 
Followed the react-native docs for integrating in an existing app here: https://facebook.github.io/react-native/docs/integration-with-existing-apps

And did:

```
yarn add react-native-sentry
react-native link react-native-sentry
cd ios
pod install
```

everything worked without doing any manual linking.

**Comment by silvainSayduck** [comment]
For my part, the [steps](https://github.com/getsentry/react-native-sentry/issues/344#issuecomment-362354851) given by @amsul worked, thanks a lot!

But I ultimately also figured out how to link Sentry with `react-native link`. The problem came from the fact that I did not have all of React Native's required podspecs. Sentry was then adding a wrong version of `React` (which even issued a deprecation warning on `pod install`).
Adding the podspecs according to the [React Native install guide](https://facebook.github.io/react-native/docs/integration-with-existing-apps), and then `$ react-native link`, `$ cd ios/; pod install` worked:

```
  ...

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  ...
```

**Comment by amsul** [comment]
@silvainSayduck that approach would work as well.

However, my concern with doing that is that it requires quite a bit of maintenance and knowledge of RN's dependencies to keep it working. Especially through upgrades as dependencies are changed/added/removed. It's a nightmare to debug that at times.

You can see hints of that in the snippet you posted as well, which requires separate dependencies for 0.42 0.43, 0.47, etc. This is going to be a never ending thing to maintain.
