### ISSUE TITLE
Installing Sentry significantly slows down loading remote images

### ISSUE THREAD

**Issue by amsul** [getsentry/react-native-sentry#345]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.4.0
5.5.1
project-path
├── color-hash@1.0.3
├── lodash@4.17.4
├── prop-types@15.5.10
├── UNMET PEER DEPENDENCY react@16.1.1
├── react-native@0.50.3
├── react-native-camera@0.10.0
├── react-native-circular-progress@0.0.8 invalid
├── react-native-contacts@1.0.4
├── react-native-device-info@0.13.0
├── react-native-fbsdk@0.6.3
├── react-native-firebase@3.1.0
├── react-native-fs@2.8.1
├── react-native-linear-gradient@2.3.0
├── react-native-mixpanel@0.0.15
├── react-native-section-list-get-item-layout@2.1.0
├── react-native-sentry@0.33.0
├── react-native-slider@0.11.0
├── react-native-svg@5.4.2 invalid
├── react-native-video@2.0.0
├── react-performance@0.0.4
├── react-redux@5.0.6
├── react-translated@2.2.0
├── redux@3.7.2
├── redux-logger@3.0.6
├── redux-thunk@2.2.0
├── reselect@3.0.1
├── source-map@0.6.1
└── superstruct@0.4.6
```

Config:

```js
Sentry.config('https://...@sentry.io/...', {
  // disableNativeIntegration: true,
  ignoreErrors: [/^Force close$/],
}).install()
```

---

After setting up `react-native-sentry`, all images in our app are loading INCREDIBLY slowly. It takes anywhere between 6-30 seconds to load a ~20kb image.

**Steps to reproduce:**
- Set up the project as described here: https://github.com/getsentry/react-native-sentry/issues/344#issuecomment-362354851
- Use the config above

**Expected result:**
- Images to load instantly without any impact of running the `install` call.

The issue is completely mitigated if we add `disableNativeIntegration: true` to the config. So it's definitely something to do with the native SDK.

We've tried it in a fresh project and were able to reproduce it. Has anyone else experienced this?

**Comment by HazAT** [comment]
That seems very strange, I will take a look whats happening.

**Comment by HazAT** [comment]
Hey,
So I've just tried it with a clean react-native project adding Sentry.
I am loading this picture
https://edmullen.net/test/rc.jpg
It doesn't take longer to load than in the Browser
```
<Image
          style={{width: 50, height: 50}}
          source={{uri: 'https://edmullen.net/test/rc.jpg'}}
        />
```
Can you instrument what's going in your app? (Check CPU und calls to functions)

**Comment by HazAT** [comment]
OK, closing this for now.
Keep in mind that if you `disableNativeIntegration` you will not capture any crash that happens in ObjC or Java.
