### ISSUE TITLE
ExceptionsManager.js:63 _document.attachEvent is not a function

### ISSUE THREAD

**Issue by onreadystatechange** [getsentry/react-native-sentry#346]
OS:
- [ ]  Windows
- [1 ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [ 1]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
<!-- Replace this -->
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

Description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by HazAT** [comment]
Hey, sorry I need an actual issue report, the title alone is not really helpful.
I would also need a reproduction case.
Feel free to post here again.

**Comment by onreadystatechange** [comment]
react native version:0.43.4
react-native-sentry:0.33.0
when  i  npm start i got "RNSentry.startWithDsnString got 2 arguments,expected 1", browser debug 
got "_document.attachEvent is not a function"

**Comment by onreadystatechange** [comment]
![img20180207175137](https://user-images.githubusercontent.com/21106077/35909922-ece89880-0c2f-11e8-953e-302224908209.jpg)
