### ISSUE TITLE
Breadcrumb data not captured on iOS

### ISSUE THREAD

**Issue by jpaas** [getsentry/react-native-sentry#35]
We're using 0.6.0 on both Android and iOS. We often pass additional information to captureBreadcrumb using the "data" option, but that information only appears on Android, never on iOS.

**Comment by HazAT** [comment]
Thx for reporting this.
Reason for that is that currently for iOS we use our native client which drops the additional data, we'll fix that.

**Comment by HazAT** [comment]
Fixed in latest release
