### ISSUE TITLE
401 when building react-native app. My credentials are good

### ISSUE THREAD

**Issue by hecontreraso** [getsentry/react-native-sentry#352]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [X]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v9.1.0
4.6.1
Driver@0.0.1 /Users/esteban/Desktop/kiwibot/Driver
├── @mapbox/react-native-mapbox-gl@6.0.2
├── expo@23.0.6
├── husky@0.14.3
├── lint-staged@6.0.1
├── prettier@1.10.2
├── react@16.0.0
├── react-native@0.51.0
├── react-native-google-location@0.2.0
├── react-native-sentry@0.33.0
├── react-navigation@1.0.0-beta.21
├── react-redux@5.0.6
├── redux@3.7.2
├── redux-thunk@2.2.0
├── rn-sliding-up-panel@1.1.7
├── url-parse@1.2.0
└── validate.js@0.12.0
```

Config:

```
Sentry.config('https://...@sentry.io/285564').install()
```

---
I have following issue:

Hello guys, I’m getting this error when I try to build the release of my react-native android app
https://imgur.com/a/poVU5

But my auth token is good, because when I put this on my terminal to login in sentry it works fine with the same token as my sentry.properties file

`./node_modules/@sentry/cli/bin/sentry-cli login`

this is the content of my sentry.properties file

    defaults.url=https://sentry.io/
    defaults.org=kiwi-campus
    defaults.project=driver-app
    auth.token=🔑
    cli.executable=node_modules/@sentry/cli/bin/sentry-cli

I already wasted 2 days trying to solve this. Could you please help me?

Thanks!

**Comment by HazAT** [comment]
@hecontreraso Can you send me your auth token to daniel@sentry.io so I can test it?

**Comment by diegocouto** [comment]
Hey, @hecontreraso! Were you able find a fix for this issue? I'm currently experiencing the same problem. 😔

**Comment by btoueg** [comment]
Same here, I think iOs builds are not able to take advantage of `ios/sentry.properties` anymore

**Comment by btoueg** [comment]
I fixed the issue by adding `export SENTRY_PROPERTIES=sentry.properties` in `Bundle React Native code and images` build phase, just before `../node_modules/sentry-cli-binary/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh`

I'm curious why it was working previously, any idea @HazAT ?

**Comment by HazAT** [comment]
Hmm, that's really strange, so I've just tried it with a clean react-native project and `export SENTRY_PROPERTIES=sentry.properties` was correctly added.
Did you guys create a new project?
Upgraded dependencies?

**Comment by btoueg** [comment]
I updated from "0.14.16" to "0.33.0"

**Comment by HazAT** [comment]
Please try to completely re-adding the plugin again, this should work.

I will close this issue for now since it has become stale.
Please feel free to post again if you are still having trouble with this.
