### ISSUE TITLE
`react-native link` always runs the wizard

### ISSUE THREAD

**Issue by Almouro** [getsentry/react-native-sentry#356]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.9.1
5.5.1

SentryTest@0.0.1 /Users/almouro/bam/uefa/SentryTest
├── react@16.2.0
├── react-native@0.53.0
└── react-native-sentry@0.33.0
```

Config:

```
// No particular config at this point
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
Hi,
Thanks for all the work on the Sentry wizard, I still remember when we had to configure all this manually, this is awesome! :)

I have the following issue with it though:
`react-native link` always runs the Sentry wizard

**Steps to reproduce:**
- `react-native init SentryTest`
- `cd SentryTest`
- `yarn add react-native-sentry`
- `react-native link` -> set up Sentry project with the wizard
- `react-native link` -> Wizard is still being ran even though project is configured already 

**Actual result:**
On the second run of `react-native link`, the wizard is still being run even though project is configured already

**Expected result:**
On the second run of `react-native link`, the wizard is not run

**Comment by HazAT** [comment]
Thank you for reporting this, `sentry-wizard` `0.8.3` fixed this issue, please upgrade :)

**Comment by Almouro** [comment]
Thanks @HazAT that was fast! :)

**Comment by grit96** [comment]
I can't use the wizard due to network proxies and having a local instance of Sentry running, so I have configured `react-native-sentry` manually and it works fine. However, whenever I run `react-native link` it will try to run the wizard and fail, requiring a <kbd>ctrl-c</kbd> to stop it. How can I tell `react-native-sentry` that it does not need to run the wizard?

**Comment by HazAT** [comment]
@grit96 You can define `SENTRY_WIZARD_URL` and guide it to your local installation.
See: https://github.com/getsentry/sentry-wizard

**Comment by HazAT** [comment]
@grit96 What version of Sentry are you running locally? 
It should be Sentry 9.x to make sure that the wizard works.
And, the wizard always runs when you call `link` that's what it's here for, it just shouldn't do anything if Sentry is already linked correctly (which in your case probably isn't).

**Comment by grit96** [comment]
I was using Sentry 8.22.0 from https://github.com/getsentry/onpremise, but they updated the repository to 9.0 recently so I have tried with that.
Now `react-native link` successfully completes the Sentry setup but then hangs on `Assets have been successfully linked to your project` (I don't know if this is a problem with `react-native-sentry` or something else). I have to press <kbd>ctrl-c</kbd> to quit and the next time I run `react-native link` it goes through the linking process for `react-native-sentry` (opens up the browser).

**Comment by grit96** [comment]
I have discovered something in [`sentry-wizard`](https://github.com/getsentry/sentry-wizard/blob/master/lib/Steps/Integrations/ReactNative.ts#L106) where it checks for the word Sentry in `index.ios.js` and `index.android.js` to decide whether to do the configuration or not. This fails for me because I have `index.common.js` where I configure Sentry that is required by `index.ios.js`, `index.android.js` and `index.electron.js`, causing the wizard to try and reconfigure every time.

**Comment by grit96** [comment]
Putting `/* Sentry */` in `index.ios.js` and `index.android.js` stops the wizard reconfiguring, but `react-native link` still hangs after completing (and does not hang if I remove `react-native-sentry` from `package.json`).

**Comment by emilkarl** [comment]
I have the same problem as @grit96. `react-native link` and the wizard completes bug it stalls after 
`Assets have been successfully linked to your project`.

![image](https://user-images.githubusercontent.com/10711/43830280-3617728c-9b01-11e8-8715-3fb7af995559.png)

**Comment by mads79** [comment]
I have exactly the same issue as @emilkarl and @grit96

**Comment by mpochron** [comment]
@HazAT please open it. 

My solution is to add a new option to the package.json where you can disable the annoying wizard

**Comment by Sampath-Lokuge** [comment]
`SENTRY_SKIP_WIZARD=true cordova plugin add sentry-cordova`

**Comment by W1nstar** [comment]
How is this closed when it's 2020 and is still happening?

**Comment by waqaramjad** [comment]
same issue
