### ISSUE TITLE
Bump KSCrash version

### ISSUE THREAD

**Issue by sola92** [getsentry/react-native-sentry#36]
The latest version of KSCrash contains a fix for an issue that is affecting our app:
https://github.com/kstenerud/KSCrash/issues/207

Looks like the fix is in version 1.15.8: https://github.com/kstenerud/KSCrash/commit/e8977a426ab3ef83939a1929c9c4743ae314bcd1

Can you please bump your version. Might also fix https://github.com/getsentry/react-native-sentry/issues/33

**Comment by HazAT** [comment]
See https://github.com/getsentry/react-native-sentry/releases/tag/v0.7.0
