### ISSUE TITLE
Delete sourcemaps from bundle after successful upload

### ISSUE THREAD

**Issue by ctaintor** [getsentry/react-native-sentry#364]
This is a feature request. I love how simple it was to set all of this up and have it working!

I was surprised to see that the sourcemaps are being bundled in my release. While everyone can write something to remove the sourcemaps, I figure that if someone is using Sentry and Sentry is uploading the sourcemaps, then it stands to reason that they don't need to have the sourcemaps bundled. For me, this saves about 5M in bundle size and also makes it that much harder for someone to decompile the app and make sense of it.

So - would it be possible to delete the sourcemaps upon successful upload by default?

**Comment by HazAT** [comment]
Hey, I suppose you mean Android right?
On iOS the source maps shouldn't be bundled at all.
And on Android this PR should do exactly that, if it's not working then it's a bug.
https://github.com/getsentry/react-native-sentry/pull/327

**Comment by LironErman** [comment]
> On iOS the source maps shouldn't be bundled at all.

The source maps still inside my .ipa file
I managed to delete the file by changing "Bundle React Native code and images" script 
```
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh

if [ "${CONFIGURATION}" == "Release" ]; then
    echo "Delete sourcemaps"
    cd "$CONFIGURATION_BUILD_DIR/$PROJECT_NAME.app"
    rm main.jsbundle.map
fi
```

Am I doing something wrong? can I remove the map file in other way?

**Comment by ctaintor** [comment]
@HazAT - thanks! I was actually looking at this code and was confused why we still had sourcemaps but then I remembered we're on an old version of react-native-sentry due to us not being able to update to Yarn 1.0+ due to it having bugs with resolving `file:` deps.

I think the iOS issue is there, but @LironErman's fix works for us.

**Comment by HazAT** [comment]
This should be fixed, if not please provide a way how to reproduce this, thanks.

**Comment by peacechen** [comment]
@HazAT  Thanks for the update.  Do you mean that sourcemaps are automatically pruned from the .ipa for iOS builds?  Or do we still need to add it to the script ourselves?

**Comment by xwartz** [comment]
Hi, @HazAT 
Why not  to delete the sourcemaps upon successful upload by default?
I think it's a good feature.

**Comment by JetCyC** [comment]
> This should be fixed, if not please provide a way how to reproduce this, thanks.

which release of react-native-sentry has the fix？Please tell me,I have bought sentry's service

**Comment by JetCyC** [comment]
> > On iOS the source maps shouldn't be bundled at all.
> 
> The source maps still inside my .ipa file
> I managed to delete the file by changing "Bundle React Native code and images" script
> 
> ```
> ../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh
> 
> if [ "${CONFIGURATION}" == "Release" ]; then
>     echo "Delete sourcemaps"
>     rm "$CONFIGURATION_BUILD_DIR/$PROJECT_NAME.app/main.jsbundle.map"
> fi
> ```
> 
> Am I doing something wrong? can I remove the map file in other way

> > On iOS the source maps shouldn't be bundled at all.
> 
> The source maps still inside my .ipa file
> I managed to delete the file by changing "Bundle React Native code and images" script
> 
> ```
> ../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh
> 
> if [ "${CONFIGURATION}" == "Release" ]; then
>     echo "Delete sourcemaps"
>     rm "$CONFIGURATION_BUILD_DIR/$PROJECT_NAME.app/main.jsbundle.map"
> fi
> ```
> 
> Am I doing something wrong? can I remove the map file in other way?

It works,but it can't  upload sourcemap
