### ISSUE TITLE
Stack trace line number 

### ISSUE THREAD

**Issue by dht** [getsentry/react-native-sentry#365]
OS:
- [X]  MacOS

_Platform:_
- [X]  iOS

```
v8.9.3
5.5.1
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
  logLevel: SentryLog.Debug, // default SentryLog.None | Possible values:  .None, .Error, .Debug, .Verbose
        disableNativeIntegration: false, // default: false | Deactivates the native integration and only uses raven-js
        handlePromiseRejection: true, // default: true | Handle unhandled promise rejections
        ignoreModulesExclude: [], // default: [] | Exclude is always stronger than include
        ignoreModulesInclude: [], // default: [] | Include modules that should be ignored too
}).install()
```

---
We see no line number for JS file in stack trace on dashboard. In this example we expected to see app_thunks.js:147:8. Is it configurable?

**Actual result:**
<img width="838" alt="screen shot 2018-02-26 at 15 43 26" src="https://user-images.githubusercontent.com/137832/36673645-22f9e6aa-1b0c-11e8-86e3-7ed19701ae2c.png">

**Expected result:**
![screen shot 2018-02-26 at 15 43 14](https://user-images.githubusercontent.com/137832/36673653-27325842-1b0c-11e8-939d-598e9eab31b1.png)

**Comment by AlexViapiano** [comment]
+1

**Comment by HazAT** [comment]
It looks like you didn't upload the source maps.
There should be a `Run script` in your Xcode project uploading them.
You can also do it manually, make sure release/dist are the same as in the app
https://docs.sentry.io/clients/react-native/sourcemaps/
