### ISSUE TITLE
Remove global dependency

### ISSUE THREAD

**Issue by rt2zz** [getsentry/react-native-sentry#37]
The docs require sentry-cli be installed globally, but it would seem to be much preferable to make the cli a local dep and change the build script to:
```
../node_modules/.bin/sentry-cli react-native-xcode ../node_modules/react-native/packager/react-native-xcode.sh
../node_modules/.bin/sentry-cli upload-dsym
```

Any issues with this approach?

**Comment by HazAT** [comment]
No, nothing wrong with it ... we gonna do it in an upcoming release.
