### ISSUE TITLE
Gradle build error: Cannot invoke method size() on null object

### ISSUE THREAD

**Issue by buckhx** [getsentry/react-native-sentry#374]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`
$ node -v && npm -v && npm ls --prod --depth=0
v9.8.0
5.6.0
Infatuation@0.0.1 /Users/buck/Workspace/github/the-infatuation/native-app
├── lunr@1.0.0
├── react@15.4.2
├── react-native@0.42.0
├── react-native-google-analytics-bridge@5.0.1
├── react-native-maps@0.12.4
├── react-native-sentry@0.35.1
├── react-navigation@1.0.0-beta.8
└── realm@2.2.15
Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

Latest version with fresh install has error building through gradle. This line is the culprit as there are no variants detected and it tries to get the count of a null collection.
This 
https://github.com/getsentry/react-native-sentry/blame/05aedb9c95c4fdd9f248a3cc6c49ada7c4bbb7a9/sentry.gradle#L90

Downgrading to v0.34.1 fixes

**Steps to reproduce:**
- react-native link react-native-sentry
- react-native run-android

**Actual result:**
- Actual
```
Error:FAILURE: Build failed with an exception.

* Where:
Script '/Users/buck/Workspace/github/the-infatuation/native-app/node_modules/react-native-sentry/sentry.gradle' line: 88

* What went wrong:
Cannot invoke method size() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Expected result:**
- A successful build

**Comment by HazAT** [comment]
This should be fixed with the latest version as of 0.35.2
