### ISSUE TITLE
Source code was not found for app:///main.jsbundle

### ISSUE THREAD

**Issue by sercanov** [getsentry/react-native-sentry#378]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v6.12.3
5.7.1
Rider@2.0.0 /Users/sercanov/Projects/rider
├── axios@0.18.0
├── base-64@0.1.0
├── card-validator@4.3.0
├── immutability-helper@2.6.6
├── is_js@0.9.0
├── lodash@4.17.5
├── moment@2.21.0
├── polyline@0.2.0
├── prop-types@15.6.1
├── raven-for-redux@1.3.0
├── UNMET PEER DEPENDENCY react@16.2.0
├── react-native@0.51.1
├── react-native-animatable@1.2.4
├── react-native-code-push@5.3.2
├── react-native-communications@2.2.1
├── react-native-config@0.11.5
├── react-native-device-info@0.11.0
├── react-native-fbsdk@0.7.0 (git+https://github.com/facebook/react-native-fbsdk.git#3859dc64f51199de9ffd4c28db469889009075bb)
├── react-native-firebase@3.3.1
├── react-native-indicators@0.10.0
├── react-native-keyboard-aware-scroll-view@0.4.4
├── react-native-linear-gradient@2.4.0
├── react-native-localization@0.1.32
├── react-native-maps@0.17.1
├── react-native-masked-text@1.6.5
├── react-native-navigation@1.1.314
├── react-native-pages@0.6.1
├── react-native-permissions@1.1.1
├── react-native-progresshub@0.1.2 
├── react-native-rakam-io@1.0.0
├── react-native-rating-requestor@2.0.0
├── react-native-sentry@0.34.1
├── react-native-share@1.0.26
├── react-native-simple-popover@2.1.0
├── react-native-timer@1.3.1
├── react-native-vector-icons@4.5.0
├── react-redux@5.0.7
├── redux@3.7.2
├── redux-logger@3.0.6
├── redux-persist@3.5.0
└── redux-thunk@2.2.0
```

Config:

```javascript
Sentry.config('https://👀').install()
Sentry.setRelease(`${DeviceInfo.getBundleId()}-3.0.0`)
Sentry.setVersion('3.0.0')
```

---
I have following issue:

I'm building with CI server then upload artifacts to sentry,

Upload script ;
```
    ./node_modules/@sentry/cli/bin/sentry-cli --log-level=DEBUG releases \
    files "com.app.ios-3.0.0" \
    upload-sourcemaps \
    --dist $APPCENTER_BUILD_ID \
    --strip-prefix "$APPCENTER_SOURCE_DIRECTORY/src" \
    --rewrite "$APPCENTER_SOURCE_DIRECTORY/dist"
```

I can see the artifacts as 
- ~/index.ios.map
- ~/main.jsbundle

**Steps to reproduce:**
- Step

**Actual result:**
- Symbolicated trace

**Expected result:**
- Unsymbolicated trace

**Comment by HazAT** [comment]
Hey,

You don't need to call both `setRelease` and `setVersion` on should be enough.
Can you link an event here so I can take a look at it?

**Comment by sercanov** [comment]
Sure @HazAT 
https://sentry.io/scotty/scotty/issues/500809542

Alright, I'll only call `setRelease` from now on 👍

**Comment by HazAT** [comment]
OK, so a few things I've noticed.

There is a dist set on the artifacts: 
https://sentry.io/scotty/scotty/releases/com.usescotty.ios-3.0.0/artifacts/
But not on your event, so in order to make it work you have to call `setDist('144')` to be the same as the dist on the artifact.
In short, release/dist of the event have to match the artifact.

Also, there seems to be some inconsistency with your filenames, sometimes it's called `index.ios.js` sometimes `main.jsbundle`.
These also have to match.

If everything matches, it should work without a problem.
We know the process is a bit tedious especially if you do it manually.

Hope this helps.

**Comment by sercanov** [comment]
Alright, I'll use `setDist` on Sentry initialization and try again.

About filenames, I was experimenting with CI build output and was renaming to be consistent, that might be the cause, should be okay now.

Thanks for the quick support, will let you know soon.

**Comment by sercanov** [comment]
Setting distribution worked @HazAT thanks !
