### ISSUE TITLE
react-native unlink runs the wizard

### ISSUE THREAD

**Issue by zzorba** [getsentry/react-native-sentry#380]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [X]  Android

---
I have following issue:

When running `react-native unlink react-native-sentry` the unlink is correctly executed, but then the onboarding wizard is run.

**Comment by HazAT** [comment]
Actually, it should run but not through the install process rather than the uninstall process which removes code we inject into your project.
Is this the case or does it really run the installation again?

**Comment by zzorba** [comment]
Well, it asked for all the setup information (API key, dsn secret, project name), which seems like something it wouldn't need for uninstall.

it is possible it was going to end up uninstalling but I didn't feel like looking up all that information.

**Comment by HazAT** [comment]
Ok, that seems strange, I will check what's going on.
Is it possible that you were using an old version (or upgrading from it)?

**Comment by zzorba** [comment]
I was on version '0.35.3' before triggering the unlink.  I hadn't yet
removed it from my package.json, but the unlink command (even though I
aborted it after the 4th question) did remove dependencies from the
iOS/Android projects.  There were a couple stale dependencies left behind
in one of the projects that I had to clean out manually.

**Comment by HazAT** [comment]
So that was the problem, the unlink was probably still triggered with the old "wizard".
This should no longer happen as of right now.
