### ISSUE TITLE
'Source code was not found for app:///index.bundle' error when uploading sourcemaps too many times to the same release

### ISSUE THREAD

**Issue by Alqasrawi** [getsentry/react-native-sentry#384]
OS:
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [ x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v6.11.3
3.10.10
MyNamshiReactNativeApp@0.0.1 /Users/khaledalqasrawi/Development/namshi-android
├── glamorous-native@1.2.0
├── json-beautify@1.0.1
├── lodash-es@4.17.4
├── moment@2.19.3
├── prop-types@15.6.0
├── query-string@5.1.1
├── react@16.0.0-beta.5
├── react-native@0.49.3
├── react-native-collapsible@0.9.0
├── react-native-credit-card-input@0.4.1
├── react-native-i18n@2.0.8
├── react-native-keyboard-aware-scroll-view@0.4.1
├── react-native-material-dropdown@0.8.0
├── react-native-material-textfield@0.10.2
├── react-native-modal@4.1.1
├── react-native-sentry@0.35.2
├── react-native-simple-radio-button@2.7.0
├── react-native-vector-icons@4.4.2
└── react-navigation@1.0.0-beta.13
```

Config:

```
Sentry.config(sentryClientKey).install();
Sentry.setRelease(releaseVersion);
```

---
I have following issue:

I added sentry to my react native app inside an existing Android app, I have 3 flavors each flavor has its own project on sentry.io account,  when uploading the sourcemaps too many times to the same release version I get the 'Source code was not found for app:///index.bundle' error.
If I bump the version number the javascript code gets shown normally on sentry.io

**Steps to reproduce:**
- Add sentry to an existing react native project on android with different flavors
- Create a separate project for each flavor and add the project settings in separate sentry.properties files for each flavor
- Upload the sourcemaps for one of the flavors to the same version too many times (12 - 20)
- If you bump the version number and upload the sourcemaps, javascript code will be shown properly

**Actual result:**
- sentry.io shows 'Source code was not found for app:///index.bundle' error message

**Expected result:**
- Javascript code should be shown properly

**Comment by ZhuZeus** [comment]
HI, did you figure it out?

**Comment by HazAT** [comment]
So this is probably an issue with release names, keep in mind release name + dist always have to match release + dist of the event. Otherwise, Sentry is not able to map the source map file to a specific crash.
Closing this now since it's already really old, feel free to post again if it's still an issue.
