### ISSUE TITLE
Does not work with Jenkins

### ISSUE THREAD

**Issue by firatakandere** [getsentry/react-native-sentry#389]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0` (from Jenkins)

```
+ node -v
v9.8.0
+ npm -v
5.6.0
+ npm ls --prod --depth=0
/Users/[username]/.jenkins/workspace/test
```

---
I have following issue:

I have Jenkins installed on my old Mac to automate the building process. I can successfully compile the project through its command line. But when I run the the compilation through Jenkins, I get the error on Build Phase:

**Actual result:**
```
❌  error: Can't find '/Users/[username]/.jenkins/workspace/[project path]/node_modules/@sentry/cli/sentry-cli' binary to build React Native bundle
```
PS:
- The file is actually there, if I create a Jenkins task that calls this file, the Jenkins can call it, and sentry-cli returns the help text. Therefore I don't think there's a permission issue between Jenkins and sentry-cli file.

**Comment by HazAT** [comment]
Hey, can you test a simple Jenkins job that does
`npm install @sentry/cli`
and then calls `node node_modules/.bin/sentry-cli` to check if that works.
It seems very odd that it does not work.

**Comment by firatakandere** [comment]
Sorry that I forgot the close the issue. The real reason was that the path included white spaces and one of the tools (probably xcode) does not escape it by default.
