### ISSUE TITLE
Does not support all Raven methods.

### ISSUE THREAD

**Issue by boennemann** [getsentry/react-native-sentry#39]
We were trying to migrate to the native plugin here at @adahealth and it was looking quite good.
We are however missing the full feature set that raven-js provided, e.g. `Raven.lastException()` and most importantly `Raven.lastEventId()`.

**Comment by HazAT** [comment]
Thx for pointing that out, we will add support for this in an upcoming version.
Is this feature blocking you from migrating right now?

**Comment by boennemann** [comment]
Hey @HazAT,

thanks for the quick reply.
We're currently using `lastEventId` to show that in a user facing error modal, which is fully integrated in our QA/Support workflows. We couldn't do the migration because of this – for now.

We're looking forward to the next release.

Best,
Stephan

**Comment by HazAT** [comment]
This is fixed in the latest release
