### ISSUE TITLE
Source code was not found for index.android.bundle

### ISSUE THREAD

**Issue by gilesvangruisen** [getsentry/react-native-sentry#390]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v9.9.0
5.6.0
xxxxxxxx@0.0.1 /Users/xxxxxxx/xxxxxxxx
├── @sentry/cli@1.30.3
├── eslint@4.15.0
├── format-currency@1.0.0
├── moment@2.19.4
├── number-to-locale-string@1.2.0
├── react@16.0.0
├── react-native@0.51.0
├── react-native-actionsheet@2.3.0
├── react-native-config@0.11.1
├── react-native-device-info@0.13.0
├── react-native-fabric@0.5.1
├── react-native-fast-image@2.0.1
├── react-native-fbsdk@0.7.0
├── react-native-firebase@3.2.6
├── react-native-image-crop-picker@0.19.1
├── react-native-in-app-utils@6.0.0
├── react-native-keyboard-aware-scroll-view@0.4.1
├── react-native-mixpanel@0.0.16
├── react-native-permissions@1.1.1
├── react-native-safari-view@2.1.0
├── react-native-sentry@0.35.3
├── react-native-side-menu@1.1.3
├── react-native-snap-carousel@3.6.0
├── react-native-table-component@1.1.3
├── react-navigation@1.0.0-beta.21
├── react-redux@5.0.6
├── react-relay@1.4.1
├── redux@3.7.2
├── redux-logger@3.0.6
├── redux-persist@4.8.2
├── redux-thunk@2.2.0
├── relay-compiler@1.4.1
└── sentry-cli-binary@1.25.0
```

Config:

```
Sentry.config(Config.SENTRY_DSN).install();

Sentry.setRelease(`${DeviceInfo.getBundleId()}-${DeviceInfo.getVersion()}`);
Sentry.setDist(`${DeviceInfo.getBuildNumber()}`);
```

---
I have following issue:

Now I know there's a handful of issues by a similar title but hear me out! haha. I've crawled through and confirmed things (I know of) which need to match are indeed matching. So now I'm a bit stumped.

I'm expecting a symbolicated error report but am not seeing one.

More info:
- Confirmed matching `dist` # 102186 `~/index.android.bundle` artifact exists (see screenshots below)
- Release `xx.xx.xx-1.0.2` matches release name in URL of Artifacts page. Indeed, the second screenshot below is the page linked via the "release tag" (`i`) button on the first screenshot.

Don't want to share my client here in here but I'm happy to link you to our Sentry org/relevant error reports in a private channel. Let me know how is best to do that.

Thanks!!

![image](https://user-images.githubusercontent.com/1256189/38904269-6c1a0b84-4277-11e8-9052-61575dc06ccb.png)

![image](https://user-images.githubusercontent.com/1256189/38904125-8362a914-4276-11e8-8adf-3fb4e60bda21.png)

**Steps to reproduce:**
- `./gradlew installProductionRelease`
- throw error

**Actual result:**
"There was 1 error encountered while processing this event"
"Source code was not found for app://index.android.bundle"

**Expected result:**
- Expected symbolicated/mapped error report

**Comment by HazAT** [comment]
Sorry for the delay.
2 things I've noticed while looking at your events.

1. It seems something is wrong with the native integration, you can see this by checking the SDK section at the bottom, it says `raven-js` instead of `sentry-react-native`.
This indicates that somehow the native integration in android isn't running.
Check your entryfile for:
https://github.com/getsentry/react-native-sentry/issues/6#issuecomment-368777938

2. For some reason, the frames say `app://` instead of `app:///` (with 3 `/`).
I am not sure if the is a bug in our lib or if you change the frames somehow.

The rest looks fine.
Please report back with your findings :)

**Comment by gilesvangruisen** [comment]
@HazAT oh wow, I'm sorry!! #1 seems to have fixed it, we do have a handful of native packages but I'm not sure how I missed that. 

I think fixing the native integration seemed to fix the stacktrace frames (now preceded by 3 `/`) and stack traces are now symbolicating properly. 

Thanks for your help! Going to close this.

**Comment by pinguo-zhouwei** [comment]
I have the same problem，sourcemap upload success ,but there is a error tip: 
![image](https://user-images.githubusercontent.com/8786349/50536472-f038e480-0b8f-11e9-9478-febd4950566b.png)
how to fix it ?

**Comment by tiaaaa123** [comment]
I'm having the same issue as @pinguo-zhouwei.
In the SDK section, it says `sentry-react-native` with `0.39.1`

<img width="478" alt="screen shot 2019-02-01 at 8 57 23 am" src="https://user-images.githubusercontent.com/9055082/52127246-8af96880-25ff-11e9-999b-e9c128cfddab.png">

**Comment by HazAT** [comment]
Make sure source maps are uploaded as `~/index.andoird.bundle` and `~/index.andoird.bundle.map`
and also the `dist` and `release` tag of the event match exactly the name of where you uploaded the artifacts to.

**Comment by tiaaaa123** [comment]
But doesn't the react-native-sentry lib is already suppose to do that? We don't have much control on what is send during the `./gradlew assembleRelease` don't we?

**Comment by jay1337** [comment]
> 
> 
> Make sure source maps are uploaded as `~/index.andoird.bundle` and `~/index.andoird.bundle.map`
> and also the `dist` and `release` tag of the event match exactly the name of where you uploaded the artifacts to.

@HazAT same issue for me with `app:///index.andoird.bundle` and an artefact `~/index.android.bundle` for the same version and distribution.

**Comment by thisisjaiswal** [comment]
> Make sure source maps are uploaded as `~/index.andoird.bundle` and `~/index.andoird.bundle.map`
> and also the `dist` and `release` tag of the event match exactly the name of where you uploaded the artifacts to.

I was facing this issue since a long time. finally got it working. 
I had followed all the instructions correctly but still wasn't able to fix it. finally realised I was not setting 'dist' tag in the source map
