### ISSUE TITLE
How does sentry native compare to crashlytics?

### ISSUE THREAD

**Issue by chirag04** [getsentry/react-native-sentry#4]
We are currently using raven-js for capturing js strack traces and crashlytics for native. This is sort of working ok for us. Before making the switch, I was wondering how sentry native compares with something like crashlytics.

**Comment by mitsuhiko** [comment]
You can use this and crashlytics at the same time and then try it and see for yourself :)

**Comment by pkantsedalov** [comment]
@chirag04 @mitsuhiko Hi guys.
Can you tell me please how did you integrate both Sentry and Crashlytics? It seems that Sentry catches crashes _before_ Crashlytics: we see output in Sentry dashboard and don't see it in Crashlytics' one.
