### ISSUE TITLE
[iOS] native error not reported from "Got memory pressure notification (critical)"

### ISSUE THREAD

**Issue by peacechen** [getsentry/react-native-sentry#402]
OS:
- [x]  MacOS

_Platform:_
- [x]  iOS

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v9.3.0
5.5.1
MyApp@1.2.3 /Users/someone/my-app
├── apisauce@0.14.3
├── lodash@4.17.5
├── moment@2.22.1
├── numeral@2.0.6
├── query-string@5.1.1
├── react@16.3.2
├── react-native@0.55.3
├── react-native-animatable@1.2.4
├── react-native-autocomplete-input@3.5.0
├── react-native-battery@0.1.15
├── react-native-button@2.3.0
├── react-native-calendar-picker@5.18.0
├── react-native-calendar-strip@1.3.3
├── react-native-code-push@5.3.2
├── react-native-collapsible@0.10.0
├── react-native-config@0.11.5
├── react-native-device-info@0.21.5
├── react-native-drawer@2.5.0
├── react-native-elements@0.19.1
├── react-native-fetch-blob@0.10.8
├── react-native-keep-awake@3.0.1
├── react-native-keyboard-aware-scroll-view@0.4.4
├── react-native-loading-spinner-overlay@0.5.2
├── react-native-local-storage@1.5.2
├── react-native-maps@0.20.1
├── react-native-modal-selector@0.0.27
├── react-native-responsive-grid@0.41.96
├── react-native-restart@0.0.6
├── react-native-sentry@0.36.0
├── react-native-svg@6.3.1
├── react-native-tab-navigator@0.3.4
├── react-native-vector-icons@4.6.0
├── react-native-video@2.0.0
├── react-navigation@1.0.0-beta.16
├── react-redux@5.0.7
├── reactotron-react-native@1.14.0
├── reactotron-redux@1.13.0
├── redux@3.7.2
├── redux-thunk@2.2.0
├── url@0.11.0
└── victory-native@0.17.4
```

Config:

```
Sentry.config('https://MY_SUPER_SECRET_KEY@sentry.io/1199913').install();
```

---
I have following issue:

Our production app has a corner case bug that causes a crash logged by Xcode:
`Got memory pressure notification (critical)`

This is a release build running on a physical device.  I'm pinpointing the cause, but this type of bug out in the field doesn't get reported by Sentry.  I'm guessing that Sentry isn't able to save crash information due to the app running out of memory.

On subsequent app launch:
```
Sentry Started -- Version: 3.12.4
INFO : KSCrash.m (339): -[KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
```

Sentry is set up and operating properly in our app because it's able to log RN unhandled exceptions in the JS code.

**Steps to reproduce:**
We trigger this in our app with a large FlatList and rotating the screen repeatedly.  There is a menu drawer component that isn't very optimized and may be contributing.

**Actual result:**
App crashes with no crash report.

**Expected result:**
App crashes with crash report.

**Comment by HazAT** [comment]
We are using https://github.com/kstenerud/KSCrash for all our crash handling and I am not sure if KSCrash is able to "catch" those kinds of errors.

I will write this down and check if we somehow can catch this in sentry-cocoa.
