### ISSUE TITLE
Fingerprint is not set properly

### ISSUE THREAD

**Issue by HazAT** [getsentry/react-native-sentry#407]
^ title

**Comment by Kornflexx** [comment]
Hello,

An error appear this morning from nowhere:

`node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java:251: error: incompatible types: ReadableArray cannot be converted to ReadableNativeArray
            addExceptionInterface(eventBuilder, exception.getString("type"), exception.getString("value"), stacktrace.getArray("frames"));`

Is this error related to the issue ?

**Comment by gouxlord** [comment]
Hi @Kornflexx , its more linked to:

https://github.com/facebook/react-native/issues/19259

Juste use `compile ("com.facebook.react:react-native:0.51.0-rc.3") { force = true } // From node_modules` in your àpp/build.gradle`;)

**Comment by grit96** [comment]
Yes, it is always set to `["{{ default }}"]` event when it is passing into `Sentry.captureException()`.

**Comment by nguyenhose** [comment]
@HazAT I am stuck when tried group messages using fingerprint. Could you tell me which is event of react-native-sentry that I can modify data to add `fingerprint` attribute ?

**Comment by JBenda** [comment]
Can we set the fingerprint in ``react-native-sentry`` only with ``Sentry.configureScope``? This does not feel right for only one time changes. Because we only want the modified the fingerprint for one call. This cause to Code like this:
```JS
let fingerprint = null;
Sentry.configureScope((scope) => {
  scope.setFingerprint(fingerprint || ['{{default}}']);
});
function specialException(error, tags) {
  fingerprint = tags;
  Sentry.captureException(error);
  fingerprint = null;
}
```

**Comment by nguyenhose** [comment]
@JBenda D you can use like this example for custom sentry catch (crash, exception ... )
```js
export const captureMessage = (message, extra = {}, level = 'warning') => {
  Sentry.captureMessage(message, {
    level,
    extra,
    fingerprint: ['Type: Crash', 'Message: null is not object']
  })
}
```

**Comment by llostris** [comment]
According to release notes, this should've been added in 0.40, however, we still don't seem to have fingerprint set on iOS. Does it require using Pods now to have this feature, or any other steps need to be performed to have it working when upgrading? 
(Referring to this: #507 and the updates in sentry-cocoa that were related to this)

**Comment by llostris** [comment]
According to release notes this should be fixed in 0.40.2 however upon upgrading, the fingerprint seems to be sent on Android, but not on iOS. Does anything extra needs to be configured for it to work on iOS? We've updated the library, unlinked and linked `react-native-sentry` again, and re-added the framework/library in XCode, it hasn't changed anything :(

**Comment by jessestuart** [comment]
FYI @llostris @maximeaubaret et al., I think I've got a fix for this over at https://github.com/getsentry/sentry-cocoa/pull/279. Certainly explains why disabling the native integration did the trick for you! 

For anyone else scratching their head over this before it makes it into a release, it's easy to make the one line change directly in your `Pods` directory (for @CocoaPods users), or using e.g., [`patch-package`(https://github.com/ds300/patch-package)] if not.

**Comment by llostris** [comment]
@HazAT Any chance of getting that fix released?

**Comment by HazAT** [comment]
Release `0.40.3` going out now, closing this for now.

**Comment by jessestuart** [comment]
Thanks again for the quick turnaround @HazAT! 👍
