### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by erez-guesty** [getsentry/react-native-sentry#409]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of node -v && npm -v && npm ls --prod --depth=0

v8.11.1
6.0.1
react@16.0.0
react-native@0.51.0
react-native-sentry@0.34.0

```
node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java:262: error: incompatible types: ReadableArray cannot be converted to ReadableNativeArray
                addExceptionInterface(eventBuilder, exception.getString("type"), exception.getString("value"), stacktrace.getArray("frames"));
```
---
I have following issue:

Failed to build android apk

**Steps to reproduce:**
- run on termial ```react-native run-android```

**Actual result:**
node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java:262: error: incompatible types: ReadableArray cannot be converted to ReadableNativeArray
                addExceptionInterface(eventBuilder, exception.getString("type"), exception.getString("value"), stacktrace.getArray("frames"));

**Expected result:**
- build succeed

**Comment by RobPando** [comment]
Was just about to open this very same issue. I am on `react-native@0.52` and  `react-native-sentry@0.32`, I thought it might have to do something wit the version so I updated the library to 0.36 and I get `React Native version mismatch` so it seems that the new version of this library is only compatible with RN 55? if so the readme needs to be updated.

**Comment by m-vdb** [comment]
Updating to `0.36.0` fixed it for me:
```
v6.11.2
5.3.0
<myproject>
├── react@16.2.0
├── react-native@0.52.2
└── react-native-sentry@0.36.0
```

**Comment by foxmicha** [comment]
It seems like it's trying to compile the react-native-sentry projects using a different version number than what is currently installed in the node_modules folder.

I am on RN v0.51 as well. I haven't done an npm install of react-native-sentry since December. The build worked fine yesterday and breaks today.

**Comment by HazAT** [comment]
So this issue is not really related to Sentry, more like react-native / gradle itself.
Please use a version `> 0.34.1` which should fix this issue.

**Comment by m-vdb** [comment]
@HazAT why do you say it fixes the issue?

**Comment by m-vdb** [comment]
thanks! Don't why I didn't see that. I especially read this comment that explains the issue: https://github.com/facebook/react-native/issues/13094#issuecomment-389568018
