### ISSUE TITLE
Source map file is getting automatically deleted

### ISSUE THREAD

**Issue by GargManish** [getsentry/react-native-sentry#412]
OS:
- [ ]  MacOS

_Platform:
- [ ]  Android

Output of react-native run-android --variant=release is creating source map file inside android/app/build/intermediate folder but it's getting deleted. In apk there is no source file. On Sentry dashboard output is not providing proper information about the js file name.

ReferenceError
ReferenceError: Can't find variable: Button1

This error is located at:
    in t
    in Connect(t)
    in n
    in s
    in RCTView
    in RCTView
    in t
app://index.android.bundle in value at line 352:2578

Expected result is:
ReferenceError
ReferenceError: Can't find variable: Button1

This error is located at:
    in ItemSearch (created by Connect(ItemSearch))
    in Connect(ItemSearch) (at Navigation.js:83)
    in Provider (at Navigation.js:82)
    in _class2 (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)

Its coming only for the debug build.

**Comment by HazAT** [comment]
This should work, also we do not fully support the "Debug" story since react-native itself provides you with an alert screen where the error happened.
