### ISSUE TITLE
npm i (or yarn install) fails to complete with errors coming from the sentry package

### ISSUE THREAD

**Issue by spruce-bruce** [getsentry/react-native-sentry#415]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && yarn --version && npm ls --prod --depth=0`

```
v8.9.3
6.0.1
1.3.2
HeliaConnect@0.0.1 /Users/aaron/code/synapse/helia/HeliaConnect
├── @redux-offline/redux-offline@2.3.3
├── @synapsestudios/fetch-client@1.0.4
├── appcenter@1.5.1
├── appcenter-analytics@1.5.1
├── appcenter-crashes@1.5.1
├── async@2.6.1
├── date-fns@1.29.0
├── formik@0.10.5
├── immutable@3.8.2
├── jwt-decode@2.2.0
├── lodash@4.17.10
├── numeral@2.0.6
├── prop-types@15.6.1
├── querystring@0.2.0
├── react@16.2.0
├── react-immutable-proptypes@2.1.0
├── react-native@0.52.3
├── react-native-actionsheet@2.4.2
├── react-native-datepicker@1.7.2
├── react-native-keyboard-aware-scroll-view@0.4.4
├── react-native-modal@4.1.1
├── react-native-sentry@0.35.0
├── react-native-sqlite-2@1.6.0
├── react-native-svg@6.3.1
├── react-native-swipeable@0.6.0
├── react-native-version-number@0.3.3
├── react-navigation@2.0.1
├── react-redux@5.0.7
├── redux@3.7.2
├── redux-persist@4.10.2
├── redux-persist-transform-immutable@5.0.0
├── redux-thunk@2.2.0
├── reselect@3.0.1
├── url-search-params-polyfill@2.0.3
├── uuid@3.2.1
└── yup@0.24.1
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
  // nothing
}).install()
```

---
I have following issue:

`npm i` fails with the following error:

```
Error: Command failed: /Users/aaron/code/path/to/project/node_modules/@sentry/cli/sentry-cli --version
```

**Steps to reproduce:**
- lock `react-native-sentry` to any version in package.json (tried with 0.35.0 through 0.37.0)
- remove node_modules and package-lock.json (or yarn-lock.json)
- run `npm i` or `yarn`

**Actual result:**
- Fails with error reported above

**Expected result:**
- Successfully installs :P

**Comment by maggialejandro** [comment]
Here is the issue on sentry-cli repo
https://github.com/getsentry/sentry-cli/issues/307

**Comment by spruce-bruce** [comment]
Anybody who finds this issue - There's a work around from the above sentry-cli issue.  Do `npm i @sentry/cli@1.3.0` on your project.

**Comment by lfkwtz** [comment]
@spruce-bruce you probably meant `npm i @sentry/cli@1.31.0 --save`

**Comment by codeocelot** [comment]
similar error coming from the webpack plugin too.

**Comment by spruce-bruce** [comment]
@lfkwtz you're right! i'm a notorious typoist...

**Comment by HazAT** [comment]
We are working on a fix, stay tuned.

**Comment by lfkwtz** [comment]
fixed for me in sentry-cli@1.32.0

**Comment by HazAT** [comment]
Closing this, if you are still running into this, please upgrade to > `sentry-cli@1.32.0`.

**Comment by spruce-bruce** [comment]
Thanks!
