### ISSUE TITLE
Importing Sentry causes error regarding `fetch`.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [getsentry/react-native-sentry#424]
Adding `import Sentry from 'sentry-expo'` to my `App.js` causes my app to crash:

```
Unhandled JS Exception: Requiring module "fetch", which threw an exception. 
TypeError: undefined is not an object (evaluating 'self.fetch').
```

Same problem happens if I simply import `react-native-sentry`.

Digging around, I've seen issues crop up in `react-native` [here](https://github.com/facebook/react-native/issues/9599) and `fetch` [here](https://github.com/github/fetch/issues/125) and `isomorphic-fetch` [here](https://github.com/matthew-andrews/isomorphic-fetch/pull/63). AFAICT, `isomorphic-fetch` is the root of the problem, it's not maintained and didn't support React Native, and now people are moving to other packages (`cross-fetch`, `fetch-everywhere`, `fetch-ponyfill`, etc.) as a replacement.

Are other people running into this problem? Right now, following the Expo docs, I'm unable to get Sentry to work for React Native. 😞 

Versions:

```
node: v8.4.0
npm: 5.6.0

"expo": "^27.0.2",
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
"sentry-expo": "^1.9.0"
```

**Comment by HazAT** [comment]
Hey, 

So not really sure what's going on, I can't reproduce this issue.
If I do a 
```
create-react-native-app AwesomeProject
cd AwesomeProject
yarn add sentry-expo
npm start
```
As stated here:
https://facebook.github.io/react-native/docs/getting-started.html
https://docs.expo.io/versions/latest/guides/using-sentry#install-and-configure-sentry
it works without an error.

So I need a repro case in order the be able to help you :/

**Comment by brentvatne** [comment]
I also tried to repro this and was unable to, I think there is some interaction with another library being used in the project

**Comment by AndrewSouthpaw** [comment]
Blah. Thanks for looking into it, we'll dig around more on our end and see what's messing it up. 🙁

**Comment by AndrewSouthpaw** [comment]
FYI we resolved the issue by changing our `.babelrc` file. It used to contain a bunch of stuff:

```
presets: ['es2015', 'react', 'stage-2', 'flow', 'babel-preset-expo']
```

We changed it to

```
presets: ['babel-preset-expo']
```

and the problem resolved itself.

**Comment by Quadriphobs1** [comment]
I still experience thus if you try to use it alongside jest... Jest would not be able to run because of fetch api... Is there a test for this project already using jest

**Comment by spezzino** [comment]
Still happening with this config
```
"expo": "^29.0.0",
"sentry-expo": "^1.10.0"
```

Result: 
```
Unhandled JS Exception: Requiring module "fetch", which threw an exception. 
TypeError: undefined is not an object (evaluating 'self.fetch').
```

![image](https://user-images.githubusercontent.com/2013367/47926487-704c1200-de9f-11e8-900e-cd08cf0bc47b.png)

.babelrc
```
{
  "presets": [
    "babel-preset-expo"
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source"
      ]
    }
  }
}
```

**Comment by spezzino** [comment]
Solved by explicitly adding this version to package.json

```
"whatwg-fetch": "2.0.4"
```

**Comment by leaphawk** [comment]
This is likely an issue with the `npm` & `builder` cache. You must be having another dependency depending on `whatwg-fetch`.

Which you can easily check with `npm ls whatwg-fetch`.

Remove the dependency which is using `whatwg-fetch` reinstall it. Also clear the builder cache. If you're using expo `expo start -c`

You'll find some solution stating to do: `global.self = global`. Which is not really a solution.

**Comment by obibring** [comment]
@maxammann, I'm seeing the same issue with `transform-es2015-modules-commonjs`, but unfortunately, I need the plugin installed. Any idea what a workaround might be?

**Comment by maxammann** [comment]
There is an updated Version of that Plugin :) https://www.npmjs.com/package/@babel/plugin-transform-modules-commonjs

Also reset the cache of the packager.
