### ISSUE TITLE
android proguart

### ISSUE THREAD

**Issue by xyzconduent** [getsentry/react-native-sentry#429]
OS:
- [x]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
<!-- Replace this -->
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

Description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by HazAT** [comment]
Sorry I need a bit more information 😅 
Closing this, feel free to create a new ticket with a proper description.
