### ISSUE TITLE
Ability to ignore errors from native side, but disableNativeIntegration is false?

### ISSUE THREAD

**Issue by wiscat** [getsentry/react-native-sentry#430]
Hi, thank you for this package!
Is there any option to ignore errors from native side, while keep disableNativeIntegration false?

**Comment by HazAT** [comment]
Why do you want to do this?
Right now there is no way besides `disableNativeIntegration` setting to true.

**Comment by wiscat** [comment]
I dont want to catch native errors, but I want extra native information about device on js errors
