### ISSUE TITLE
java.lang.Double cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by masterT** [getsentry/react-native-sentry#436]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v9.11.1
6.0.1
Kimoby@0.0.1 /Users/simon/Documents/kimoby/kimobile
├── axios@0.18.0
├── lodash@4.17.10
├── mime@2.3.1
├── moment@2.22.2
├── prop-types@15.6.2
├── pusher-js@4.2.2
├── react@16.3.1
├── react-native@0.55.4
├── react-native-document-picker@2.1.0
├── react-native-dotenv@0.1.1
├── react-native-firebase@4.2.0
├── react-native-i18n@2.0.12
├── react-native-image-picker@0.26.10
├── react-native-linear-gradient@2.4.0
├── react-native-modal@6.0.0
├── react-native-newrelic@1.1.1 (git+https://git@github.com/eleretic/react-native-newrelic.git#a1b64afe379b8da6d8a23948288a13c061d5d404)
├── react-native-sentry@0.38.0
├── react-native-splash-screen@3.0.9
├── react-navigation@2.5.3
├── react-redux@5.0.7
├── redux@4.0.0
├── redux-logger@3.0.6
├── redux-thunk@2.2.0
├── rn-viewpager@1.2.9
└── set-cookie-parser@2.2.0
```

Config:

```
Sentry.config('🔑').install()
```

---
I have following issue:

I try to set user context with 

```js
Sentry.setUserContext({ userId: 1293847 })
```

I got this error:

<img width="314" alt="screen shot 2018-07-03 at 9 30 13 am" src="https://user-images.githubusercontent.com/2584158/42222636-bbe1e30e-7ea3-11e8-82f7-e669b3d01fc3.png">

Stacktrace:

```
java.lang.Double cannot be cast to java.lang.String
getString
    ReadableNativeMap.java:168
getUserBuilder
    RNSentryModule.java:295
setUser
    RNSentryModule.java:177
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:148
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:818
```

I tried with 

```js
Sentry.setUserContext({ foo: 1293847 })
```

I had no error.

**Comment by HazAT** [comment]
Please make the userId a string, this should fix it.

**Comment by masterT** [comment]
It doesn't look like the right way to do it, can't you detect the type instead of making the supposition that it's a _String_?

https://github.com/getsentry/react-native-sentry/blob/e04f429de7fbec10b3fc17a4d6a9ce094e1345e5/android/src/main/java/io/sentry/RNSentryModule.java#L297

**Comment by sryze** [comment]
I ran into the same issue, I hasn't sen any mention that `userId` must be a string in the documentation. JavaScript is a dynamic language, you can't expect values coming from the JS side to strictly match a string or a double, you should convert between the two representations internally.

**Comment by andrewzey** [comment]
@sryze Is absolutely right, this is extremely unexpected behavior. Thanks @HazAT and @masterT for providing a temporary solution and explanation of the underlying issue!

**Comment by SethArchambault** [comment]
Just ran into this issue today - coincided with building for 64 bit systems as required by Android. Maybe a coincidence, or maybe a lot more people will be encountering this issue!
