### ISSUE TITLE
How can I disable the automatic javascript sourcemap uploading?

### ISSUE THREAD

**Issue by jamesone** [getsentry/react-native-sentry#446]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.6.0
5.6.0
```

---

I have following issue:

I want to be able to disable the automatic javascript sourcemap uploading that happens when running: `./gradlew assembleRelease`. 

Expected result:

react-native-sentry won't automatically upload the js sourcemaps

----

Is there a property I can add to sentry.properties which will disable the automatic javascript sourcemap uploading?

**Comment by HazAT** [comment]
Remove this line from your gradle file:
`apply from: "../../node_modules/react-native-sentry/sentry.gradle"`
see: https://docs.sentry.io/clients/react-native/manual-setup/#android

**Comment by arughani** [comment]
@HazAT  I am facing an issue where I am not able to get absolute path and getting minified path of js file. Where as I need absolute path to it. Can you please help me for the same

**Comment by junshengpierre** [comment]
Hi, @HazAT how could we do it for ios?
