### ISSUE TITLE
Line numbers are never corrects in error reporting on iOS or Android

### ISSUE THREAD

**Issue by dawee** [getsentry/react-native-sentry#451]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
node -v && npm -v && npm ls --prod --depth=0
v10.7.0
6.1.0
ClubMobile@0.0.1 /Users/dcorticchiato/projects/mobile-reboot
├── prop-types@15.6.1
├── react@16.3.0-alpha.1
├── react-native@0.54.4
├── react-native-animatable@1.3.0
├── react-native-create-bridge@2.0.1
├── react-native-sentry@0.38.2
├── react-navigation@2.9.0
├── react-redux@5.0.7
├── redux@3.7.2
└── styled-components@3.2.5
```

Config:

```
Sentry.config('https://MY_AUTH@MY_PRIVATE_DSN').install();
```
---
I have following issue:

When I report any error with `throw new Error...` I've got the traceback on my server, the function names are OK the enlighted line in code is like 20 lines after the good one (unsymbolicated) and can obviously be anywhere when symbolicated.

**Steps to reproduce:**
- Copy example code from sentry repository (the one with _throwError function)
- Let sentry automatically publish sourcemap with the post-build automatic scripts (xcode or gradle, debug or release, I tested all cases)
- Click on "Throw Error"
- You should see the error on the server, but the enlighted code has nothing to do with the error.

**Actual result:**
- The enlighted code has nothing to do with the error

**Expected result:**
- The enlighted code should be the one where `throw Error` is called

**Comment by dawee** [comment]
I also tried to update to `react-native@0.56.0` but I didn't get a better result. 

That's really frustrating because I would love working with sentry, it's an excellent tool but after a week of trying a lot of different configurations my team will probably give up. No criticism implied here of course. I know you work really hard on this.

I tried to see if I can contribute but I have really no clue.
Any help on this would be appreciated. I'm completely lost.

**Comment by HazAT** [comment]
Hey, 

I am really sorry and I know this issue is long-lasting and very annoying.
This is actually an issue with react-native itself see: https://github.com/facebook/react-native/issues/6946

But there is a workaround to not minify the sources (that sometimes works) -.-
see: https://github.com/facebook/react-native/issues/6946#issuecomment-386754414

They said they fixed but it isn't.

**Comment by dawee** [comment]
Hey,

Thanks for the reply. I've seen this thread before on react-native before. That's why I tried with latest version (I also tried to install latest metro version too) but it doesn't change anything.

As the other issue you had about it talked about Android only, I was hopping it was maybe something different but it is not :/.

I already tried with unminified. Same error sadly. 

Anyway, sorry for duplicating an existing issue. Have a good day :).

**Comment by YeatsLu** [comment]
see: [facebook/react-native/issues/20628](https://github.com/facebook/react-native/issues/20628)

**Comment by HazAT** [comment]
@YeatsLu Thx for this :)
@dawee Does iOS work for you?

**Comment by dawee** [comment]
Hum, this fix is for Android only I think. It's an upgrade of JSC. In IOS it's linked to the system version.

Anyway, recently I discovered that the release iOS version with a dSym upload on our sentry server get some pretty good results. We always have a 1 line number offset, but it's sufficient for us for the moment.

Good news, Android works fine with this fix.
Sure thing is, there is no issue with sentry plugin, it's all in react-native side so let's wait for the 0.57 version which might fix a lot of problems. I think we can close this issue.

Thanks for the help !

**Comment by dawee** [comment]
BTW I presented the sentry implementation to my team and they were all pretty amazed / super exited to use it. Good job for this amazing implementation, it feels magic to get iOS merged stack trace.

**Comment by HazAT** [comment]
@dawee Thanks 😄 
Closing this now.

**Comment by lylest** [comment]
am facing this error but i can not trace the problem since i can not find the line number of line specifically
