### ISSUE TITLE
exception Signal 5, Code 0

### ISSUE THREAD

**Issue by peacechen** [getsentry/react-native-sentry#456]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v9.3.0
5.5.1
```

Config:

```
Sentry.config('🔑').install();
```

---
I have following issue:

My app reported the exception `exception Signal 5, Code 0`.  The stack trace shows a code push check happened at 03:00, then 12 hours later it reported the exception.  What is this error?   I searched but couldn't find anything on it.

> console [CodePush] An update is available but it is not targeting the binary version of your app. 03:00:01 
> console [CodePush] App is up to date. 03:00:01 
> exception Signal 5, Code 0 15:43:10 
> 

**Steps to reproduce:**
Unknown

**Actual result:**
Exception report

**Expected result:**
No exception

**Comment by HazAT** [comment]
Can you link me to the event in your sentry.io account?

**Comment by peacechen** [comment]
Here ya go:
https://sentry.io/oncethere/booking/issues/630728595/

**Comment by HazAT** [comment]
Thanks for the link.
So I think there is nothing we can do here, I think it's probably iOS closing the app in background due to memory, reboot, os update or anything.
Signal 5 if I am correct means `# Input/output error` can be anything.
Do other crashes show up normally?

**Comment by peacechen** [comment]
Other errors do show up correctly.  This was an oddball event that I have no other insight into and am trying to determine if a fix is needed.  Thanks for looking into this.
