### ISSUE TITLE
Configure for CI services like Semaphore

### ISSUE THREAD

**Issue by emilkarl** [getsentry/react-native-sentry#458]
How should I configure this to able to run tests through services like Semaphore. At the moment it tries to run the Wizard during `yarn install` even tho `SKIP_WIZARD_CONNECT` is true.

Is the `sentry.properties` files supposed to be added to the repo with tokens or how do people solve this? I don't want to have auth tokens etc in the repo.

Would be happy if someone had any guidelines for this. Cheers!

**Comment by HazAT** [comment]
So you should treat `sentry.properties` as it was your `.env` file.
You shouldn't probably add it to your vcs but it has to be available on your build machine.
There are workarounds where you don't need the file and you can use env vars directly but this needs changes in the run script in Xcode / gradle.
