### ISSUE TITLE
[Question] Code-Push version for both iOS and Android

### ISSUE THREAD

**Issue by LuisRizo** [getsentry/react-native-sentry#459]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.9.4
6.1.0
/Users/luis
└── (empty)
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

My app has different CodePush releases on Android and on iOS. iOS is ahead by 12 code-push releases. So Android has a label of `v2.1.10-codepush:v23` and iOS has `v2.1.10-codepush:v35`. My question is related to how to handle two different code-push labels for iOS and Android as I have a feeling that Sentry is not separating iOS vs Android when I upload a new source map.

In fact, it causes things like these to happen:
![screen shot 2018-08-07 at 10 53 45 am](https://user-images.githubusercontent.com/25105030/43783630-346d4b7c-9a30-11e8-9ce0-2fbc228c3f7e.png)

In the screenshot above, the last release was made using the Android Code-Push project, and the second one using iOS.

**Steps to reproduce:**
- Create both iOS and Android Code-Push projects
- Make a couple more deployments on one of the platforms during development
- Once the app is stable, code-pushes are done simultaneously (iOS and then Android)
- Upload the source map as explained here: https://docs.sentry.io/clients/react-native/codepush/

**Actual result:**
- Versions are just strings and they don't know the difference between iOS and Android.

**Expected result:**
- The versions are separated by a specific platform.

Imagine the following:
iOS Code-Push is version `v30`, and it's uploaded to Sentry, while Android has a code-push label of `v29`. On the next code-push patch, Android turns `v30` and iOS `v31`. This means that if users on iOS don't immediately update the app, their code-push version is still `v30` but if their app crashes, the source map will be linked to the new javascript, which is the equivalent of `v31` on iOS. This would possibly make the stack-trace useless or broken.

Any thoughts? Should I just try to have iOS and Android on the same version number to prevent this problem?

**Comment by HazAT** [comment]
Hey, so I think this is only an ui problem.
If you click on each release, check the url it should show the full release name.
We only show the truncated one in the UI.

Can you confirm this?
If not, please send a link to your account so I can take a look at it.

**Comment by LuisRizo** [comment]
Hello @HazAT, since both the Android app and iOS app have the same bundle ID, they have the same URL, only difference is, again, the code-push release version. Here's my [Sentry Project's URL](https://sentry.io/hyr/hyrwork-prod/releases/)

**Comment by LuisRizo** [comment]
I also have issues getting my Code-Push source maps to get linked to their appropriate release, but that might deserve a new issue.

**Comment by HazAT** [comment]
OK, I see.
It shouldn't matter if the bundleID are the same as long as the artifacts you upload (sourcemaps) have a different name.

**Comment by LuisRizo** [comment]
According to the outputs of the code-push cli, the sourmaps are called:
- Android: `... --platform android --sourcemap-output build/CodePush/index.android.bundle.map`
- iOS: `... --platform ios --sourcemap-output build/CodePush/main.jsbundle.map`

If that is what you meant, then yes, I'm uploading them separately. Closing this issue as I trust your word :)
