### ISSUE TITLE
Stacktrace merging doesn't work with cxx bridge

### ISSUE THREAD

**Issue by janicduplessis** [getsentry/react-native-sentry#46]
If stacktrace merging is enabled with RN new cxx bridge it causes the app to crash because it tries to swizzle the RCTBatchedBridge class that doesn't exists anymore. RN 0.45 will ship with the cxx bridge as the default and will hit RC soon.

**Comment by HazAT** [comment]
Hey, thanks for giving us the heads up.
We will look into this in the coming days.

**Comment by HazAT** [comment]
This is works in the latest release, though it has some performance issues since it seems `__fbBatchedBridgeConfig` is not available in `release`.

**Comment by jasongonzales23** [comment]
This crash is happening intermittently for us. It was discovered in prod unfortunately. Took us a long time to track down. We are using RN 0.47.2 and RNSentry ^0.22.0.

Here is the debug info from xcode

```
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a510b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000108fc7141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a579625 +[NSException raise:format:] + 197
	3   Whil                                0x000000010835ab8a RCTFatal + 393
	4   Whil                                0x0000000108353dd4 -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 507
	5   CoreFoundation                      0x000000010a498c6c __invoking___ + 140
	6   CoreFoundation                      0x000000010a498b40 -[NSInvocation invoke] + 320
	7   CoreFoundation                      0x000000010a4b0956 -[NSInvocation invokeWithTarget:] + 54
	8   Whil                                0x0000000108357b21 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 553
	9   Whil                                0x0000000108494bbb __36-[RNSentry swizzleInvokeWithBridge:]_block_invoke_2 + 1428
	10  Whil                                0x00000001083a958c _ZN8facebook5react15RCTNativeModule11invokeInnerEjOKN5folly7dynamicE + 270
	11  Whil                                0x00000001083a93e5 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 46
	12  libdispatch.dylib                   0x000000010f018585 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x000000010f039792 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010f01f237 _dispatch_queue_serial_drain + 1022
	15  libdispatch.dylib                   0x000000010f01f98f _dispatch_queue_invoke + 1053
	16  libdispatch.dylib                   0x000000010f01fd31 _dispatch_queue_override_invoke + 374
	17  libdispatch.dylib                   0x000000010f021899 _dispatch_root_queue_drain + 813
	18  libdispatch.dylib                   0x000000010f02150d _dispatch_worker_thread3 + 113
	19  libsystem_pthread.dylib             0x000000010f3cd5a2 _pthread_wqthread + 1299
	20  libsystem_pthread.dylib             0x000000010f3cd07d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Let me know what other info I can provide.

**Comment by HazAT** [comment]
@jasongonzales23 Can link me to the events, I want to take a closer look what exactly is happening?
This should have been fixed long ago.

**Comment by jasongonzales23** [comment]
@HazAT is this what you're looking for: https://sentry.io/share/issue/3134363330342e333430383633353931/

I don't think that will help, but let me know if it does. If not, let me know and I will do more to track it down and/or repro.

**Comment by HazAT** [comment]
Hey, so this crash is whenever react-native has an error in javascript which is not handled, the app crashes with this. This was the case if you are not using the react-native SDK that just happens if you used sentry-swift/sentry-cocoa.
I am pretty sure Sentry isn't the cause of the crash, I also would recommend upgrading to the latest version `0.23.x`.

**Comment by jasongonzales23** [comment]
Hey @HazAT it looks like you may have addressed this: https://github.com/getsentry/react-native-sentry/issues/228. If so, thank you!
