### ISSUE TITLE
react-native link stalls at 

### ISSUE THREAD

**Issue by emilkarl** [getsentry/react-native-sentry#460]
OS:
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

_Platform:_
- [x ]  iOS
- [ ]  Android

`react-native link` and the wizard completes bug it stalls after `Assets have been successfully linked to your project.`

![image](https://user-images.githubusercontent.com/10711/43830912-c27b44e6-9b02-11e8-9810-665619ffd838.png)

**Comment by HazAT** [comment]
I think this issue is not Sentry related, I am not able to reproduce it:
https://github.com/facebook/react-native/issues/19431
