### ISSUE TITLE
[iOS] dSYM is uploaded successfully but can't be found in Sentry Dashboard

### ISSUE THREAD

**Issue by phuochau** [getsentry/react-native-sentry#461]
OS:
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

_Platform:_
- [x ]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.6.0
5.3.0
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
    maxMessageLength: 50000
}).install()
```

---
Hi all,
I have following issue:

Currently I can integrate react-native-sentry with iOS and Android successfully. But I have a problem that uploaded dSYM can't be found on Sentry Dashboard

_Uploaded_
[![Screenshot from Gyazo](https://gyazo.com/16955fab027d1344cc7d903bdfc3586c/raw)](https://gyazo.com/16955fab027d1344cc7d903bdfc3586c)

_Dashboard_
[![Screenshot from Gyazo](https://gyazo.com/d243f74e5e2740fc12014c2f2c40012a/raw)](https://gyazo.com/d243f74e5e2740fc12014c2f2c40012a)

_I have enabled Reprocessing Active as well_
[![Screenshot from Gyazo](https://gyazo.com/79bcbff30cbbaa7f9a64eeffdeba34cc/raw)](https://gyazo.com/79bcbff30cbbaa7f9a64eeffdeba34cc)

**Steps to reproduce:**
- Open Xcode
- Run Command + B

**Actual result:**
- dSYM can't be found in Sentry Dashboard

**Expected result:**
- dSYM can be found in Sentry Dashboard

Thanks so much

**Comment by phuochau** [comment]
@HazAT I have enabled it already
[![Screenshot from Gyazo](https://gyazo.com/8e52c5e0a0058d1be1734f0acc872276/raw)](https://gyazo.com/8e52c5e0a0058d1be1734f0acc872276)

**Comment by phuochau** [comment]
@HazAT I have enabled it already

[![Screenshot from Gyazo](https://gyazo.com/472b1b50c2be04e52004f6b1f7476386/raw)](https://gyazo.com/472b1b50c2be04e52004f6b1f7476386)

**Comment by HazAT** [comment]
Can you run this command in the `iOS` folder locally after you build and attach the log output?
```
export SENTRY_PROPERTIES=sentry.properties
export SENTRY_LOG_LEVEL=debug
./sentry-cli upload-dsym
```

**Comment by phuochau** [comment]
@HazAT I have checked `$DWARF_DSYM_FOLDER_PATH` variable and can see dSYM in that folder. My project is React Native project. Thanks

```
export SENTRY_PROPERTIES=sentry.properties
export SENTRY_LOG_LEVEL=debug
../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
Warning: No paths were provided.
[INFO] sentry_cli::api request POST https://sentry.io/api/0/projects/yojee-limited/yojeedriver-internal/reprocessing/
[INFO] sentry_cli::api using token authentication
[INFO] sentry_cli::api > POST /api/0/projects/yojee-limited/yojeedriver-internal/reprocessing/ HTTP/1.1
[INFO] sentry_cli::api > Host: sentry.io
[INFO] sentry_cli::api > Accept: */*
[INFO] sentry_cli::api > Connection: TE
[INFO] sentry_cli::api > TE: gzip
[INFO] sentry_cli::api > User-Agent: sentry-cli/1.30.3
[INFO] sentry_cli::api > Authorization: Bearer 1ab66cc7***
[INFO] sentry_cli::api < HTTP/1.1 200 OK
[INFO] sentry_cli::api < Server: nginx
[INFO] sentry_cli::api < Date: Thu, 09 Aug 2018 23:48:59 GMT
[INFO] sentry_cli::api < Content-Length: 0
[INFO] sentry_cli::api < Connection: keep-alive
[INFO] sentry_cli::api < X-XSS-Protection: 1; mode=block
[INFO] sentry_cli::api < Content-Language: en
[INFO] sentry_cli::api < X-Content-Type-Options: nosniff
[INFO] sentry_cli::api < Vary: Accept-Language, Cookie
[INFO] sentry_cli::api < Allow: POST, OPTIONS
[INFO] sentry_cli::api < X-Frame-Options: deny
[INFO] sentry_cli::api < X-Served-By: web-c401c6a4
[INFO] sentry_cli::api < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
[INFO] sentry_cli::api response: 200
[INFO] sentry_cli::api body:
```

**Comment by HazAT** [comment]
@phuochau Sorry can you run the command again with the path 😬 
```
../node_modules/@sentry/cli/bin/sentry-cli upload-dsym $DWARF_DSYM_FOLDER_PATH
```

**Comment by phuochau** [comment]
@HazAT Thanks so much, based on your suggestion, I can update my script and it can run successfully for multiple schemes with multiple configuration

```
export SENTRY_PROPERTIES="${SENTRY_PROPERTIES}"
../node_modules/@sentry/cli/bin/sentry-cli upload-dsym "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"
```

*Note*: I configure `SENTRY_PROPERTIES` in Used-Defined for each Scheme.
