### ISSUE TITLE
Any way to ignore garbage error?

### ISSUE THREAD

**Issue by Komalov** [getsentry/react-native-sentry#462]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Config:

```
Sentry.config('https://...@sentry.io/...').install()
```
---
I have following issue:
Error like __Attempted to dereference garbage pointer__ can't be ignored

It makes noise in my issue log, so I want to avoid it. I realized that ignoreErrors doesn't work in react-native, so I decide to create this util
```
Sentry.setShouldSendCallback(({ message }) => !ignoreErrors.some(e => message.indexOf(e) !== -1))
```
near with my Sentry.config(...).install(), but it won't work

__Attempted to dereference garbage pointer__ was [faced](https://github.com/getsentry/react-native-sentry/issues/244) before, as I understand it's to be fixed later and it's not fault of my app.

Maybe I understand setShouldSendCallback mission wrong, but could you please provide some help to avoid this errors in my project issues?

**Comment by Komalov** [comment]
ignoreErrors is just a plain array
```
const ignoreErrors = [
  'Attempted to dereference garbage pointer',
  'C++ exception',
]
```

**Comment by HazAT** [comment]
So the problem is, that this is a native error and `setShouldSendCallback` only works on the JS side :/ 

As a workaround, you can ignore errors in your projects settings directly in Sentry.
Hope this helps.
