### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by Rewieer** [getsentry/react-native-sentry#47]
I can't install the last version of Sentry (0.8) on Windows. I got the following error. It doesn't want to execute the following commands : 

`
sentry-cli-binary@1.9.0 preinstall D:\...\node_modules\.staging\sentry-cli-binary-49cd104f
./bin/install-sentry-cli
`

**Comment by HazAT** [comment]
Actually, we don't support windows yet and I am not sure if we ever will be, at least natively.
It should use raven-js by default.
But now to the issue, this is actually a sentry-cli issue I have created an issue there.
