### ISSUE TITLE
0.8.1 android: couldn't find key level in dynamic object

### ISSUE THREAD

**Issue by jpaas** [getsentry/react-native-sentry#48]
This looks like the same problem as #43 and #45. It occurs when calling captureBreadcrumb on Android.

**Comment by jpaas** [comment]
Looks like its also a problem with email, userID and username on setUserContext too. Only on Android though.

**Comment by HazAT** [comment]
This should be fixed in version 0.8.4

**Comment by ekeuus** [comment]
Still happens when using setExtraContext on 0.9.1.

**Comment by jhilden** [comment]
Also seeing this.  Reported sentry client SDK is `sentry-java:android` Version `1.0.0-beta-141a1`

**Comment by RobertWSaunders** [comment]
Getting this when calling `Sentry.captureMessage('TEST message', null);` with `react-native-sentry": "^0.11.6"`

**Comment by HazAT** [comment]
Probably dup https://github.com/getsentry/react-native-sentry/issues/87

**Comment by benhowes** [comment]
@HazAT I suspect you might be right that this is related, we've seen a few different cases of keys not found from calls to `getString` in the java level. Really keen to get this sorted, so please let me know if there's any other debug info I can provide.

**Comment by HazAT** [comment]
Fixed in `0.12.5`
