### ISSUE TITLE
Execution failed for task ':react-native-sentry:verifyReleaseResources'.

### ISSUE THREAD

**Issue by hecontreraso** [getsentry/react-native-sentry#482]
Any help will be greatly appreciated!

OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [X]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v9.1.0
5.8.0-next.0
Operations@0.0.1 /Users/esteban/Desktop/kiwi/opsapp
├── array.prototype.flatmap@1.2.1
├── babel-plugin-transform-do-expressions@6.22.0
├── base-64@0.1.0
├── dateformat@3.0.3
├── expo@23.0.4
├── node-time-ago@1.0.0
├── prop-types@15.6.2
├── react@16.5.0
├── react-native@0.57.1
├── react-native-actionsheet@2.3.0
├── react-native-android-location-services-dialog-box@2.7.0
├── react-native-camera@1.2.0
├── react-native-device-info@0.22.5
├── react-native-maps@0.21.0
├── react-native-modal-selector@0.0.27
├── react-native-onesignal@3.2.7
├── react-native-qrcode-scanner@1.1.0
├── react-native-safari-view@2.1.0
├── react-native-sentry@0.38.1
├── react-navigation@2.16.0
├── react-redux@5.0.6
├── redux@3.7.2
├── redux-persist@5.9.1
├── redux-thunk@2.2.0
├── remote-redux-devtools@0.5.12
├── rn-sliding-button@1.1.5
├── rn-sliding-up-panel@1.1.7
├── time-ago@0.2.1
├── url-parse@1.2.0
└── validate.js@0.12.0
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

Build fails when I run `./gradlew assembleRelease` 

**Steps to reproduce:**
- Installed sentry following the instructions. It fails with the following error: 

```
[INFO] sentry_cli::api < Connection: keep-alive
[INFO] sentry_cli::api < X-XSS-Protection: 1; mode=block
Source Map Upload Report
[INFO] sentry_cli::api < Content-Language: en
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
[INFO] sentry_cli::api < X-Content-Type-Options: nosniff
    ~/index.android.bundle.map
[INFO] sentry_cli::api < Vary: Accept-Language, Cookie
[INFO] sentry_cli::api < Allow: GET, POST, HEAD, OPTIONS
[INFO] sentry_cli::api < X-Frame-Options: deny
[INFO] sentry_cli::api < X-Served-By: web-ee8f0660
[INFO] sentry_cli::api < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
[INFO] sentry_cli::api response: 201
[INFO] sentry_cli::api body: {"sha1": "0996f671d9ec00b9f9e678305694caa2c7a78b3c", "dist": "74", "name": "~/index.android.bundle.map", "dateCreated": "2018-09-25T16:03:24.696Z", "headers": {"Content-Type": "application/octet-stream"}, "id": "131080816", "size": 4891624}

error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
/Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
    
/Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.
    
/Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values-v26/values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
    
/Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontStyle not found.
    
/Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/font not found.
    
/Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontWeight not found.
    
error: failed linking references.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-sentry:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 57s
193 actionable tasks: 23 executed, 170 up-to-date
```

**Comment by xufeipyxis** [comment]
Same issue here, I switched to Windows to do the Android compiling as a temporary solution.

**Comment by hecontreraso** [comment]
@xufeipyxis Solved by updating Sentry to 0.39.0

**Comment by HazAT** [comment]
Ok, closing this for now, we switched to using newer Android build tools with `0.39.0`

**Comment by Chirag069** [comment]
> Any help will be greatly appreciated!
> 
> OS:
> 
> * [ ]   Windows
> * [x]   MacOS
> * [ ]   Linux
> 
> _Platform:_
> 
> * [ ]   iOS
> * [x]   Android
> 
> Output of `node -v && npm -v && npm ls --prod --depth=0`
> 
> ```
> v9.1.0
> 5.8.0-next.0
> Operations@0.0.1 /Users/esteban/Desktop/kiwi/opsapp
> ├── array.prototype.flatmap@1.2.1
> ├── babel-plugin-transform-do-expressions@6.22.0
> ├── base-64@0.1.0
> ├── dateformat@3.0.3
> ├── expo@23.0.4
> ├── node-time-ago@1.0.0
> ├── prop-types@15.6.2
> ├── react@16.5.0
> ├── react-native@0.57.1
> ├── react-native-actionsheet@2.3.0
> ├── react-native-android-location-services-dialog-box@2.7.0
> ├── react-native-camera@1.2.0
> ├── react-native-device-info@0.22.5
> ├── react-native-maps@0.21.0
> ├── react-native-modal-selector@0.0.27
> ├── react-native-onesignal@3.2.7
> ├── react-native-qrcode-scanner@1.1.0
> ├── react-native-safari-view@2.1.0
> ├── react-native-sentry@0.38.1
> ├── react-navigation@2.16.0
> ├── react-redux@5.0.6
> ├── redux@3.7.2
> ├── redux-persist@5.9.1
> ├── redux-thunk@2.2.0
> ├── remote-redux-devtools@0.5.12
> ├── rn-sliding-button@1.1.5
> ├── rn-sliding-up-panel@1.1.7
> ├── time-ago@0.2.1
> ├── url-parse@1.2.0
> └── validate.js@0.12.0
> ```
> 
> Config:
> 
> ```
> Sentry.config('https://...@sentry.io/...', {
> ....
> }).install()
> ```
> 
> I have following issue:
> 
> Build fails when I run `./gradlew assembleRelease`
> 
> **Steps to reproduce:**
> 
> * Installed sentry following the instructions. It fails with the following error:
> 
> ```
> [INFO] sentry_cli::api < Connection: keep-alive
> [INFO] sentry_cli::api < X-XSS-Protection: 1; mode=block
> Source Map Upload Report
> [INFO] sentry_cli::api < Content-Language: en
>   Minified Scripts
>     ~/index.android.bundle (sourcemap at index.android.bundle.map)
>   Source Maps
> [INFO] sentry_cli::api < X-Content-Type-Options: nosniff
>     ~/index.android.bundle.map
> [INFO] sentry_cli::api < Vary: Accept-Language, Cookie
> [INFO] sentry_cli::api < Allow: GET, POST, HEAD, OPTIONS
> [INFO] sentry_cli::api < X-Frame-Options: deny
> [INFO] sentry_cli::api < X-Served-By: web-ee8f0660
> [INFO] sentry_cli::api < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> [INFO] sentry_cli::api response: 201
> [INFO] sentry_cli::api body: {"sha1": "0996f671d9ec00b9f9e678305694caa2c7a78b3c", "dist": "74", "name": "~/index.android.bundle.map", "dateCreated": "2018-09-25T16:03:24.696Z", "headers": {"Content-Type": "application/octet-stream"}, "id": "131080816", "size": 4891624}
> 
> error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
> error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
> /Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
>     
> /Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.
>     
> /Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values-v26/values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
>     
> /Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontStyle not found.
>     
> /Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/font not found.
>     
> /Users/esteban/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/bc59160776ffb4e6355511fed330ca22/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontWeight not found.
>     
> error: failed linking references.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-sentry:verifyReleaseResources'.
> > com.android.ide.common.process.ProcessException: Failed to execute aapt
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 57s
> 193 actionable tasks: 23 executed, 170 up-to-date
> ```

i have fetch same issu bat react-native -sha1 libreay
