### ISSUE TITLE
Can't build on Windows for Android release

### ISSUE THREAD

**Issue by xufeipyxis** [getsentry/react-native-sentry#483]
OS:
- [x]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.12.0
6.4.1
```

---

I got the error during a release build:

```
FAILURE: Build failed with an exception.

* Where:
Script 'C:\\node_modules\react-native-sentry\sentry.gradle' line: 176

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssetsreleaseSentryUpload'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

I'm compiling by `gradlew.bat assembleRelease` but I don't know where to add `--stacktrace`. 
If I open the project by Android Studio I got the same error.

I have to comment out this line for my urgent release:
```
//apply from: "../../node_modules/react-native-sentry/sentry.gradle"
```

**Comment by HazAT** [comment]
You should be able to add it there `gradlew.bat assembleRelease --stacktrace`

**Comment by Victorams** [comment]
I had the same issue. I managed a local workaround by setting a static path to my local sentry cli.executable in 'sentry.properties' (e.g. where it was 'cli.executable=node_modules/@sentry/cli/bin/sentry-cli' I changed to 'cli.executable=C:/Projetos/app/node_modules/@sentry/cli/bin/sentry-cli').

**Comment by HazAT** [comment]
Thanks, @Victorams I am closing this right now.
