### ISSUE TITLE
react-native link asks for DSN, but doesn't seem to do anything with it

### ISSUE THREAD

**Issue by jpaas** [getsentry/react-native-sentry#49]
Every time I run `react-native link react-native-sentry`, it asks for my DSN and I have a number of questions/concerns with this:

1. I believe we are supposed to have different sentry projects for iOS vs Android. So which one is it asking for?
2. Some hints would be good, like whether it wants the public or private one and where to find it.
3. In the end, as far as I can tell, I can enter anything I like and it never gets used. Thankfully.

So is it a bug that it asks at all?

**Comment by mitsuhiko** [comment]
Yeah, it should not be asking that unless it already has it. I will look at why that might be the case. Also we will change it so that it asks for a different DSNs optionally.
