### ISSUE TITLE
Upgraded project to React Native 0.56.  Sentry build fails on Android "actual and formal argument lists differ in length"

### ISSUE THREAD

**Issue by peacechen** [getsentry/react-native-sentry#490]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v9.3.0
5.5.1
/Users/me
└── (empty)
```

Config:

```
Sentry.config('https://...@sentry.io/...' ).install()
```

---
I have following issue:

Building for Android returns this error:

> Error:(53, 9) error: constructor RNSentryPackage in class RNSentryPackage cannot be applied to given types;
> required: no arguments
> found: MainApplication
> reason: actual and formal argument lists differ in length
> 

**Steps to reproduce:**
Upgrade project to React Native 0.56.1

MainApplication.java contains
```
        new RNNotificationsPackage(MainApplication.this),
```

**Actual result:**
Build error

**Expected result:**
Successful build

**Comment by peacechen** [comment]
The RNSentryPackage class doesn't have a constructor:
https://github.com/getsentry/react-native-sentry/blob/master/android/src/main/java/io/sentry/RNSentryPackage.java#L14

Somehow either the updated versions of RN 0.56, Gradle 4.6, or Android SDK 28.x have removed default constructors.  Not sure exactly what it is, but something involving constructors has changed.

**Comment by HazAT** [comment]
This is actually a bug, I will release a new version tomorrow with a fix for this.

**Comment by peacechen** [comment]
Yes it's working great.  Thanks @HazAT

**Comment by peacechen** [comment]
@cihati

Remove the argument and simply call 
```
new RNSentryPackage() 
```

**Comment by cihati** [comment]
Yes, this did solve the issue -- thanks @peacechen and @HazAT  =)
