### ISSUE TITLE
How to unset user context?

### ISSUE THREAD

**Issue by hkan** [getsentry/react-native-sentry#492]
Hi there,

*I deleted the default issue template because this is a question or maybe a suggestion rather than an issue.*

I realized that there is a method called `setUserContext` which is super useful for bunch of reasons; but why isn't there a `unsetUserContext` method? I mean, as far as I can see from source codes, there isn't *any* way to clear user information on the air. This is definitely needed because, you know, people log out from applications.

What might be the workaround for this, until someone actually creates the `unsetUserContext`?

**Comment by KabirKang** [comment]
I tried passing in null but then it gave me a message on the sentry dash saying `Discarded invalid value for parameter 'user'`

**Comment by HazAT** [comment]
You have to use `clearContext` to clear all context, there is currently no other way of doing this.
