### ISSUE TITLE
`beforeBreadcrumb` hook 

### ISSUE THREAD

**Issue by KevinColemanInc** [getsentry/react-native-sentry#494]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

I have following issue:

I am having the same issue as this guy in the `sentry-javascript` repo.
https://github.com/getsentry/sentry-javascript/issues/1490

**Expected result:**
Does the `react-native-sentry` package support this feature to modify the breadcrumbs? If so, where is the documentation?

**Comment by HazAT** [comment]
The react-native SDK doesn't conform the unified SDK API yet, you have to use `setShouldSend` callback and modify the event / breadcrumbs in there.
See: https://docs.sentry.io/clients/react-native/config/

**Comment by KevinColemanInc** [comment]
Any chance you could give me an example?

**Comment by cruzach** [comment]
@HazAT ,

Has the RN SDK conformed to the JS SDK yet? If not, are there plans to add the `beforeBreadcrumb` hook to the react-native SDK in the future?

Thanks!
Charlie
