### ISSUE TITLE
iOS - fatal error: 'RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by javi10823** [getsentry/react-native-sentry#498]
OS:
- [ ]  Windows
- [X ]  MacOS
- [ ]  Linux

_Platform:_
- [X ]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v9.11.1
6.1.0
HomeChefApp@ /Users/javierolivieri/projects/foxbox/homechef/react_mobile
├── appcenter@1.9.0
├── appcenter-analytics@1.9.0
├── appcenter-crashes@1.9.0
├── install@0.12.2
├── lodash.isempty@4.4.0
├── lodash.omit@4.5.0
├── moment@2.22.2
├── prettier@1.14.3
├── qs@6.5.2
├── react@16.3.1
├── UNMET PEER DEPENDENCY react-native@0.55.4
├── react-native-amplitude-analytics@0.2.6
├── react-native-communications@2.2.1
├── react-native-config@0.11.5
├── react-native-sentry@0.39.1
├── react-native-splash-screen@3.1.1
├── react-native-svg@8.0.8
├── react-native-vector-icons@6.0.2
├── react-navigation@2.14.0
├── react-navigation-material-bottom-tabs@0.3.0
├── react-redux@5.0.7
├── redux@4.0.0
├── redux-thunk@2.3.0
└── simple-markdown@0.4.2

npm ERR! peer dep missing: react-native@>=0.56.0, required by react-native-sentry@0.39.1
npm ERR! invalid: xcode@1.0.1-dev /Users/javierolivieri/projects/foxbox/homechef/react_mobile/node_modules/@sentry/wizard/node_modules/xcode
npm ERR! peer dep missing: react@16.0.0-alpha.6, required by react-native-screens@1.0.0-alpha.9
npm ERR! peer dep missing: react-native@^0.44.1, required by react-native-screens@1.0.0-alpha.9
```

I have following issue:

/node_modules/react-native-sentry/ios/RNSentryEventEmitter.h:4:9: fatal error: 'RCTEventEmitter.h' file not found
#import "RCTEventEmitter.h"

**Steps to reproduce:**
Follow readme install instructions

**Actual result:**
Build Failed

**Expected result:**
Build Successfull

**Comment by se-bastiaan** [comment]
From the README:
> `react-native-sentry >= 0.39.0` requires `react-native >= 0.56.0`

You're using `react-native-sentry@0.39.1` and `react-native@0.55.4`.

**Comment by javi10823** [comment]
> From the README:
> 
> > `react-native-sentry >= 0.39.0` requires `react-native >= 0.56.0`
> 
> You're using `react-native-sentry@0.39.1` and `react-native@0.55.4`.

Hi Sebastian, I'm trying with 0.38.3

"react-native-sentry": "0.38.3",

I'm receive same error

**Comment by javi10823** [comment]
With **react-native-sentry@0.38.3**

same issue

v9.11.1
6.1.0
HomeChefApp@ /Users/javierolivieri/projects/foxbox/homechef/react_mobile
├── appcenter@1.9.0
├── appcenter-analytics@1.9.0
├── appcenter-crashes@1.9.0
├── lodash.isempty@4.4.0
├── lodash.omit@4.5.0
├── moment@2.22.2
├── prettier@1.14.3
├── qs@6.5.2
├── react@16.3.1
├── react-native@0.55.4
├── react-native-amplitude-analytics@0.2.6
├── react-native-communications@2.2.1
├── react-native-config@0.11.5
├── react-native-sentry@0.38.3
├── react-native-splash-screen@3.1.1
├── react-native-svg@8.0.8
├── react-native-vector-icons@6.0.2
├── react-navigation@2.14.0
├── react-navigation-material-bottom-tabs@0.3.0
├── react-redux@5.0.7
├── redux@4.0.0
├── redux-thunk@2.3.0
└── simple-markdown@0.4.2

npm ERR! peer dep missing: eslint@^3.17.0 || ^4.0.0, required by eslint-plugin-react-native@3.2.1
npm ERR! peer dep missing: react@16.0.0-alpha.6, required by react-native-screens@1.0.0-alpha.9
npm ERR! peer dep missing: react-native@^0.44.1, required by react-native-screens@1.0.0-alpha.9

**Comment by se-bastiaan** [comment]
What are the header search paths in Xcode for the react-native-sentry library?

**Comment by javi10823** [comment]
> What are the header search paths in Xcode for the react-native-sentry library?

I run this steps, and now it's working

> Do NOT use CocoaPods for react-native-sentry
> Follow the standard install steps:
> a) yarn react-native-sentry
> b) react-native link react-native-sentry
> If your Podfile was modified by the setup script, remove any reference of ReactNativeSentry
> Open Xcode and drag node_modules/react-native-sentry/ios/RNSentry.xcodeproj into your project's Libraries directory
> Open your project's "Linked Frameworks and Libraries" and add libRNSentry.a

**Comment by HazAT** [comment]
I am closing this since your issue seems to be fixed.

**Comment by shredding** [comment]
Mine is not fixed. I have the same probleme and there is no RNSentry.xcodeproj and when i drop other xcodeproj files i get other errors.
