### ISSUE TITLE
Sentry.clearContext() blocks

### ISSUE THREAD

**Issue by messense** [getsentry/react-native-sentry#51]
Logout saga (I am using [redux-saga](https://github.com/redux-saga/redux-saga)):

```javascript
export function * logout() {
  API.setHeader('X-Token', '');
  yield call(AsyncStorage.removeItem, 'currentUser');
  Sentry.clearContext();
  alert('test clear');
}
```

The `alert('test clear')` never gets executed, remove the `Sentry.clearContext();` then it pops up an alert.

OS: iOS & Android
RN version: 0.44
react-native-sentry version: 0.8.1

**Comment by messense** [comment]
The `setUserContext` method on raven-js supports call `setUserContext()` with no argument to clear user context, but `react-native-sentry` seems not supporting that so I have to call `clearContext()`.

**Comment by messense** [comment]
```javascript
   static clearContext(clearContext) {
        if (Sentry.isNativeClientAvailable()) Sentry._nativeClient.clearContext();
        // Sentry._ravenClient.clearContext();
    }
```

The problem seems not related to `nativeClient` but `ravenClient`, comment `Sentry._ravenClient.clearContext();` works fine.

**Comment by messense** [comment]
BTW, the `setUserContext` of `raven-js` [documentation](https://docs.sentry.io/clients/javascript/#adding-context) seems advice us to pass user id as `id` while `react-native-sentry` requires `userID`.

**Comment by jordanmkoncz** [comment]
I was planning to use `clearContext()` from within a logout saga just like you, so this will also be an issue for me. Hopefully it's fixed soon.

**Comment by jordanmkoncz** [comment]
@HazAT, just confirming that `Sentry.clearContext()` appears to be working fine for me in `0.14.0`, thanks for the fix.

**Comment by antoinerousseau** [comment]
Yeah but how do we clear the user context without other context infos?
With Raven it was `Raven.setUserContext()` but with Sentry it crashes because it takes an object. Should we call `Sentry.setUserContext({})`?

**Comment by HazAT** [comment]
@antoinerousseau If it works like that, yes use `Sentry.setUserContext({})`
