### ISSUE TITLE
How to ignore caught exceptions?

### ISSUE THREAD

**Issue by sryze** [getsentry/react-native-sentry#517]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v11.4.0
6.4.1
react-native-sentry: 0.40.2
react-native: 0.57.2
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
        deactivateStacktraceMerging: false,
        logLevel: SentryLog.Debug,
        disableNativeIntegration: false,
        handlePromiseRejection: true
}).install()
```
Sometimes I see errors that are thrown by my code inside try {...} catch blocks, for example after checking the result of an `async` function (to handle it in the catch block below)

```js
try {
    const data = await API.get('some_api');
    if (data.msg) {
        throw new Error(data.msg);
    }
} catch (error) {
    // error handling code
}
```

Is there a way to ignore such errors because they are already handled/caught?

**Comment by HazAT** [comment]
I think setting:
```
instrument: {
    'tryCatch': false, // Instruments timers and event targets
}
```
should fix this.
