### ISSUE TITLE
Gradle v5.0 - execute() method renamed to exec()

### ISSUE THREAD

**Issue by OleksandrKucherenko** [getsentry/react-native-sentry#520]
https://github.com/getsentry/react-native-sentry/blob/96f09af56c6a85e1548acf6fea45be6ef3d44a07/sentry.gradle#L176-L179

In latest Gradle Exec task has API changes. `execute()` method is no more available and should be replaced by `exec()`;

Solution:
- its a wrong approach to call tasks directly from code, gradle has tasks graph and execute tasks according to it. Sentry script should just configure proper dependencies between the tasks and use one of the gradle tasks directives: finalizedBy, mustRunAfter, onlyIf, etc. (https://docs.gradle.org/current/dsl/org.gradle.api.Task.html)

**Comment by jussirantala** [comment]
Could you make a PR?

**Comment by OleksandrKucherenko** [comment]
@jussirantala ^

**Comment by OleksandrKucherenko** [comment]
@HazAT ^ - can you review the PR and merge?
