### ISSUE TITLE
Exceptions get swallowed on Android

### ISSUE THREAD

**Issue by christophermark** [getsentry/react-native-sentry#522]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [X]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`
```
v8.12.0
5.2.0

react-native-sentry@0.40.2
```

---
I have following issue:

**A crash on Android is getting swallowed by Sentry.**
Seems to be a behavior change between react-native-sentry `0.38.3` --> `0.40.2 (latest)`. Earlier version 38 throws and reports the error as expected, whereas the latest version swallows it.

### Steps to reproduce
I had a line of code which causes a crash on Android: 
```
var foo = 10;
var bar = {...foo};
```

Upgrading `react-native-sentry` from `0.38.3` to the latest `0.40.2` changed the behavior where the app doesn't crash and the error is not reported to Sentry. So to reproduce:

- Upgrade to 0.40.2
- Manually log a separate event to Sentry
  - The caught exception is shown in the _breadcrumbs_ 

### Actual result
- The exception gets caught by Sentry and the app doesn't crash as it's supposed to
- The exception doesn't get reported to Sentry
  - Instead it's included in the breadcrumbs

<details><summary>Screenshot of the error within the breadcrumbs of another event</summary>

![image](https://user-images.githubusercontent.com/6303781/50303059-f6291a00-0459-11e9-89cf-760f2ef8c90e.png)
</details>
<br>

_Important detail here is that I had to manually push an event to Sentry to discover that there was a crash happening in the background. Is Sentry wrapping all errors in a `try-catch` and not re-throwing said errors?_

### Expected result
- Downgrade to `0.38.3` to reproduce expected result
- The app should crash
- Sentry should report this crash/exception

<details><summary>Screenshot of the error within the breadcrumbs of another event</summary>

![image](https://user-images.githubusercontent.com/6303781/50303148-32f51100-045a-11e9-8a9c-15d6e0507769.png)
</details>

**Comment by derN3rd** [comment]
Hey @christophermark, did you find a solution or did u just downgrade back to 0.38.3?
We are having the same problem (#470)

**Comment by leedan77** [comment]
In 1.3.0, this is still happening.
