### ISSUE TITLE
Disable sourcemaps file upload for debug builds

### ISSUE THREAD

**Issue by sourabhv** [getsentry/react-native-sentry#525]
Is there a way to disable uploading sourcemaps for android and iOS debug builds?

I can add add `if [ "${CONFIGURATION}" = "Release" ]; then ... ` check for ios run script but I don't understand why does that even run in debug scheme

**Comment by OleksandrKucherenko** [comment]
```gradle
/* Disable Sentry tasks for test environments / flavors. */
gradle.projectsEvaluated {
    // Grab all build types and product flavors
    def buildTypes = android.buildTypes.collect { type -> type.name }
    def productFlavors = android.productFlavors.collect { flavor -> flavor.name }

    // When no product flavors defined, use empty
    if (!productFlavors) productFlavors.add("")

    productFlavors.each { flavor ->
        buildTypes.each { buildt ->
            def isEnabled = !isTestEnvironment(flavor.toString())
            /* disable sentry tasks for test environments */
            [
                    "bundle${flavor.capitalize()}${buildt.capitalize()}JsAndAssets${flavor}-${buildt}SentryUpload",
                    "bundle${flavor.capitalize()}${buildt.capitalize()}JsAndAssets${flavor}-${buildt}SentryUploadCleanUp",
            ].each { name ->
                def task = tasks.findByPath(name)
                if (null != task) {
                    task.enabled = isEnabled
                    task.group = "sentry.io"
                }
            }
        }
    }
}
```

**Comment by sorrat** [comment]
Shorter variant:

```groovy
gradle.projectsEvaluated {
    def tasksToSkip = project.tasks.matching {
        it.name.contains("SentryUpload") &&
        it.name.contains("Debug")
    }
    tasksToSkip.all { enabled = false }
}
```

**Comment by jussirantala** [comment]
> A shorter version:
> 
> ```groovy
> gradle.projectsEvaluated {
>     def tasksToSkip = project.tasks.matching {
>         it.name.contains("SentryUpload") &&
>         it.name.contains("Debug")
>     }
>     tasksToSkip.all { enabled = false }
> }
> ```

Where do I put these lines?

**Comment by OleksandrKucherenko** [comment]
@jussirantala you can place this code into `app/build.gradle`

**Comment by jussirantala** [comment]
> @jussirantala you can place this code into `app/build.gradle`

I added it at the end of the file but nothing changed

**Comment by gianpaj** [comment]
Since version `0.42.0` sourcemap files are not uploaded by default on Android.

https://github.com/getsentry/react-native-sentry/blob/master/CHANGELOG.md#0420

I believe this is the PR but I'm not 100% sure:
https://github.com/getsentry/react-native-sentry/pull/548

**Comment by OleksandrKucherenko** [comment]
@gianpaj it was in PR https://github.com/getsentry/react-native-sentry/pull/546

**Comment by gianpaj** [comment]
cool, thanks @OleksandrKucherenko

**Comment by jstheoriginal** [comment]
Any idea how to also prevent uploading to sentry just from running UnitTests? Every prod release it uploads twice. first for the job running the unit tests and then secondly for the actual app bundle job.

**Comment by AlirezaHadjar** [comment]
> > [@jussirantala](https://github.com/jussirantala) you can place this code into `app/build.gradle`
> 
> I added it at the end of the file but nothing changed

Just in case, the code @sorrat mentioned should be added after this line:
`apply from: new File(["node", "--print", "require('path').dirname(require.resolve('@sentry/react-native/package.json'))"].execute().text.trim(), "sentry.gradle")`

So it would be like this:

![Image](https://github.com/user-attachments/assets/6abc92e4-d84e-43ce-8871-e5e9877da5ee)

**Comment by krystofwoldrich** [comment]
Hello everyone,
this is quite an old issue. Since 2019 the SDK evolved and not automatic source maps upload can be disabled by `export SENTRY_DISABLE_AUTO_UPLOAD=true` env both for iOS and Android.

Read more at https://docs.sentry.io/platforms/react-native/sourcemaps/#disable-automatic-upload
