### ISSUE TITLE
Sentry.lastEventId() always returns null

### ISSUE THREAD

**Issue by saadq** [getsentry/react-native-sentry#527]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.12.0
6.4.1
Example-App@0.0.1 /Users/me/Projects/Example
├── @expo/vector-icons@8.0.0
├── aws-amplify@1.1.8
├── date-fns@1.29.0
├── expo@30.0.1
├── formik@1.3.1
├── iex-api@0.0.3
├── numeral@2.0.6
├── polished@2.3.0
├── react@16.3.1
├── react-native@0.55.4
├── react-native-dotenv@0.2.0
├── react-navigation@2.18.2
├── react-navigation-redux-helpers@2.0.8
├── react-redux@5.0.7
├── redux@4.0.1
├── redux-saga@0.16.2
├── sentry-expo@1.11.0
├── victory-native@31.0.0
└── yup@0.26.6
```

Config:

```ts
import Sentry from 'sentry-expo';
import { SENTRY_DSN } from 'react-native-dotenv';

Sentry.config(SENTRY_DSN).install();
```

---

**I have the following issue:**

After capturing a message or an exception, `Sentry.lastEventId()` will still return `null`. [According to the docs](https://docs.sentry.io/clients/javascript/usage/#getting-back-an-event-id) however, this should work fine.

**Steps to reproduce:**

```ts
Sentry.captureMessage('Broken!');
console.log(Sentry.lastEventId());
```

**Actual result:**

```ts
null
```

**Expected result:**

```
8f1c81d52296458fa9851df93e3cea16
```

The message IS being sent successfully, so I'm not sure why this is happening.

<img width="1441" alt="screen shot 2018-12-27 at 2 11 46 am" src="https://user-images.githubusercontent.com/5678694/50470066-3538fd00-097d-11e9-80ec-43007a5d38a2.png">

<img width="1441" alt="screen shot 2018-12-27 at 2 14 28 am" src="https://user-images.githubusercontent.com/5678694/50470053-28b4a480-097d-11e9-85af-91658bea1161.png">

**Comment by HazAT** [comment]
Sorry in react-native it works differently.
You need to wait until the event has been sent like:
```
// set a callback after an event was successfully sent
// its only guaranteed that this event contains `event_id` & `level`
Sentry.setEventSentSuccessfully((event) => {
  // can also be called outside this block but maybe null
  // Sentry.lastEventId(); -> returns the last event_id after the first successfully sent event
  // Sentry.lastException(); -> returns the last event after the first successfully sent event
});
```
ref: https://docs.sentry.io/clients/react-native/config/
