### ISSUE TITLE
The line number of the error code does not match the actual number

### ISSUE THREAD

**Issue by yongqianvip** [getsentry/react-native-sentry#528]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

> node v10.14.1
> npm v6.4.1
> react-native v0.55.3
> react-native-sentry v0.38.3

Config:

```
Sentry.config('__MY_DSN__'}).install()
```

---
I have following issue:
_**When an exception occurs, the APP reports the error message to the SENTRY background, but on the website, it does not highlight the right line number of the error code
The sourcemap and jsbundle were uploaded automatically by script in Xcode or AndroidStudio**_ 

**Steps to reproduce:**

> **SOURCE CODE**
<img width="660" alt="sourcecode-mark" src="https://user-images.githubusercontent.com/5046614/50943893-34e64900-14c9-11e9-9e54-1e2be051a2b5.png">

<img width="276" alt="error-red" src="https://user-images.githubusercontent.com/5046614/50944050-db324e80-14c9-11e9-8c38-b9dc1e32fabb.png">

![error-ios](https://user-images.githubusercontent.com/5046614/50943049-ce136080-14c5-11e9-8007-59ba65189032.png)

![android-report](https://user-images.githubusercontent.com/5046614/50895511-497efe80-1441-11e9-9566-3628a26cf36b.png)

**Actual result:**
- I got the right description but a wrong line number of the error code

**Expected result:**
- right description and a right line number of the error code

**Comment by minhducit83** [comment]
same issue

**Comment by yongqianvip** [comment]
Maybe, it is my fault.
The project which i mentioned in this question is a demo, i dropped it, and in another project, it works well, maybe i do something wrong, I am sorry, I will close this issue

**Comment by HazAT** [comment]
It's a long lasting issue with react-native itself generating wrong source maps.
There is not much we can do about it, just always be sure to be on the latest RN version.
