### ISSUE TITLE
debug symbols for libswiftcore missing

### ISSUE THREAD

**Issue by jpaas** [getsentry/react-native-sentry#53]
Using 0.8.1 and sentry-cli 1.9.0, if I create an iOS build and trigger a native crash using `Sentry.nativeCrash`, the event is captured and I see a fairly reasonable stack trace. However the event in sentry.io shows this error:

```
An optional debug symbol file was missing. Collapse
{
  "image_arch": "arm64",
  "image_uuid": "900e59d2-1c9f-3a43-9d3a-e552a289103f",
  "message": "None",
  "image_path": "/private/var/containers/Bundle/Application/A015C776-5F98-49DC-812C-5591B95058C8/KarmaWorkerApp.app/Frameworks/libswiftCore.dylib"
}
```

Should the iOS build be uploading another dsym?

**Comment by HazAT** [comment]
Hey,
No, I am pretty sure you are doing everything correctly if this is the only dsym missing.
We will look into this why we don't get all dsyms even if it's an optional one.

**Comment by HazAT** [comment]
This will be fixed with the next release on sentry.io, we can't do anything here.
https://github.com/getsentry/sentry/pull/5349

**Comment by Mindaugas-Jacionis** [comment]
I have similar issue, just in my case I am using:
react-native-sentry v0.10.0
sentry-cli v1.10.1

Both android and iOS work good and I receive crash reports with pretty nice stack, but in reports from iOS crashes I see these two messages:

A required debug symbol file was missing.
{
  "image_arch": "arm64",
  "image_uuid": "dabaf06f-36cc-3aa6-bd8f-e58da6992f41",
  "message": "None",
  "image_path": "/var/containers/Bundle/Application/0C982856-C522-4B9E-9A49-2B2BEAC66370/MyApp.app/MyApp"
}
An optional debug symbol file was missing.
{
  "image_arch": "arm64",
  "image_uuid": "11d793ca-5bd9-30e2-9b50-d4504a29a22d",
  "message": "None",
  "image_path": "/private/var/containers/Bundle/Application/0C982856-C522-4B9E-9A49-2B2BEAC66370/MyApp.app/Frameworks/Sentry.framework/Sentry"
}

@HazAT I'm not sure if this falls into the same PR you've mentioned, or this is some issue on my side?

**Comment by mitsuhiko** [comment]
@Mindaugas-Jacionis this just means that you need to upload debug symbols.

**Comment by Mindaugas-Jacionis** [comment]
@mitsuhiko But when building my app with xcode I get prompt that debug symbols are generated and uploaded successfully, so do I need to do some additional manual upload? 
That's why I am so confused regarding seeing these error messages in my crash report in sentry.

**Comment by mitsuhiko** [comment]
@Mindaugas-Jacionis are you using bitcode by any chance? Then you need to ingest the debug symbols from ITC.

**Comment by Mindaugas-Jacionis** [comment]
@mitsuhiko yup - I am using bitcode(totally forgot). Any suggestions on automation of this? Fastlane? And how much of an issue this is for me? I do receive crash reports and real good logs, so what is the loss on my side of having these errors(just trying to figure out how fast should I resolve this issue and how critical it is for my case)?

**Comment by mitsuhiko** [comment]
@Mindaugas-Jacionis yeah, fastlane is the way to go for now. We're investigating alternatives but for now that's what you can do.

**Comment by Mindaugas-Jacionis** [comment]
@mitsuhiko thanks for the answers! :) 👍
