### ISSUE TITLE
Source code was not found and transaction value is always app://index.android.bundle

### ISSUE THREAD

**Issue by jycl** [getsentry/react-native-sentry#531]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [X]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v11.1.0
6.4.1
├── react@16.6.3
├── react-native@0.57.8
├── react-native-device-info@0.22.6
├── react-native-fabric@0.5.2
├── react-native-fbsdk@0.8.0
├── react-native-fs@2.12.1
├── react-native-sentry@0.40.2

Config:

```
Sentry.config(SENTRY_DSN[Platform.OS], {
            disableNativeIntegration: true,
}).install();

---
I have following issue:

Events reported by Android devices (with Native Integration disabled) cannot find source code apparently because the `transaction` context value is `app://index.android.bundle` instead of `app:///index.android.bundle`.  No issue on iOS.

Recently disabled native integration, there were no issues on both Android and iOS.

**Steps to reproduce:**
- Configure and build app as described in documentation, source map and bundle are uploaded to Sentry (can see them in Project --> Releases --> Artifacts)

**Actual result:**
- Events display the error: `Source code was not found` and tags contain `transaction:app://index.android.bundle`

**Expected result:**
- Events has symbolicated stack trace and no error
- Tags contain `transaction:app:///index.android.bundle` (iOS shows `transaction:app:///main.jsbundle` and can find source map

I have also attached an image for your reference.
<img width="741" alt="transaction_bundle_path_2" src="https://user-images.githubusercontent.com/20531032/51371249-9e530100-1b34-11e9-98b0-a0263dcd5e80.png">

**Comment by HazAT** [comment]
Closing this for now, merged with your PR, thanks again.
