### ISSUE TITLE
Console log file output is always console.js:35 instead of the real file name and raw number

### ISSUE THREAD

**Issue by zivchen** [getsentry/react-native-sentry#538]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [X]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.11.4
6.7.0
"react-native-sentry": "^0.40.3", (it happend in earlier versions too)
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```
---
I have following issue:
After sentry.config(xx).install() console.log path is wrong

Description goes here ...
After sentry.config(xx).install() all console log output (in chrome or developer tools) position is always console.js:35 and not the actaul file and raw number

**Steps to reproduce:**
Just run sentry.config(xx).install() and open developer tools 

**Actual result:**
console.js:35

**Expected result:**
Actual filename that console.log ran from : raw number

**Comment by zivchen** [comment]
Image that might help
<img width="618" alt="screen shot 2019-01-31 at 12 40 19" src="https://user-images.githubusercontent.com/983093/52049712-1b2fa300-2557-11e9-98ae-54ec31be37f5.png">

**Comment by HazAT** [comment]
It's because `raven-js` patches the `console.log` method underneath so we get breadcrumbs.
Workaround for you would be to disable the SDK in debug mode.

**Comment by ciekawy** [comment]
I'm surprised there is no solution for this till now. What about trying to debug test version of the app where breadcrumbs are valuable but at the same time it's hard to debug seeing bad source point of log message.
