### ISSUE TITLE
Immutable object mutation

### ISSUE THREAD

**Issue by jeroenbourgois** [getsentry/react-native-sentry#64]
`"react-native-sentry": "^0.9.0"`

Hi
I am receiving errors in my app that I believe Sentry wants to catch - which is good. However, this seems te generate an error itself. Any thoughts if this is in the Sentry plugin or somewhere else?

![image](https://cloud.githubusercontent.com/assets/202312/26236451/aef79f1a-3c70-11e7-88f0-2eed3407d444.png)

**Comment by HazAT** [comment]
Duplicate #57

**Comment by jeroenbourgois** [comment]
@HazAT thanks, the workaround in #57 helped me for now

**Comment by HazAT** [comment]
Fixed in `v0.12.10`
