### ISSUE TITLE
Error calling RCTEventEmitter.receiveTouches

### ISSUE THREAD

**Issue by smmoosavi** [getsentry/react-native-sentry#66]
error calling RCTEventEmitter.receiveTouches
```
// index.android.js
Sentry.config('****').install()
```
```
//in some onPress function 
throw new Error('Sentry: Test throw error')
```

![screen](https://cloud.githubusercontent.com/assets/1582954/26275216/ff000cda-3d70-11e7-853d-584f495c274a.png)

same when throw error in render, but with `Error calling JSTimersExcution.callTimers`

## versions:
react@16.0.0-alpha.6
react-native@0.44.0
react-native-sentry@0.9.1
android: 5.1.1

**Comment by Biplab2014** [comment]
I am getting this same problem while trying to log message

**Comment by HazAT** [comment]
@Biplab2014 This should be fixed with the latest release, please upgrade to `v0.12.11`
