### ISSUE TITLE
Can't upload extra data 0.9.1 on android

### ISSUE THREAD

**Issue by ekeuus** [getsentry/react-native-sentry#67]
I've tried Sentry.setDataCallback and setting the data in the data.extra and data.user.extra. This solution worked with the older version and works with this version on iOS. Neither of the following work.

`Sentry.setDataCallback((data) => {
	const newData = {
              ...data,
              extra: {field:true}
       }
	return newData
})`

`Sentry.setDataCallback((data) => {
	const newData = {
              ...data,
              user: {...user, field: true}
       }
	return newData
})`

**Comment by HazAT** [comment]
We need this to be merged first to get support for this:
https://github.com/getsentry/sentry-java/issues/336

**Comment by ekeuus** [comment]
Should this be fixed now that it is merged in?

**Comment by HazAT** [comment]
Oh, haven't noticed it yet.
Will release an update shortly.

**Comment by HazAT** [comment]
This has been fixed with `0.13.3`
