### ISSUE TITLE
`image not found` even with `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` set to `YES`

### ISSUE THREAD

**Issue by jkimbo** [getsentry/react-native-sentry#7]
I'm trying to get react-native-sentry installed and I can't get past the "image not found" issue even though I've enabled `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` in the build settings and did a clean build. Any ideas?

I'm not sure what extra info would be useful for you to see but happy to upload anything that might help. I haven't added the uploading of debug symbols step yet since I'm just trying to get it working on the simulator.

Exception: 
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: [...]/Build/Products/Debug-iphonesimulator/Sentry.framework/Sentry
  Reason: image not found
```

**Comment by HazAT** [comment]
Did you make sure you changed the build step?
https://docs.sentry.io/clients/react-native/#xcode-build-steps

**Comment by jkimbo** [comment]
Ah ok that fixed it. Sorry about that. Since the documentation in the error was in the section before I thought that it wasn't related.

Thanks!

**Comment by HazAT** [comment]
We will try to improve that, glad it worked!
