### ISSUE TITLE
Invalid Swift Support error from iTunes Connect

### ISSUE THREAD

**Issue by ndbroadbent** [getsentry/react-native-sentry#73]
I'm getting the following error email when trying to submit my app to iTunes:

> Invalid Swift Support - The file myapp.app/Frameworks/KSCrash.framework, myapp.app/Frameworks/Sentry.framework doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

I'm not using Swift, so I think this error message is not very accurate.

This doesn't happen without Sentry, and it seems to be related to the new frameworks that were added. (`Sentry.framework` and `KSCrash.framework`.) Any ideas what I can try?

I'm using Cocoapods for some other libraries, if that's related.

**Comment by ndbroadbent** [comment]
Just confirming that I removed `react-native-sentry` from my iOS build, and I was able to upload the app to iTunes connect without any errors. So it definitely seems to be a problem with these frameworks.

**Comment by HazAT** [comment]
Hey, please upgrade to the latest release `0.11.0`.
We dropped the whole bundle frameworks step so there shouldn't be any signing issues anymore.

**Comment by ndbroadbent** [comment]
Ah great, I was using `0.10.0`. Will upgrade to `0.11.0` and see if that fixes things.

**Comment by ndbroadbent** [comment]
If anyone else sees this, I'm just confirming that I successfully submitted my app using version `0.11.4`.

**Comment by robbiet480** [comment]
I just started getting this error today after upgrading from 0.6.0 to 0.12.12. I unlinked and relinked before submitting a build.

**Comment by robbiet480** [comment]
@HazAT any help?

**Comment by HazAT** [comment]
Sorry, Sentry or KSCrash can't be the reason for `Invalid Swift Support` anymore for you @robbiet480 because there is no Swift anymore ^^
Check your Xcode project, there shouldn't be a `Sentry.framework` or `KSCrash.framework` (only if you are using CocoaPods).

**Comment by robbiet480** [comment]
@HazAT Those frameworks don't exist, but I do have some schemes relating to them.

<img width="250" alt="screen shot 2017-06-20 at 10 44 55 am" src="https://user-images.githubusercontent.com/18516/27347475-8b52495e-55a5-11e7-86ad-2f17521371aa.png">

**Comment by robbiet480** [comment]
Turns out this was an issue with a notification extension which used Swift. Removing it entirely fixed the problems. Thanks for the help @HazAT!
