### ISSUE TITLE
yarn download sentry-cli every time

### ISSUE THREAD

**Issue by smmoosavi** [getsentry/react-native-sentry#74]
after I add react-native-sentry to my project, every time I run yarn command `sentry-cli-Linux-x86_64` is fetching. (and this is so annoying)
I have `sentry-cli 1.10.2` in my global packages

react-native-sentry@0.10.0
yarn 0.23.4

**Comment by mitsuhiko** [comment]
Opened the issue in the correct project. Closing it here.
