### ISSUE TITLE
Documentation update auth token

### ISSUE THREAD

**Issue by lefloh** [getsentry/react-native-sentry#75]
The (awesome!) setup script asks for DSN including secret and auth token. I thought that auth tokens are used in combination with public DSNs without secrets. Why do I need to provide both?
Could you add some explanation to the documentation and especially which scopes are necessary for the auth token?

**Comment by HazAT** [comment]
Hey,
Since we are also building source maps and upload them, we need the auth token in order for the server to accept it.
We will update the documentation accordingly to make this clearer.

**Comment by lefloh** [comment]
I see! Makes perfectly sense! Thanks for the quick response!

**Comment by jordanmkoncz** [comment]
@HazAT any chance you could also add to the documentation a list of the minimum scopes required for the auth token to allow the react-native-sentry configuration to work correctly?

**Comment by HazAT** [comment]
Will do, we are currently refactoring the docs/react-native setup.
`project:releases` is enough just to clarify it now ;)
