### ISSUE TITLE
KSCrashHandler not started

### ISSUE THREAD

**Issue by maggialejandro** [getsentry/react-native-sentry#81]
Hi guys, I'm having this issue on iOS

XCode Log:
```bash
AppName [49093:1897388] Sentry Started -- Version: 3.0.0
AppName [49093:1897388] Sentry - Error:: KSCrashHandler not started - Make sure you added KSCrash as a dependency
[fatal][tid:io.sentry.RNSentry] Exception 'KSCrashHandler not started - Make sure you added KSCrash as a dependency' was thrown while invoking startWithDsnString on target RNSentry with params (
 "https://aaaac9f0fd024d00bd6fee01d11aaaaa:08daaaaf6863aaaa8e4e1d3cc705aaaa@sentry.io/174222"
)
```

![captura de pantalla 2017-06-02 a las 12 07 28 p m](https://cloud.githubusercontent.com/assets/3394748/26732565/6552b5a6-478e-11e7-8f64-bd190df72d20.png)

react-native 0.42.2
react-native-sentry 0.11.1
xcode 8.2.1

any ideas?

**Comment by HazAT** [comment]
Are you using cocoapods?

**Comment by HazAT** [comment]
Also please upgrade to the latest version and make sure to run `react-native unlink react-native-sentry` and `react-native link react-native-sentry`

**Comment by maggialejandro** [comment]
Updating to 0.11.6 then unlink and link the library made it work. Thanks @HazAT
