### ISSUE TITLE
gradlew assembleRelease Error on Windows

### ISSUE THREAD

**Issue by HAMPLENI** [getsentry/react-native-sentry#82]
OS: Windows 7 64-bit
react-native-cli Version: 2.0.1
react-native Version: 0.44.2
npm Version: 4.6.1
react-native-sentry Version: 0.11.6

1. Open Command Prompt as an Administrator.
2. react-native init AwesomeProject
3. cd AwesomeProject
4. npm install react-native-sentry --save
5. react-native link react-native-sentry
6. Answered the questions asked in the Command Prompt.
7. cd android
8. gradlew assembleRelease
9. The following error occurs:

'...\AwesomeProject/node_modules/sentry-cli-binary/bin/sentry-cli' is not recognized as an internal or external command,
operable program or batch file.
:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

\* Where:
Script '...\AwesomeProject\node_modules\react-native-sentry\sentry.gradle' line: 115

\* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssetsSentryUpload'.
\> Process 'command 'cmd'' finished with non-zero exit value 1

**Comment by wisedrette** [comment]
jic, I've described possible solution in #https://github.com/getsentry/react-native-sentry/issues/91

**Comment by HazAT** [comment]
Fixed in `0.12.5`
