### ISSUE TITLE
Issue report on Sentry page doesn't look as expected

### ISSUE THREAD

**Issue by KatarinaSimnova** [getsentry/react-native-sentry#86]
#I tried your example code and issue report doesn't look like your example from README file.
I need filename and line where the crash happened. It shows just this:
![screen shot 2017-06-06 at 1 26 43 pm](https://cloud.githubusercontent.com/assets/11189150/26827316/efd886fc-4abc-11e7-8771-bc11092cc6b4.png)
I have also implemented my own crash (null reference error). Sentry shows some random files and lines as a crash localization (not filename and line where my crash happened).
Are there any additional settings to make this work? Or it's a bug.

**Comment by mitsuhiko** [comment]
Did you upload sourcemaps and debug symbols?

**Comment by KatarinaSimnova** [comment]
I found out that my sourcemaps are not uploaded correctly. Could you provide any step by step instructions how to do that for react native? I'm using sentry-cli.

**Comment by mitsuhiko** [comment]
Hi @KatarinaSimnova. Did you integrate the xcode release process? If you make a new release with xcode it should then automatically upload sourcemaps and debug symbols.

If you upgrade from an older version of react-native-sentry run `react-native unlink react-native-sentry` followed by `react-native link react-native-sentry`.

**Comment by KatarinaSimnova** [comment]
Xcode automatically upload debug symbols but no sourcemaps.
I also tried to upload sourcemaps manually: 
![screen shot 2017-06-07 at 4 04 30 pm](https://user-images.githubusercontent.com/11189150/26882916-065ff222-4b9c-11e7-9026-c685c9c1fd90.png)
Am I doing something wrong?

**Comment by HazAT** [comment]
Hey @KatarinaSimnova 
Xcode should handle everything automatically, please make sure your `Build Steps` contain this step:
<img width="809" alt="screen shot 2017-06-08 at 10 10 53" src="https://user-images.githubusercontent.com/363802/26918599-f70c40d6-4c32-11e7-8c95-4f479bc6e6df.png">
`react-native link react-native-sentry` should add this to your project.

**Comment by KatarinaSimnova** [comment]
Now sourcemaps work but still not as expected :( 
![screen shot 2017-06-08 at 12 30 53 pm](https://user-images.githubusercontent.com/11189150/26924697-2f4ad7e6-4c47-11e7-8b3a-e40b5ce04c66.png)

**Comment by HazAT** [comment]
@KatarinaSimnova This looks fine :)
It's just that the crash and the internal code structure changed that's why it doesn't look exactly the same.
But I will close this now since there isn't any bug/issue anymore.
