### ISSUE TITLE
How can we use react-native-sentry in a mixed react-native app

### ISSUE THREAD

**Issue by julienfouilhe** [getsentry/react-native-sentry#9]
I'm have a swift app, and I'm using react-native for only a part of the app. I was successfully using raven-js until now but I wanted to upgrade to this, how can we use it in a mixed environment? Could you provide a .podspec file maybe?

Thanks!

**Comment by myusuf3** [comment]
You can just pull in library like so documented in react native with just a few tweaks https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by HazAT** [comment]
You `0.5.x` contains a podspec ... see releases.
