### ISSUE TITLE
Not compatible with windows 10 build

### ISSUE THREAD

**Issue by nenti** [getsentry/react-native-sentry#91]
When running `./grandlew assembleRelease` in the postinstall sentry crashes with following error: 
```
Unknown command "C:\Users\piust\Documents\app/node_modules/sentry-cli-binary/bin/sentry-cli"

* Where:
Script 'C:\Users\piust\Documents\app\node_modules\react-native-sentry\sentry.gradle' line: 115
```

I installed sentry-cli globally because apparently a binary like this can't be executed on windows.

**Comment by wisedrette** [comment]
Hey, I've stumbled across the same problem. 
That can be hot-fixed by either copying sentry-cli file from sentry-cli-binary/ into sentry-cli-binary/bin/ directory. Otherwise '/bin/' part should be removed from react-native-sentry/sentry.gradle in line 63
	
Although after fixing it I'm getting 
```
> Adding source map references
error: http error: Authentication credentials were not provided. (401)
:app:bundleReleaseJsAndAssets FAILED
```

Could you please let me know if you have same issue as well after fixing this one?

**Comment by HazAT** [comment]
@wisedrette Did you run `react-native link react-native-sentry` ... this will create a file called `sentry.properties` where this information is stored.

**Comment by mitsuhiko** [comment]
God dammit. I knew this would regress. This was a side effect of fixing our yarn build issue.

**Comment by HazAT** [comment]
Dup https://github.com/getsentry/react-native-sentry/issues/82

**Comment by fauzzi** [comment]
Getting same error
 "react-native": "0.44.0",
 "react-native-sentry": "^0.21.1"

sentry.properties
cli.executable=node_modules\sentry-cli-binary\bin\sentry-cli

sentry.gradle 
    def cliExecutable = sentryProps.get("cli.executable", "$reactRoot/node_modules/sentry-cli-binary/bin/sentry-cli");

**Comment by Fuhrmann** [comment]
I was having the same problem in Windows 10. I managed to get it working by changing:

```
cli.executable=node_modules/sentry-cli-binary/bin/sentry-cli
```

To this:

```
cli.executable=node node_modules/sentry-cli-binary/bin/sentry-cli
                ▲
```
