### ISSUE TITLE
Windows "npm install react-native-sentry --save" Fails

### ISSUE THREAD

**Issue by HAMPLENI** [getsentry/react-native-sentry#96]
OS: Windows 7 64-bit
react-native-cli Version: 2.0.1
react-native Version: 0.45.0
npm Version: 4.6.1
react-native-sentry Version: 0.12.6

1. Open Command Prompt as an Administrator.
2. react-native init AwesomeProject
3. cd AwesomeProject
4. npm install react-native-sentry --save
5. The install fails:

\> sentry-cli-binary@1.13.3 install ...\AwesomeProject\node_modules\sentry-cli-binary
\> node ./bin/install-sentry-cli

fetching sentry-cli-Windows-i686.exe ████████████████████ 100% 0.0s
Something went wrong!
{ Error: Command failed: ...\AwesomeProject\node_modules\sentry-cli-binary\bin\sentry-cli.exe --version

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 3221225595,
  signal: null,
  cmd: '...\\AwesomeProject\\node_modules\\sentry-cli-binary\\bin\\sentry-cli.exe --version' }
AwesomeProject@0.0.1 ...\AwesomeProject
+-- external-editor@2.0.4  extraneous
+-- is-promise@2.1.0  extraneous
+-- mimic-fn@1.1.0  extraneous
+-- raven-js@3.15.0  extraneous
+-- rx@4.1.0  extraneous
`-- signal-exit@3.0.2  extraneous

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentry-cli-binary@1.13.3 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sentry-cli-binary@1.13.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\AppData\Roaming\npm-cache\_logs\2017-06-08T16_39_30_319Z-debug.log

**Comment by nenti** [comment]
npm now installes `sentry-cli-bin` to a sub `node_modules` folder rather than to the top level

**Comment by OllaAshour** [comment]
Is there a fix to this? I'm running on windows 7

**Comment by nenti** [comment]
npm install -save-dev sentry-cli-bin

**Comment by HAMPLENI** [comment]
I added a new issue here:

https://github.com/getsentry/sentry-cli/issues/92

**Comment by HAMPLENI** [comment]
getsentry/sentry-cli#92

**Comment by HazAT** [comment]
I will close this now since this seems to be resolved in `sentry-cli` https://github.com/getsentry/sentry-cli/issues/92

**Comment by HAMPLENI** [comment]
I can confirm that it has been resolved.  Thanks for the help!  :)
