### ISSUE TITLE
iOS: Sentry.setUserContext throws an exception

### ISSUE THREAD

**Issue by outpunk** [getsentry/react-native-sentry#98]
Hello,

I've added Sentry using the following doc https://docs.sentry.io/clients/react-native/config/.
And it throws an error every time I try to set a user's data like so:

```js
  Sentry.setUserContext({
    email:    user.email,
    userId:   user.id,
    username: user.name,

    extra: {
      confirmed:  user.confirmed,
    },
  });
```

Here is the error:

```
ExceptionsManager.js:71 Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]' was thrown while invoking setUser on target RNSentry with params (
        {
        email = "user@example.com";
        extra =         {
            confirmed = 1;
        };
        userId = "1234";
        username = "Username";
    }
)
```

Package version is 0.12.9

**Comment by jeroenbourgois** [comment]
Is happening on 0.11.8 also

**Comment by HazAT** [comment]
I am not able to reproduce this.
What's even more strange is that I don't see the nil value when react-native is reporting the exception.

**Comment by outpunk** [comment]
@HazAT added the package version to the description — 0.12.9

**Comment by wielrls** [comment]
It looks like RN Sentry expects there to always be a property `userID` (note uppercase 'D') on the user object:

https://github.com/getsentry/react-native-sentry/blob/master/ios/RNSentry.m#L303

@outpunk in your example you are instead using lowercase 'd' in `userId`

**Comment by HazAT** [comment]
@wielrls wow good catch, that's it. Considering releasing a fix to allow both, in the meantime please change it to `userID`.

**Comment by outpunk** [comment]
Ooops, thank you guys!

**Comment by HazAT** [comment]
In the latest release >= 0.14.10 I've added support for
userId
userID
id
so this shouldn't anymore.
