### ISSUE TITLE
Debug symbol upload failed

### ISSUE THREAD

**Issue by juhaelee** [getsentry/react-native-sentry#99]
Hello! I'm running into a few issues with React-native-sentry. Help and clarification would be greatly appreciated!

1)
Whenever I run from simulator, xcode throws me the following error:
`
The Sentry build step failed while running in the background. You can ignore this error or view details to attempt to resolve it. Ignoring it might cause your crashes not to be handled properly.
`
Is this the intended behavior?

2)
I also noticed in the docs (https://docs.sentry.io/clients/react-native/manual-setup/) that running `react-native link react-native-sentry` should add the following script to Build Phases: `“Bundle react-native-sentry Frameworks”`, However, the only phase that gets added is `Upload Debug Symbols to Sentry`. Are the docs out of date, or is this a bug?

3)
When you run `react-native unlink react-native-sentry` it deletes the following build script completely which I believe is not the intended behavior: `Bundle React Native code and images`

**Comment by HazAT** [comment]
Hey,
1. Yeah, this is intended behavior if we would do this with every debug build in the simulator it would take much longer.
https://docs.sentry.io/clients/react-native/manual-setup/#build-steps
> Note that uploading of debug simulator builds by default is disabled for speed reasons. If you do want to also generate debug symbols for debug builds you can pass –allow-fetch as a parameter to react-native-xcode in the above mentioned build phase.
2. Thanks for pointing that out, I've updated the docs, this step no longer exists.
3. You are right, it should not remove that step completely, we'll look into this.

**Comment by HazAT** [comment]
I wasn't able to reproduce that this step gets removed completely.
`Bundle React Native code and images`
Tested with a fresh `react-native init` Xcode project.

**Comment by juhaelee** [comment]
thanks @HazAT !!!
